app:
  name: assistant
  port: 1234
  root:
    username: admin
    password: AAaa00__
    email: admin@example.com

db:
  driver_name: mysql
  dsn: assistant:AAaa00__@tcp(127.0.0.1:3306)/assistant?charset=utf8mb4&parseTime=True&loc=Local
  max_open_conns: 20
  max_idle_conns: 10
  conn_max_life_time: 1h
  conn_max_idle_time: 30m

dislock:
  default_ttl: 30
  max_ttl: 300

log:
  level: debug
  filename: ./logs/assistant.log
  max_size_mb: 16
  max_backups: 7
  max_age_days: 14
  compress: true
  josn_format: true
  console: true

