package psl

var userTables = []UpDownSQL{
	{
		UpSQL: `
		CREATE TABLE IF NOT EXISTS sys_user (
			id BIGINT AUTO_INCREMENT NOT NULL,
			gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
			gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
			user_name VARCHAR(255) NOT NULL DEFAULT '',
			password VARCHAR(255) NOT NULL DEFAULT '',
			email VARCHAR(128) NOT NULL DEFAULT '',
			PRIMARY KEY (id),
			UNIQUE KEY uk_user_name (user_name),
			UNIQUE KEY uk_email (email)
		) COMMENT='用户表';
		`,
		DownSQL: `
		DROP TABLE IF EXISTS sys_user;
		`,
	},
	{
		UpSQL: `
		CREATE TABLE IF NOT EXISTS sys_server (
			id BIGINT AUTO_INCREMENT NOT NULL,
			gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
			gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
			idc VARCHAR(64) NOT NULL DEFAULT '',
			svr_ip VARCHAR(32) NOT NULL DEFAULT '127.1',
			ak VARCHAR(255) NOT NULL DEFAULT '',
			sk VARCHAR(2048) NOT NULL DEFAULT '',
			svr_status VARCHAR(32) NOT NULL DEFAULT '',
			PRIMARY KEY (id),
			UNIQUE KEY uk_svr_ip (svr_ip)
		) COMMENT='服务器表';
		`,
		DownSQL: `
		DROP TABLE IF EXISTS sys_server;
		`,
	},
	{
		UpSQL: `
		CREATE TABLE IF NOT EXISTS todo_list (
			id BIGINT AUTO_INCREMENT NOT NULL,
			gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
			gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
			title VARCHAR(255) NOT NULL DEFAULT '',
			content VARCHAR(4096) NOT NULL DEFAULT '',
			deadline VARCHAR(128) NOT NULL DEFAULT '',
			progress INT NOT NULL DEFAULT 0,
			priority INT NOT NULL DEFAULT 5,
			task_status ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED') NOT NULL DEFAULT 'PENDING',
			PRIMARY KEY (id),
			KEY idx_priority (priority DESC)
		) COMMENT='代办事项表';
		`,
		DownSQL: `
		DROP TABLE IF EXISTS todo_list;
		`,
	},
}
