package psl

var userTables = []UpDownSQL{
	{
		UpSQL: `
		CREATE TABLE IF NOT EXISTS sys_user (
			id BIGINT AUTO_INCREMENT,
			gmt_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			gmt_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
			user_name VARCHAR(255) NOT NULL,
			password VARCHAR(255) NOT NULL,
			email VARCHAR(128) NOT NULL,
			PRIMARY KEY (id),
			UNIQUE KEY (user_name),
			UNIQUE KEY (email)
		) COMMENT='用户表';
		`,
		DownSQL: `
		DROP TABLE IF EXISTS sys_user;
		`,
	},
	{
		UpSQL: `
		CREATE TABLE IF NOT EXISTS sys_server (
			id BIGINT AUTO_INCREMENT,
			gmt_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			gmt_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
			idc VARCHAR(64) NOT NULL DEFAULT '',
			svr_ip VARCHAR(32) NOT NULL DEFAULT '127.1',
			ak VARCHAR(255) NOT NULL DEFAULT '',
			sk TEXT NOT NULL,
			svr_status VARCHAR(32) NOT NULL DEFAULT '',
			PRIMARY KEY (id),
			UNIQUE KEY (svr_ip)
		) COMMENT='服务器表';
		`,
		DownSQL: `
		DROP TABLE IF EXISTS server;
		`,
	},
	{
		UpSQL: `
		CREATE TABLE IF NOT EXISTS todo_list (
			id BIGINT AUTO_INCREMENT,
			gmt_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			gmt_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
			title VARCHAR(255) NOT NULL,
			content text NOT NULL,
			deadline VARCHAR(128) NOT NULL,
			is_done BOOLEAN DEFAULT TRUE,
			PRIMARY KEY (id)
		) COMMENT='代办事项表';
		`,
		DownSQL: `
		DROP TABLE IF EXISTS todo_list;
		`,
	},
}
