
CREATE TABLE IF NOT EXISTS server (
  id BIGINT AUTO_INCREMENT NOT NULL,
  gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  idc VARCHAR(64) NOT NULL DEFAULT '',
  svr_ip VARCHAR(32) NOT NULL DEFAULT '127.1',
  ak VARCHAR(255) NOT NULL DEFAULT '',
  sk TEXT NOT NULL,
  svr_status VARCHAR(32) NOT NULL DEFAULT '',
  PRIMARY KEY (id),
  UNIQUE KEY (svr_ip)
) COMMENT='服务器表';
