CREATE TABLE IF NOT EXISTS sys_server (
  id BIGINT AUTO_INCREMENT NOT NULL,
  gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  idc VARCHAR(64) NOT NULL DEFAULT '',
  svr_ip VARCHAR(32) NOT NULL DEFAULT '127.1',
  svr_status VARCHAR(32) NOT NULL DEFAULT '',
  cpu_usage FLOAT NOT NULL DEFAULT 0,
  mem_usage FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_svr_ip (svr_ip)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='服务器表';
