CREATE TABLE IF NOT EXISTS task_workflow_instance (
  id BIGINT AUTO_INCREMENT NOT NULL,
  gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  workflow_def_id BIGINT NOT NULL COMMENT '关联工作流定义ID',
  workflow_def_version INT DEFAULT 1 COMMENT '工作流定义版本',
  trigger_type ENUM('MANUAL', 'SCHEDULED', 'API', 'EVENT', 'DEPENDENCY') NOT NULL DEFAULT 'MANUAL' COMMENT '触发类型',
  trigger_id VARCHAR(128) DEFAULT NULL COMMENT '触发源ID',
  input_params JSON DEFAULT NULL COMMENT '输入参数',
  status ENUM('PENDING', 'RUNNING', 'PAUSED', 'SUCCESS', 'FAILED', 'CANCELLED', 'ROLLING_BACK') NOT NULL DEFAULT 'PENDING' COMMENT '执行状态',
  status_reason VARCHAR(512) DEFAULT NULL COMMENT '状态原因',
  current_node_id VARCHAR(64) DEFAULT NULL COMMENT '当前执行节点',
  execution_mode ENUM('SYNCHRONOUS', 'ASYNCHRONOUS') DEFAULT 'ASYNCHRONOUS' COMMENT '执行模式',
  priority INT DEFAULT 5 COMMENT '调度优先级',
  gmt_start TIMESTAMP DEFAULT NULL COMMENT '开始时间',
  gmt_end TIMESTAMP DEFAULT NULL COMMENT '结束时间',
  gmt_paused TIMESTAMP DEFAULT NULL COMMENT '暂停时间',
  total_nodes INT DEFAULT 0 COMMENT '总节点数',
  completed_nodes INT DEFAULT 0 COMMENT '已完成节点数',
  failed_nodes INT DEFAULT 0 COMMENT '失败节点数',
  result_summary JSON DEFAULT NULL COMMENT '执行结果汇总',
  error_info JSON DEFAULT NULL COMMENT '错误信息',
  created_by VARCHAR(128) DEFAULT NULL COMMENT '创建人',
  PRIMARY KEY (id),
  KEY idx_wf_def (workflow_def_id),
  KEY idx_status (status),
  KEY idx_priority (status, priority DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工作流实例表';
