CREATE TABLE IF NOT EXISTS task_schedule (
  id BIGINT AUTO_INCREMENT NOT NULL,
  gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  name VARCHAR(128) NOT NULL COMMENT '调度名称',
  description TEXT COMMENT '调度描述',
  workflow_def_id BIGINT NOT NULL COMMENT '关联工作流定义ID',
  schedule_type ENUM('CRON', 'INTERVAL', 'ONCE') NOT NULL COMMENT '调度类型',
  cron_expr VARCHAR(64) DEFAULT NULL COMMENT 'Cron 表达式',
  interval_seconds INT DEFAULT NULL COMMENT '间隔秒数',
  execute_at TIMESTAMP DEFAULT NULL COMMENT '单次执行时间',
  input_params JSON DEFAULT NULL COMMENT '默认输入参数',
  status ENUM('ENABLED', 'DISABLED', 'PAUSED') DEFAULT 'ENABLED' COMMENT '状态',
  last_execute_id BIGINT DEFAULT NULL COMMENT '最近执行的实例ID',
  next_execute_at TIMESTAMP DEFAULT NULL COMMENT '下次执行时间',
  created_by VARCHAR(128) DEFAULT NULL COMMENT '创建人',
  PRIMARY KEY (id),
  KEY idx_wf_status (workflow_def_id, status),
  KEY idx_next_exec (next_execute_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='任务调度表';
