
CREATE TABLE IF NOT EXISTS task_composite (
  id BIGINT AUTO_INCREMENT NOT NULL,
  gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	task_tmpl_id BIGINT UNSIGNED NOT NULL,
	task_atomic_id BIGINT UNSIGNED NOT NULL,
	step_order INT NOT NULL,
	depends_on JSON NOT NULL,
	PRIMARY KEY (id),
	UNIQUE KEY (task_tmpl_id, step_order)
) COMMENT='任务模板与原子任务映射关系';
