CREATE TABLE IF NOT EXISTS task_workflow_def (
  id BIGINT AUTO_INCREMENT NOT NULL,
  gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  name VARCHAR(128) NOT NULL COMMENT '工作流名称',
  description TEXT COMMENT '工作流描述',
  version INT DEFAULT 1 COMMENT '版本号',
  workflow_type ENUM('SEQUENTIAL', 'PARALLEL', 'DAG', 'CONDITIONAL') NOT NULL DEFAULT 'DAG' COMMENT '工作流类型',
  graph_config JSON NOT NULL COMMENT 'DAG 图配置',
  parameters JSON DEFAULT NULL COMMENT '输入参数定义',
  timeout INT DEFAULT 3600 COMMENT '整体超时时间(秒)',
  on_error_strategy ENUM('STOP', 'CONTINUE', 'ROLLBACK') DEFAULT 'STOP' COMMENT '错误处理策略',
  notification_config JSON DEFAULT NULL COMMENT '通知配置',
  status ENUM('DRAFT', 'ENABLED', 'DISABLED', 'DEPRECATED') DEFAULT 'DRAFT' COMMENT '状态',
  created_by VARCHAR(128) DEFAULT NULL COMMENT '创建人',
  PRIMARY KEY (id),
  UNIQUE KEY uk_name_version (name, version),
  KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='任务工作流定义表';
