CREATE TABLE IF NOT EXISTS task_workflow_edge (
  id BIGINT AUTO_INCREMENT NOT NULL,
  gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  workflow_id BIGINT NOT NULL COMMENT '关联工作流定义ID',
  from_node_id VARCHAR(64) NOT NULL COMMENT '源节点ID',
  to_node_id VARCHAR(64) NOT NULL COMMENT '目标节点ID',
  edge_type ENUM('SEQUENTIAL', 'CONDITION_TRUE', 'CONDITION_FALSE', 'PARALLEL') DEFAULT 'SEQUENTIAL' COMMENT '边类型',
  condition_expr TEXT DEFAULT NULL COMMENT '条件表达式',
  PRIMARY KEY (id),
  UNIQUE KEY uk_wf_edge (workflow_id, from_node_id, to_node_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工作流边定义表';
