
CREATE TABLE IF NOT EXISTS task_tmpl (
  id BIGINT AUTO_INCREMENT NOT NULL,
  gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	name VARCHAR(255) NOT NULL,
	description TEXT NOT NULL,
	config JSON NOT NULL,
	is_enable BOOLEAN NOT NULL DEFAULT TRUE,
	PRIMARY KEY (id),
	UNIQUE KEY (name)
) COMMENT='任务模板表, 由多个原子任务编排而成';
