
CREATE TABLE IF NOT EXISTS task_atomic (
  id BIGINT AUTO_INCREMENT NOT NULL,
  gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	name VARCHAR(255) NOT NULL,
	description TEXT NOT NULL,
	task_type VARCHAR(48) NOT NULL,
	config JSON NOT NULL,
	is_enable BOOLEAN NOT NULL DEFAULT TRUE,
	PRIMARY KEY (id),
	UNIQUE KEY (name)
) COMMENT='任务原子表'
