CREATE TABLE IF NOT EXISTS task_node_instance (
  id BIGINT AUTO_INCREMENT NOT NULL,
  gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  workflow_instance_id BIGINT NOT NULL COMMENT '关联工作流实例ID',
  node_def_id BIGINT NOT NULL COMMENT '关联节点定义ID',
  node_id VARCHAR(64) NOT NULL COMMENT '节点标识',
  status ENUM('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'SKIPPED', 'CANCELLED', 'ROLLING_BACK', 'ROLLED_BACK') NOT NULL DEFAULT 'PENDING' COMMENT '执行状态',
  status_reason VARCHAR(512) DEFAULT NULL COMMENT '状态原因',
  input_params JSON DEFAULT NULL COMMENT '输入参数',
  output_result JSON DEFAULT NULL COMMENT '输出结果',
  execution_log TEXT DEFAULT NULL COMMENT '执行日志',
  error_log TEXT DEFAULT NULL COMMENT '错误日志',
  retry_count INT DEFAULT 0 COMMENT '已重试次数',
  gmt_start TIMESTAMP DEFAULT NULL COMMENT '开始时间',
  gmt_end TIMESTAMP DEFAULT NULL COMMENT '结束时间',
  duration_ms INT DEFAULT NULL COMMENT '执行耗时(毫秒)',
  worker_id VARCHAR(64) DEFAULT NULL COMMENT '执行 worker ID',
  PRIMARY KEY (id),
  UNIQUE KEY uk_wi_nid (workflow_instance_id, node_id),
  KEY idx_wi_status (workflow_instance_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='任务节点实例表';
