CREATE TABLE IF NOT EXISTS task_atomic_instance (
  id BIGINT AUTO_INCREMENT NOT NULL,
  gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  node_instance_id BIGINT NOT NULL COMMENT '关联节点实例ID',
  task_atomic_def_id BIGINT NOT NULL COMMENT '关联原子任务定义ID',
  status ENUM('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'ROLLED_BACK') NOT NULL DEFAULT 'PENDING' COMMENT '执行状态',
  input_params JSON DEFAULT NULL COMMENT '输入参数',
  output_result JSON DEFAULT NULL COMMENT '输出结果',
  execution_log TEXT DEFAULT NULL COMMENT '执行日志',
  error_log TEXT DEFAULT NULL COMMENT '错误日志',
  rollback_log TEXT DEFAULT NULL COMMENT '回滚日志',
  rollback_result JSON DEFAULT NULL COMMENT '回滚结果',
  timeout INT DEFAULT NULL COMMENT '超时时间',
  gmt_start TIMESTAMP DEFAULT NULL COMMENT '开始时间',
  gmt_end TIMESTAMP DEFAULT NULL COMMENT '结束时间',
  duration_ms INT DEFAULT NULL COMMENT '执行耗时(毫秒)',
  worker_id VARCHAR(64) DEFAULT NULL COMMENT '执行 worker ID',
  PRIMARY KEY (id),
  KEY idx_ni_status (node_instance_id, status),
  KEY idx_tad (task_atomic_def_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='原子任务实例表';
