
CREATE TABLE IF NOT EXISTS task_def (
  id BIGINT AUTO_INCREMENT NOT NULL,
  gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  task_type ENUM('ATOMIC', 'COMPOSITE') NOT NULL DEFAULT 'ATOMIC',
  config JSON DEFAULT NULL,
  retry_policy JSON DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_n (name),
  KEY idx_n_tt (name, task_type)
) COMMENT='任务定义表, 可复用模板';

