CREATE TABLE IF NOT EXISTS task_atomic_def (
  id BIGINT AUTO_INCREMENT NOT NULL,
  gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  name VARCHAR(128) NOT NULL COMMENT '原子任务名称',
  description TEXT COMMENT '任务描述',
  task_category ENUM('SCRIPT', 'HTTP_API', 'BUILTIN') NOT NULL DEFAULT 'SCRIPT' COMMENT '任务类别',
  script_type ENUM('SHELL', 'PYTHON', 'LUA', 'JAVASCRIPT', 'OTHER') DEFAULT NULL COMMENT '脚本类型',
  script_content LONGTEXT NOT NULL COMMENT '脚本内容',
  rollback_script_type ENUM('SHELL', 'PYTHON', 'LUA', 'JAVASCRIPT', 'OTHER') DEFAULT NULL COMMENT '回滚脚本类型',
  rollback_script_content LONGTEXT DEFAULT NULL COMMENT '回滚脚本内容',
  http_config JSON DEFAULT NULL COMMENT 'HTTP API 配置',
  builtin_config JSON DEFAULT NULL COMMENT '内置任务配置',
  timeout INT DEFAULT 300 COMMENT '超时时间(秒)',
  retry_count INT DEFAULT 0 COMMENT '重试次数',
  retry_interval INT DEFAULT 5 COMMENT '重试间隔(秒)',
  is_rollback_supported BOOLEAN DEFAULT TRUE COMMENT '是否支持回滚',
  parameters JSON DEFAULT NULL COMMENT '参数定义',
  output_schema JSON DEFAULT NULL COMMENT '输出 schema',
  env_vars JSON DEFAULT NULL COMMENT '环境变量',
  working_dir VARCHAR(512) DEFAULT NULL COMMENT '工作目录',
  status ENUM('ENABLED', 'DISABLED') DEFAULT 'ENABLED' COMMENT '状态',
  PRIMARY KEY (id),
  UNIQUE KEY uk_name (name),
  KEY idx_cat_st (task_category, script_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='原子任务定义表';
