CREATE TABLE IF NOT EXISTS todo_list (
  id BIGINT AUTO_INCREMENT NOT NULL,
  gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  title VARCHAR(255) NOT NULL,
  content text NOT NULL,
  deadline VARCHAR(128) NOT NULL,
  progress INT NOT NULL DEFAULT 0,
  priority INT NOT NULL DEFAULT 5,
  task_status ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED') NOT NULL DEFAULT 'PENDING',
  PRIMARY KEY (id),
  KEY idx_priority (priority DESC)
) COMMENT='代办事项表';

