
CREATE TABLE IF NOT EXISTS todo_list (
  id BIGINT AUTO_INCREMENT NOT NULL,
  gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	title VARCHAR(255) NOT NULL,
	content text NOT NULL,
	deadline VARCHAR(128) NOT NULL,
	is_done BOOLEAN NOT NULL DEFAULT TRUE,
	PRIMARY KEY (id)
) COMMENT='代办事项表';
