// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/schedule/create": {
            "post": {
                "description": "创建一个新的任务调度，支持 Cron/Interval/Once 三种类型",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务调度"
                ],
                "summary": "创建任务调度",
                "parameters": [
                    {
                        "description": "调度创建参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_app_modules_task_orchestration.CreateScheduleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/schedule/delete/{id}": {
            "delete": {
                "description": "根据 ID 删除任务调度",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务调度"
                ],
                "summary": "删除任务调度",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "调度ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/schedule/disable/{id}": {
            "post": {
                "description": "根据 ID 禁用任务调度\n根据 ID 禁用任务调度",
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "任务调度",
                    "任务调度"
                ],
                "summary": "禁用任务调度",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "调度ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "调度ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/schedule/enable/{id}": {
            "post": {
                "description": "根据 ID 启用已禁用的任务调度",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务调度"
                ],
                "summary": "启用任务调度",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "调度ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/schedule/get/{id}": {
            "get": {
                "description": "根据 ID 获取任务调度详细信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务调度"
                ],
                "summary": "获取任务调度详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "调度ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "调度不存在",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/schedule/list": {
            "get": {
                "description": "分页查询任务调度列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务调度"
                ],
                "summary": "获取任务调度列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量 (默认20, 最大100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/schedule/update/{id}": {
            "put": {
                "description": "根据 ID 更新任务调度信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务调度"
                ],
                "summary": "更新任务调度",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "调度ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_app_modules_task_orchestration.CreateScheduleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/task_atomic/count": {
            "get": {
                "description": "统计系统中所有启用的原子任务数量",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "原子任务管理"
                ],
                "summary": "获取原子任务总数",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/task_atomic/create": {
            "post": {
                "description": "创建一个新的原子任务，支持 Shell/Python/Lua 脚本或 HTTP API 调用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "原子任务管理"
                ],
                "summary": "创建原子任务",
                "parameters": [
                    {
                        "description": "原子任务创建参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_app_modules_task_orchestration.CreateTaskAtomicRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/task_atomic/delete/{id}": {
            "delete": {
                "description": "根据 ID 删除原子任务",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "原子任务管理"
                ],
                "summary": "删除原子任务",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "原子任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/task_atomic/get/{id}": {
            "get": {
                "description": "根据 ID 获取原子任务详细信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "原子任务管理"
                ],
                "summary": "获取原子任务详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "原子任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "任务不存在",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/task_atomic/list": {
            "get": {
                "description": "分页查询原子任务列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "原子任务管理"
                ],
                "summary": "获取原子任务列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量 (默认20, 最大100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/task_atomic/update/{id}": {
            "put": {
                "description": "根据 ID 更新原子任务信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "原子任务管理"
                ],
                "summary": "更新原子任务",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "原子任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_app_modules_task_orchestration.CreateTaskAtomicRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/todo_list/complete/{id}": {
            "post": {
                "description": "根据 ID 将 Todo 进度设为100，状态设为COMPLETED",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "待办事项"
                ],
                "summary": "完成待办事项",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "待办事项ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/todo_list/count": {
            "get": {
                "description": "统计系统中所有 Todo 的数量",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "待办事项"
                ],
                "summary": "获取待办事项总数",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/todo_list/create": {
            "post": {
                "description": "创建一个新的 Todo 项",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "待办事项"
                ],
                "summary": "创建待办事项",
                "parameters": [
                    {
                        "description": "创建参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistant_internal_app_repo.CreateTodoListParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/todo_list/delete/{id}": {
            "delete": {
                "description": "根据 ID 删除 Todo 项",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "待办事项"
                ],
                "summary": "删除待办事项",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "待办事项ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/todo_list/get/{id}": {
            "get": {
                "description": "根据 ID 获取单个 Todo 详情",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "待办事项"
                ],
                "summary": "获取待办事项详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "待办事项ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/todo_list/list": {
            "get": {
                "description": "支持分页、排序的 Todo 列表查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "待办事项"
                ],
                "summary": "获取待办事项列表",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistant_internal_app_repo.ListTodoListsParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/todo_list/priority/{id}": {
            "patch": {
                "description": "根据 ID 更新 Todo 优先级 (1-10, 越高越紧急)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "待办事项"
                ],
                "summary": "更新待办事项优先级",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "待办事项ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "优先级 1-10",
                        "name": "priority",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/todo_list/progress/{id}": {
            "patch": {
                "description": "根据 ID 更新 Todo 进度，进度100时自动设为COMPLETED",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "待办事项"
                ],
                "summary": "更新待办事项进度",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "待办事项ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "进度 0-100",
                        "name": "progress",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/todo_list/search_by_content": {
            "post": {
                "description": "根据内容关键字模糊查询 Todo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "待办事项"
                ],
                "summary": "按内容搜索待办事项",
                "parameters": [
                    {
                        "description": "搜索参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistant_internal_app_repo.SearchTodoListsByContentParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/todo_list/search_by_deadline_lt": {
            "post": {
                "description": "查询截止时间早于指定时间的 Todo 项",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "待办事项"
                ],
                "summary": "按截止时间查询待办事项",
                "parameters": [
                    {
                        "description": "搜索参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistant_internal_app_repo.SearchTodoListsByDeadlineLTParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/todo_list/search_by_title": {
            "post": {
                "description": "根据标题关键字模糊查询 Todo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "待办事项"
                ],
                "summary": "按标题搜索待办事项",
                "parameters": [
                    {
                        "description": "搜索参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistant_internal_app_repo.SearchTodoListsByTitleParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/todo_list/search_by_title_and_content": {
            "post": {
                "description": "同时根据标题和内容进行模糊搜索",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "待办事项"
                ],
                "summary": "按标题和内容搜索待办事项",
                "parameters": [
                    {
                        "description": "搜索参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistant_internal_app_repo.SearchTodoListsByTitleAndContentParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/todo_list/update/{id}": {
            "put": {
                "description": "根据 ID 更新 Todo 信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "待办事项"
                ],
                "summary": "更新待办事项",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "待办事项ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistant_internal_app_repo.UpdateTodoListByIDParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/user/count": {
            "get": {
                "description": "获取系统中所有用户的数量",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "统计用户数量",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/user/create": {
            "post": {
                "description": "创建一个新的用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "创建用户",
                "parameters": [
                    {
                        "description": "用户创建参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistant_internal_app_repo.CreateUserParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/user/delete/{id}": {
            "delete": {
                "description": "根据用户ID删除用户",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/user/get/{id}": {
            "get": {
                "description": "根据用户ID获取用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "获取用户详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/user/list": {
            "get": {
                "description": "支持分页、排序的用户列表查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "获取用户列表",
                "parameters": [
                    {
                        "description": "用户列表参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistant_internal_app_repo.ListUsersParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/user/search_by_email": {
            "post": {
                "description": "根据邮箱地址模糊搜索用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "通过邮箱搜索用户",
                "parameters": [
                    {
                        "description": "搜索参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistant_internal_app_repo.SearchUsersByEmailParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/user/search_by_user_name": {
            "post": {
                "description": "根据用户名模糊搜索用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "通过用户名搜索用户",
                "parameters": [
                    {
                        "description": "搜索参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistant_internal_app_repo.SearchUsersByUserNameParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/user/update/{id}": {
            "put": {
                "description": "根据用户ID更新用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "更新用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "用户更新参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/assistant_internal_app_repo.UpdateUserByIDParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/workflow/cancel/{id}": {
            "post": {
                "description": "取消正在运行或暂停的工作流实例",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作流执行"
                ],
                "summary": "取消工作流",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "工作流实例ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/workflow/count": {
            "get": {
                "description": "统计系统中所有工作流定义数量",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作流管理"
                ],
                "summary": "获取工作流定义总数",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/workflow/create": {
            "post": {
                "description": "创建一个新的工作流定义，支持 DAG/SEQUENTIAL/PARALLEL/CONDITIONAL 类型",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作流管理"
                ],
                "summary": "创建工作流",
                "parameters": [
                    {
                        "description": "工作流创建参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_app_modules_task_orchestration.CreateWorkflowRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/workflow/delete/{id}": {
            "delete": {
                "description": "根据 ID 删除工作流定义",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作流管理"
                ],
                "summary": "删除工作流",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "工作流ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/workflow/get/{id}": {
            "get": {
                "description": "根据 ID 获取工作流定义详细信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作流管理"
                ],
                "summary": "获取工作流详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "工作流ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "工作流不存在",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/workflow/get/{id}/edges": {
            "get": {
                "description": "根据工作流 ID 获取所有边定义",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作流管理"
                ],
                "summary": "获取工作流边列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "工作流ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/workflow/get/{id}/nodes": {
            "get": {
                "description": "根据工作流 ID 获取所有节点定义",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作流管理"
                ],
                "summary": "获取工作流节点列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "工作流ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/workflow/list": {
            "get": {
                "description": "分页查询工作流定义列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作流管理"
                ],
                "summary": "获取工作流列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量 (默认20, 最大100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/workflow/pause/{id}": {
            "post": {
                "description": "暂停正在运行的工作流实例",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作流执行"
                ],
                "summary": "暂停工作流",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "工作流实例ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/workflow/resume/{id}": {
            "post": {
                "description": "恢复已暂停的工作流实例",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作流执行"
                ],
                "summary": "恢复工作流",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "工作流实例ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/workflow/rollback/{id}": {
            "post": {
                "description": "对已完成的工作流执行回滚操作，逆序执行所有可回滚节点的回滚脚本",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作流执行"
                ],
                "summary": "回滚工作流",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "工作流实例ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/workflow/start/{id}": {
            "post": {
                "description": "根据工作流定义 ID 启动一个新的工作流实例",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作流执行"
                ],
                "summary": "启动工作流",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "工作流定义ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "启动参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_app_modules_task_orchestration.StartWorkflowRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "工作流不存在",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/workflow/update/{id}": {
            "put": {
                "description": "根据 ID 更新工作流定义信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作流管理"
                ],
                "summary": "更新工作流",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "工作流ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_app_modules_task_orchestration.CreateWorkflowRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/workflow_instance/count": {
            "get": {
                "description": "统计系统中所有工作流实例数量",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作流实例"
                ],
                "summary": "获取工作流实例总数",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/workflow_instance/get/{id}": {
            "get": {
                "description": "根据 ID 获取工作流实例详细信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作流实例"
                ],
                "summary": "获取工作流实例详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "工作流实例ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "实例不存在",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/workflow_instance/get/{id}/logs": {
            "get": {
                "description": "根据工作流实例 ID 获取完整的执行日志",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作流实例"
                ],
                "summary": "获取工作流执行日志",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "工作流实例ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/workflow_instance/list": {
            "get": {
                "description": "分页查询工作流实例列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作流实例"
                ],
                "summary": "获取工作流实例列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量 (默认20, 最大100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/assistant_pkg_response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "assistant_internal_app_repo.CreateTodoListParams": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "deadline": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "assistant_internal_app_repo.CreateUserParams": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "assistant_internal_app_repo.ListTodoListsParams": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                }
            }
        },
        "assistant_internal_app_repo.ListUsersParams": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                }
            }
        },
        "assistant_internal_app_repo.SearchTodoListsByContentParams": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                }
            }
        },
        "assistant_internal_app_repo.SearchTodoListsByDeadlineLTParams": {
            "type": "object",
            "properties": {
                "deadline": {
                    "type": "string"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                }
            }
        },
        "assistant_internal_app_repo.SearchTodoListsByTitleAndContentParams": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "assistant_internal_app_repo.SearchTodoListsByTitleParams": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "assistant_internal_app_repo.SearchUsersByEmailParams": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                }
            }
        },
        "assistant_internal_app_repo.SearchUsersByUserNameParams": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "assistant_internal_app_repo.TodoListTaskStatus": {
            "type": "string",
            "enum": [
                "PENDING",
                "IN_PROGRESS",
                "COMPLETED"
            ],
            "x-enum-varnames": [
                "TodoListTaskStatusPENDING",
                "TodoListTaskStatusINPROGRESS",
                "TodoListTaskStatusCOMPLETED"
            ]
        },
        "assistant_internal_app_repo.UpdateTodoListByIDParams": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "deadline": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "priority": {
                    "type": "integer"
                },
                "progress": {
                    "type": "integer"
                },
                "task_status": {
                    "$ref": "#/definitions/assistant_internal_app_repo.TodoListTaskStatus"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "assistant_internal_app_repo.UpdateUserByIDParams": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "assistant_pkg_response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "description": "仅成功时返回"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_app_modules_task_orchestration.CreateScheduleRequest": {
            "type": "object",
            "required": [
                "name",
                "schedule_type",
                "workflow_def_id"
            ],
            "properties": {
                "cron_expr": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "execute_at": {
                    "type": "string"
                },
                "input_params": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "interval_seconds": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "schedule_type": {
                    "type": "string"
                },
                "workflow_def_id": {
                    "type": "integer"
                }
            }
        },
        "internal_app_modules_task_orchestration.CreateTaskAtomicRequest": {
            "type": "object",
            "required": [
                "name",
                "script_content",
                "task_category"
            ],
            "properties": {
                "builtin_config": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "description": {
                    "type": "string"
                },
                "env_vars": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "http_config": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "is_rollback_supported": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "output_schema": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "parameters": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "retry_count": {
                    "type": "integer"
                },
                "retry_interval": {
                    "type": "integer"
                },
                "rollback_script_content": {
                    "type": "string"
                },
                "rollback_script_type": {
                    "type": "string"
                },
                "script_content": {
                    "type": "string"
                },
                "script_type": {
                    "type": "string"
                },
                "task_category": {
                    "type": "string"
                },
                "timeout": {
                    "type": "integer"
                },
                "working_dir": {
                    "type": "string"
                }
            }
        },
        "internal_app_modules_task_orchestration.CreateWorkflowRequest": {
            "type": "object",
            "required": [
                "graph_config",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "graph_config": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "name": {
                    "type": "string"
                },
                "notification_config": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "on_error_strategy": {
                    "type": "string"
                },
                "parameters": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "timeout": {
                    "type": "integer"
                },
                "workflow_type": {
                    "type": "string"
                }
            }
        },
        "internal_app_modules_task_orchestration.StartWorkflowRequest": {
            "type": "object",
            "properties": {
                "execution_mode": {
                    "type": "string"
                },
                "input_params": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "priority": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:1234",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Assistant API",
	Description:      "Example Swagger setup for Golang Gin.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
