// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_session.sql

package repo

import (
	"context"
	"database/sql"
)

const getOrCreateChatSession = `-- name: GetOrCreateChatSession :one
SELECT id, session_id, summary, pending_tasks, context, updated_at
FROM chat_session
WHERE session_id = ?
`

func (q *Queries) GetOrCreateChatSession(ctx context.Context, sessionID string) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateChatSession, sessionID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Summary,
		&i.PendingTasks,
		&i.Context,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertChatSession = `-- name: UpsertChatSession :execresult
INSERT INTO chat_session (session_id, summary, pending_tasks, context)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    summary = VALUES(summary),
    pending_tasks = VALUES(pending_tasks),
    context = VALUES(context)
`

type UpsertChatSessionParams struct {
	SessionID    string         `json:"session_id"`
	Summary      sql.NullString `json:"summary"`
	PendingTasks sql.NullString `json:"pending_tasks"`
	Context      sql.NullString `json:"context"`
}

func (q *Queries) UpsertChatSession(ctx context.Context, arg UpsertChatSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertChatSession,
		arg.SessionID,
		arg.Summary,
		arg.PendingTasks,
		arg.Context,
	)
}
