// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_knowledge.sql

package repo

import (
	"context"
	"database/sql"
)

const createChatKnowledge = `-- name: CreateChatKnowledge :execresult
INSERT INTO chat_knowledge (session_id, entity_id, title, content, source_messages, version, is_draft)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateChatKnowledgeParams struct {
	SessionID      string         `json:"session_id"`
	EntityID       sql.NullInt64  `json:"entity_id"`
	Title          string         `json:"title"`
	Content        string         `json:"content"`
	SourceMessages sql.NullString `json:"source_messages"`
	Version        sql.NullInt32  `json:"version"`
	IsDraft        sql.NullBool   `json:"is_draft"`
}

func (q *Queries) CreateChatKnowledge(ctx context.Context, arg CreateChatKnowledgeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createChatKnowledge,
		arg.SessionID,
		arg.EntityID,
		arg.Title,
		arg.Content,
		arg.SourceMessages,
		arg.Version,
		arg.IsDraft,
	)
}

const deleteChatKnowledgeByChatID = `-- name: DeleteChatKnowledgeByChatID :execresult
DELETE FROM chat_knowledge WHERE session_id = ?
`

func (q *Queries) DeleteChatKnowledgeByChatID(ctx context.Context, sessionID string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteChatKnowledgeByChatID, sessionID)
}

const deleteOldChatKnowledge = `-- name: DeleteOldChatKnowledge :execresult
DELETE FROM chat_knowledge WHERE created_at < ?
`

func (q *Queries) DeleteOldChatKnowledge(ctx context.Context, createdAt sql.NullTime) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteOldChatKnowledge, createdAt)
}

const getChatKnowledge = `-- name: GetChatKnowledge :many
SELECT id, session_id, entity_id, title, content, source_messages, version, is_draft, created_at, updated_at
FROM chat_knowledge
WHERE session_id = ?
ORDER BY updated_at DESC
LIMIT ? OFFSET ?
`

type GetChatKnowledgeParams struct {
	SessionID string `json:"session_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) GetChatKnowledge(ctx context.Context, arg GetChatKnowledgeParams) ([]ChatKnowledge, error) {
	rows, err := q.db.QueryContext(ctx, getChatKnowledge, arg.SessionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatKnowledge{}
	for rows.Next() {
		var i ChatKnowledge
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.EntityID,
			&i.Title,
			&i.Content,
			&i.SourceMessages,
			&i.Version,
			&i.IsDraft,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatKnowledgeByEntity = `-- name: GetChatKnowledgeByEntity :many
SELECT id, session_id, entity_id, title, content, source_messages, version, is_draft, created_at, updated_at
FROM chat_knowledge
WHERE entity_id = ?
ORDER BY version DESC
`

func (q *Queries) GetChatKnowledgeByEntity(ctx context.Context, entityID sql.NullInt64) ([]ChatKnowledge, error) {
	rows, err := q.db.QueryContext(ctx, getChatKnowledgeByEntity, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatKnowledge{}
	for rows.Next() {
		var i ChatKnowledge
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.EntityID,
			&i.Title,
			&i.Content,
			&i.SourceMessages,
			&i.Version,
			&i.IsDraft,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchChatKnowledge = `-- name: SearchChatKnowledge :many
SELECT id, session_id, entity_id, title, content, source_messages, version, is_draft, created_at, updated_at
FROM chat_knowledge
WHERE (title LIKE ? OR content LIKE ?)
ORDER BY updated_at DESC
LIMIT ?
`

type SearchChatKnowledgeParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) SearchChatKnowledge(ctx context.Context, arg SearchChatKnowledgeParams) ([]ChatKnowledge, error) {
	rows, err := q.db.QueryContext(ctx, searchChatKnowledge, arg.Title, arg.Content, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatKnowledge{}
	for rows.Next() {
		var i ChatKnowledge
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.EntityID,
			&i.Title,
			&i.Content,
			&i.SourceMessages,
			&i.Version,
			&i.IsDraft,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChatKnowledge = `-- name: UpdateChatKnowledge :execresult
UPDATE chat_knowledge
SET content = ?, source_messages = ?, version = version + 1, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateChatKnowledgeParams struct {
	Content        string         `json:"content"`
	SourceMessages sql.NullString `json:"source_messages"`
	ID             int64          `json:"id"`
}

func (q *Queries) UpdateChatKnowledge(ctx context.Context, arg UpdateChatKnowledgeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateChatKnowledge, arg.Content, arg.SourceMessages, arg.ID)
}
