// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_memory_doc.sql

package repo

import (
	"context"
	"database/sql"
)

const createChatRecall = `-- name: CreateChatRecall :execresult
INSERT INTO chat_recall (session_id, query, recalled_content, relevance_score)
VALUES (?, ?, ?, ?)
`

type CreateChatRecallParams struct {
	SessionID       string          `json:"session_id"`
	Query           string          `json:"query"`
	RecalledContent string          `json:"recalled_content"`
	RelevanceScore  sql.NullFloat64 `json:"relevance_score"`
}

func (q *Queries) CreateChatRecall(ctx context.Context, arg CreateChatRecallParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createChatRecall,
		arg.SessionID,
		arg.Query,
		arg.RecalledContent,
		arg.RelevanceScore,
	)
}

const getChatMemoryDoc = `-- name: GetChatMemoryDoc :one
SELECT id, session_id, content, version, created_at, updated_at
FROM chat_memory_doc
WHERE session_id = ?
`

func (q *Queries) GetChatMemoryDoc(ctx context.Context, sessionID string) (ChatMemoryDoc, error) {
	row := q.db.QueryRowContext(ctx, getChatMemoryDoc, sessionID)
	var i ChatMemoryDoc
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Content,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchChatRecall = `-- name: SearchChatRecall :many
SELECT id, session_id, query, recalled_content, relevance_score, created_at
FROM chat_recall
WHERE session_id = ? AND query LIKE ?
ORDER BY relevance_score DESC, created_at DESC
LIMIT ?
`

type SearchChatRecallParams struct {
	SessionID string `json:"session_id"`
	Query     string `json:"query"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) SearchChatRecall(ctx context.Context, arg SearchChatRecallParams) ([]ChatRecall, error) {
	rows, err := q.db.QueryContext(ctx, searchChatRecall, arg.SessionID, arg.Query, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatRecall{}
	for rows.Next() {
		var i ChatRecall
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Query,
			&i.RecalledContent,
			&i.RelevanceScore,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchOldChatMessagesByKeyword = `-- name: SearchOldChatMessagesByKeyword :many
SELECT id, session_id, open_id, username, role, content, message_id, created_at
FROM chat_messages
WHERE session_id = ? AND content LIKE ? AND created_at < DATE_SUB(NOW(), INTERVAL 7 DAY)
ORDER BY created_at DESC
LIMIT ?
`

type SearchOldChatMessagesByKeywordParams struct {
	SessionID string `json:"session_id"`
	Content   string `json:"content"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) SearchOldChatMessagesByKeyword(ctx context.Context, arg SearchOldChatMessagesByKeywordParams) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, searchOldChatMessagesByKeyword, arg.SessionID, arg.Content, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.OpenID,
			&i.Username,
			&i.Role,
			&i.Content,
			&i.MessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertChatMemoryDoc = `-- name: UpsertChatMemoryDoc :execresult
INSERT INTO chat_memory_doc (session_id, content, version)
VALUES (?, ?, 1)
ON DUPLICATE KEY UPDATE
    content = VALUES(content),
    version = version + 1
`

type UpsertChatMemoryDocParams struct {
	SessionID string `json:"session_id"`
	Content   string `json:"content"`
}

func (q *Queries) UpsertChatMemoryDoc(ctx context.Context, arg UpsertChatMemoryDocParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertChatMemoryDoc, arg.SessionID, arg.Content)
}
