// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_relation.sql

package repo

import (
	"context"
	"database/sql"
)

const createChatRelation = `-- name: CreateChatRelation :execresult
INSERT INTO chat_relations (session_id, from_entity_id, to_entity_id, relation_type, context)
VALUES (?, ?, ?, ?, ?)
`

type CreateChatRelationParams struct {
	SessionID    string         `json:"session_id"`
	FromEntityID int64          `json:"from_entity_id"`
	ToEntityID   int64          `json:"to_entity_id"`
	RelationType string         `json:"relation_type"`
	Context      sql.NullString `json:"context"`
}

func (q *Queries) CreateChatRelation(ctx context.Context, arg CreateChatRelationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createChatRelation,
		arg.SessionID,
		arg.FromEntityID,
		arg.ToEntityID,
		arg.RelationType,
		arg.Context,
	)
}

const deleteChatRelationsByChatID = `-- name: DeleteChatRelationsByChatID :execresult
DELETE FROM chat_relations WHERE session_id = ?
`

func (q *Queries) DeleteChatRelationsByChatID(ctx context.Context, sessionID string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteChatRelationsByChatID, sessionID)
}

const deleteOldChatRelations = `-- name: DeleteOldChatRelations :execresult
DELETE FROM chat_relations WHERE created_at < ?
`

func (q *Queries) DeleteOldChatRelations(ctx context.Context, createdAt sql.NullTime) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteOldChatRelations, createdAt)
}

const getChatRelations = `-- name: GetChatRelations :many
SELECT id, session_id, from_entity_id, to_entity_id, relation_type, context, created_at
FROM chat_relations
WHERE session_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetChatRelations(ctx context.Context, sessionID string) ([]ChatRelation, error) {
	rows, err := q.db.QueryContext(ctx, getChatRelations, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatRelation{}
	for rows.Next() {
		var i ChatRelation
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.FromEntityID,
			&i.ToEntityID,
			&i.RelationType,
			&i.Context,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityRelations = `-- name: GetEntityRelations :many
SELECT r.id, r.session_id, r.from_entity_id, r.to_entity_id, r.relation_type, r.context, r.created_at
FROM chat_relations r
WHERE r.from_entity_id = ? OR r.to_entity_id = ?
ORDER BY relation_type
`

type GetEntityRelationsParams struct {
	FromEntityID int64 `json:"from_entity_id"`
	ToEntityID   int64 `json:"to_entity_id"`
}

func (q *Queries) GetEntityRelations(ctx context.Context, arg GetEntityRelationsParams) ([]ChatRelation, error) {
	rows, err := q.db.QueryContext(ctx, getEntityRelations, arg.FromEntityID, arg.ToEntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatRelation{}
	for rows.Next() {
		var i ChatRelation
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.FromEntityID,
			&i.ToEntityID,
			&i.RelationType,
			&i.Context,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchChatRelations = `-- name: SearchChatRelations :many
SELECT r.id, r.session_id, r.from_entity_id, r.to_entity_id, r.relation_type, r.context, r.created_at
FROM chat_relations r
JOIN chat_entities e ON r.from_entity_id = e.id
WHERE e.entity_name LIKE ? OR r.relation_type LIKE ?
LIMIT ?
`

type SearchChatRelationsParams struct {
	EntityName   string `json:"entity_name"`
	RelationType string `json:"relation_type"`
	Limit        int32  `json:"limit"`
}

func (q *Queries) SearchChatRelations(ctx context.Context, arg SearchChatRelationsParams) ([]ChatRelation, error) {
	rows, err := q.db.QueryContext(ctx, searchChatRelations, arg.EntityName, arg.RelationType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatRelation{}
	for rows.Next() {
		var i ChatRelation
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.FromEntityID,
			&i.ToEntityID,
			&i.RelationType,
			&i.Context,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
