// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const countChatMessages = `-- name: CountChatMessages :one
SELECT count(*) FROM chat_messages WHERE chat_id = ?
`

func (q *Queries) CountChatMessages(ctx context.Context, chatID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChatMessages, chatID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChatMemory = `-- name: CreateChatMemory :execresult
INSERT INTO chat_memory (chat_id, keyword, summary, start_time, end_time, message_count, created_at)
VALUES (?, ?, ?, ?, ?, ?, NOW())
`

type CreateChatMemoryParams struct {
	ChatID       string        `json:"chat_id"`
	Keyword      string        `json:"keyword"`
	Summary      string        `json:"summary"`
	StartTime    time.Time     `json:"start_time"`
	EndTime      time.Time     `json:"end_time"`
	MessageCount sql.NullInt32 `json:"message_count"`
}

func (q *Queries) CreateChatMemory(ctx context.Context, arg CreateChatMemoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createChatMemory,
		arg.ChatID,
		arg.Keyword,
		arg.Summary,
		arg.StartTime,
		arg.EndTime,
		arg.MessageCount,
	)
}

const createChatMessage = `-- name: CreateChatMessage :execresult
INSERT INTO chat_messages (chat_id, open_id, username, role, content, message_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, NOW())
`

type CreateChatMessageParams struct {
	ChatID    string         `json:"chat_id"`
	OpenID    string         `json:"open_id"`
	Username  sql.NullString `json:"username"`
	Role      string         `json:"role"`
	Content   string         `json:"content"`
	MessageID sql.NullString `json:"message_id"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createChatMessage,
		arg.ChatID,
		arg.OpenID,
		arg.Username,
		arg.Role,
		arg.Content,
		arg.MessageID,
	)
}

const deleteOldChatMemories = `-- name: DeleteOldChatMemories :execresult
DELETE FROM chat_memory WHERE created_at < DATE_SUB(NOW(), INTERVAL 90 DAY)
`

func (q *Queries) DeleteOldChatMemories(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteOldChatMemories)
}

const deleteOldChatMessages = `-- name: DeleteOldChatMessages :execresult
DELETE FROM chat_messages WHERE created_at < DATE_SUB(NOW(), INTERVAL 90 DAY)
`

func (q *Queries) DeleteOldChatMessages(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteOldChatMessages)
}

const getChatMemories = `-- name: GetChatMemories :many
SELECT id, chat_id, keyword, summary, start_time, end_time, message_count, created_at
FROM chat_memory
WHERE chat_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type GetChatMemoriesParams struct {
	ChatID string `json:"chat_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) GetChatMemories(ctx context.Context, arg GetChatMemoriesParams) ([]ChatMemory, error) {
	rows, err := q.db.QueryContext(ctx, getChatMemories, arg.ChatID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMemory{}
	for rows.Next() {
		var i ChatMemory
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Keyword,
			&i.Summary,
			&i.StartTime,
			&i.EndTime,
			&i.MessageCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMessages = `-- name: GetChatMessages :many
SELECT id, chat_id, open_id, username, role, content, message_id, created_at
FROM chat_messages
WHERE chat_id = ?
ORDER BY created_at ASC
LIMIT ? OFFSET ?
`

type GetChatMessagesParams struct {
	ChatID string `json:"chat_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetChatMessages(ctx context.Context, arg GetChatMessagesParams) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, getChatMessages, arg.ChatID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.OpenID,
			&i.Username,
			&i.Role,
			&i.Content,
			&i.MessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMessagesByTimeRange = `-- name: GetChatMessagesByTimeRange :many
SELECT id, chat_id, open_id, username, role, content, message_id, created_at
FROM chat_messages
WHERE chat_id = ? AND created_at >= ? AND created_at <= ?
ORDER BY created_at ASC
`

type GetChatMessagesByTimeRangeParams struct {
	ChatID      string    `json:"chat_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

func (q *Queries) GetChatMessagesByTimeRange(ctx context.Context, arg GetChatMessagesByTimeRangeParams) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, getChatMessagesByTimeRange, arg.ChatID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.OpenID,
			&i.Username,
			&i.Role,
			&i.Content,
			&i.MessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchChatMemoriesByKeyword = `-- name: SearchChatMemoriesByKeyword :many
SELECT id, chat_id, keyword, summary, start_time, end_time, message_count, created_at
FROM chat_memory
WHERE chat_id = ? AND keyword LIKE ?
ORDER BY created_at DESC
LIMIT ?
`

type SearchChatMemoriesByKeywordParams struct {
	ChatID  string `json:"chat_id"`
	Keyword string `json:"keyword"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) SearchChatMemoriesByKeyword(ctx context.Context, arg SearchChatMemoriesByKeywordParams) ([]ChatMemory, error) {
	rows, err := q.db.QueryContext(ctx, searchChatMemoriesByKeyword, arg.ChatID, arg.Keyword, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMemory{}
	for rows.Next() {
		var i ChatMemory
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Keyword,
			&i.Summary,
			&i.StartTime,
			&i.EndTime,
			&i.MessageCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchChatMessagesByKeyword = `-- name: SearchChatMessagesByKeyword :many
SELECT id, chat_id, open_id, username, role, content, message_id, created_at
FROM chat_messages
WHERE chat_id = ? AND content LIKE ?
ORDER BY created_at DESC
LIMIT ?
`

type SearchChatMessagesByKeywordParams struct {
	ChatID  string `json:"chat_id"`
	Content string `json:"content"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) SearchChatMessagesByKeyword(ctx context.Context, arg SearchChatMessagesByKeywordParams) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, searchChatMessagesByKeyword, arg.ChatID, arg.Content, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.OpenID,
			&i.Username,
			&i.Role,
			&i.Content,
			&i.MessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
