// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_log.sql

package repo

import (
	"context"
	"database/sql"
)

const createChatLog = `-- name: CreateChatLog :execresult
INSERT INTO chat_log (session_id, action, detail)
VALUES (?, ?, ?)
`

type CreateChatLogParams struct {
	SessionID string         `json:"session_id"`
	Action    string         `json:"action"`
	Detail    sql.NullString `json:"detail"`
}

func (q *Queries) CreateChatLog(ctx context.Context, arg CreateChatLogParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createChatLog, arg.SessionID, arg.Action, arg.Detail)
}

const deleteChatLogsByChatID = `-- name: DeleteChatLogsByChatID :execresult
DELETE FROM chat_log WHERE session_id = ?
`

func (q *Queries) DeleteChatLogsByChatID(ctx context.Context, sessionID string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteChatLogsByChatID, sessionID)
}

const getChatLogs = `-- name: GetChatLogs :many
SELECT id, session_id, action, detail, created_at
FROM chat_log
WHERE session_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetChatLogsParams struct {
	SessionID string `json:"session_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) GetChatLogs(ctx context.Context, arg GetChatLogsParams) ([]ChatLog, error) {
	rows, err := q.db.QueryContext(ctx, getChatLogs, arg.SessionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatLog{}
	for rows.Next() {
		var i ChatLog
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Action,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatLogsByAction = `-- name: GetChatLogsByAction :many
SELECT id, session_id, action, detail, created_at
FROM chat_log
WHERE session_id = ? AND action = ?
ORDER BY created_at DESC
LIMIT ?
`

type GetChatLogsByActionParams struct {
	SessionID string `json:"session_id"`
	Action    string `json:"action"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) GetChatLogsByAction(ctx context.Context, arg GetChatLogsByActionParams) ([]ChatLog, error) {
	rows, err := q.db.QueryContext(ctx, getChatLogsByAction, arg.SessionID, arg.Action, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatLog{}
	for rows.Next() {
		var i ChatLog
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Action,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
