// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_entity.sql

package repo

import (
	"context"
	"database/sql"
)

const createChatEntity = `-- name: CreateChatEntity :execresult
INSERT INTO chat_entities (session_id, entity_type, entity_name, description, keywords)
VALUES (?, ?, ?, ?, ?)
`

type CreateChatEntityParams struct {
	SessionID   string         `json:"session_id"`
	EntityType  string         `json:"entity_type"`
	EntityName  string         `json:"entity_name"`
	Description sql.NullString `json:"description"`
	Keywords    sql.NullString `json:"keywords"`
}

func (q *Queries) CreateChatEntity(ctx context.Context, arg CreateChatEntityParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createChatEntity,
		arg.SessionID,
		arg.EntityType,
		arg.EntityName,
		arg.Description,
		arg.Keywords,
	)
}

const deleteChatEntitiesByChatID = `-- name: DeleteChatEntitiesByChatID :execresult
DELETE FROM chat_entities WHERE session_id = ?
`

func (q *Queries) DeleteChatEntitiesByChatID(ctx context.Context, sessionID string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteChatEntitiesByChatID, sessionID)
}

const deleteOldChatEntities = `-- name: DeleteOldChatEntities :execresult
DELETE FROM chat_entities WHERE created_at < ?
`

func (q *Queries) DeleteOldChatEntities(ctx context.Context, createdAt sql.NullTime) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteOldChatEntities, createdAt)
}

const getChatEntities = `-- name: GetChatEntities :many
SELECT id, session_id, entity_type, entity_name, description, keywords, created_at, updated_at
FROM chat_entities
WHERE session_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetChatEntitiesParams struct {
	SessionID string `json:"session_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) GetChatEntities(ctx context.Context, arg GetChatEntitiesParams) ([]ChatEntity, error) {
	rows, err := q.db.QueryContext(ctx, getChatEntities, arg.SessionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatEntity{}
	for rows.Next() {
		var i ChatEntity
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.EntityType,
			&i.EntityName,
			&i.Description,
			&i.Keywords,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatEntitiesByType = `-- name: GetChatEntitiesByType :many
SELECT id, session_id, entity_type, entity_name, description, keywords, created_at, updated_at
FROM chat_entities
WHERE session_id = ? AND entity_type = ?
ORDER BY entity_name
`

type GetChatEntitiesByTypeParams struct {
	SessionID  string `json:"session_id"`
	EntityType string `json:"entity_type"`
}

func (q *Queries) GetChatEntitiesByType(ctx context.Context, arg GetChatEntitiesByTypeParams) ([]ChatEntity, error) {
	rows, err := q.db.QueryContext(ctx, getChatEntitiesByType, arg.SessionID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatEntity{}
	for rows.Next() {
		var i ChatEntity
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.EntityType,
			&i.EntityName,
			&i.Description,
			&i.Keywords,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatEntityByID = `-- name: GetChatEntityByID :one
SELECT id, session_id, entity_type, entity_name, description, keywords, created_at, updated_at
FROM chat_entities
WHERE id = ?
`

func (q *Queries) GetChatEntityByID(ctx context.Context, id int64) (ChatEntity, error) {
	row := q.db.QueryRowContext(ctx, getChatEntityByID, id)
	var i ChatEntity
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.EntityType,
		&i.EntityName,
		&i.Description,
		&i.Keywords,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchChatEntities = `-- name: SearchChatEntities :many
SELECT id, session_id, entity_type, entity_name, description, keywords, created_at, updated_at
FROM chat_entities
WHERE entity_name LIKE ? OR keywords LIKE ?
ORDER BY created_at DESC
LIMIT ?
`

type SearchChatEntitiesParams struct {
	EntityName string         `json:"entity_name"`
	Keywords   sql.NullString `json:"keywords"`
	Limit      int32          `json:"limit"`
}

func (q *Queries) SearchChatEntities(ctx context.Context, arg SearchChatEntitiesParams) ([]ChatEntity, error) {
	rows, err := q.db.QueryContext(ctx, searchChatEntities, arg.EntityName, arg.Keywords, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatEntity{}
	for rows.Next() {
		var i ChatEntity
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.EntityType,
			&i.EntityName,
			&i.Description,
			&i.Keywords,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChatEntity = `-- name: UpdateChatEntity :execresult
UPDATE chat_entities
SET entity_name = ?, description = ?, keywords = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateChatEntityParams struct {
	EntityName  string         `json:"entity_name"`
	Description sql.NullString `json:"description"`
	Keywords    sql.NullString `json:"keywords"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateChatEntity(ctx context.Context, arg UpdateChatEntityParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateChatEntity,
		arg.EntityName,
		arg.Description,
		arg.Keywords,
		arg.ID,
	)
}
