// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type TodoListTaskStatus string

const (
	TodoListTaskStatusPENDING    TodoListTaskStatus = "PENDING"
	TodoListTaskStatusINPROGRESS TodoListTaskStatus = "IN_PROGRESS"
	TodoListTaskStatusCOMPLETED  TodoListTaskStatus = "COMPLETED"
)

func (e *TodoListTaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TodoListTaskStatus(s)
	case string:
		*e = TodoListTaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TodoListTaskStatus: %T", src)
	}
	return nil
}

type NullTodoListTaskStatus struct {
	TodoListTaskStatus TodoListTaskStatus `json:"todo_list_task_status"`
	Valid              bool               `json:"valid"` // Valid is true if TodoListTaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTodoListTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TodoListTaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TodoListTaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTodoListTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TodoListTaskStatus), nil
}

// 服务器表
type SysServer struct {
	ID          int64     `json:"id"`
	GmtCreate   time.Time `json:"gmt_create"`
	GmtModified time.Time `json:"gmt_modified"`
	IDC         string    `json:"idc"`
	SvrIP       string    `json:"svr_ip"`
	AK          string    `json:"ak"`
	SK          string    `json:"sk"`
	SvrStatus   string    `json:"svr_status"`
}

// 用户表
type SysUser struct {
	ID          int64     `json:"id"`
	GmtCreate   time.Time `json:"gmt_create"`
	GmtModified time.Time `json:"gmt_modified"`
	UserName    string    `json:"user_name"`
	Password    string    `json:"password"`
	Email       string    `json:"email"`
	IsInternal  int8      `json:"is_internal"`
}

// 代办事项表
type TodoList struct {
	ID          int64              `json:"id"`
	GmtCreate   time.Time          `json:"gmt_create"`
	GmtModified time.Time          `json:"gmt_modified"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Deadline    string             `json:"deadline"`
	Progress    int32              `json:"progress"`
	Priority    int32              `json:"priority"`
	TaskStatus  TodoListTaskStatus `json:"task_status"`
}
