// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type TaskAtomicDefRollbackScriptType string

const (
	TaskAtomicDefRollbackScriptTypeSHELL      TaskAtomicDefRollbackScriptType = "SHELL"
	TaskAtomicDefRollbackScriptTypePYTHON     TaskAtomicDefRollbackScriptType = "PYTHON"
	TaskAtomicDefRollbackScriptTypeLUA        TaskAtomicDefRollbackScriptType = "LUA"
	TaskAtomicDefRollbackScriptTypeJAVASCRIPT TaskAtomicDefRollbackScriptType = "JAVASCRIPT"
	TaskAtomicDefRollbackScriptTypeOTHER      TaskAtomicDefRollbackScriptType = "OTHER"
)

func (e *TaskAtomicDefRollbackScriptType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskAtomicDefRollbackScriptType(s)
	case string:
		*e = TaskAtomicDefRollbackScriptType(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskAtomicDefRollbackScriptType: %T", src)
	}
	return nil
}

type NullTaskAtomicDefRollbackScriptType struct {
	TaskAtomicDefRollbackScriptType TaskAtomicDefRollbackScriptType `json:"task_atomic_def_rollback_script_type"`
	Valid                           bool                            `json:"valid"` // Valid is true if TaskAtomicDefRollbackScriptType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskAtomicDefRollbackScriptType) Scan(value interface{}) error {
	if value == nil {
		ns.TaskAtomicDefRollbackScriptType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskAtomicDefRollbackScriptType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskAtomicDefRollbackScriptType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskAtomicDefRollbackScriptType), nil
}

type TaskAtomicDefScriptType string

const (
	TaskAtomicDefScriptTypeSHELL      TaskAtomicDefScriptType = "SHELL"
	TaskAtomicDefScriptTypePYTHON     TaskAtomicDefScriptType = "PYTHON"
	TaskAtomicDefScriptTypeLUA        TaskAtomicDefScriptType = "LUA"
	TaskAtomicDefScriptTypeJAVASCRIPT TaskAtomicDefScriptType = "JAVASCRIPT"
	TaskAtomicDefScriptTypeOTHER      TaskAtomicDefScriptType = "OTHER"
)

func (e *TaskAtomicDefScriptType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskAtomicDefScriptType(s)
	case string:
		*e = TaskAtomicDefScriptType(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskAtomicDefScriptType: %T", src)
	}
	return nil
}

type NullTaskAtomicDefScriptType struct {
	TaskAtomicDefScriptType TaskAtomicDefScriptType `json:"task_atomic_def_script_type"`
	Valid                   bool                    `json:"valid"` // Valid is true if TaskAtomicDefScriptType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskAtomicDefScriptType) Scan(value interface{}) error {
	if value == nil {
		ns.TaskAtomicDefScriptType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskAtomicDefScriptType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskAtomicDefScriptType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskAtomicDefScriptType), nil
}

type TaskAtomicDefStatus string

const (
	TaskAtomicDefStatusENABLED  TaskAtomicDefStatus = "ENABLED"
	TaskAtomicDefStatusDISABLED TaskAtomicDefStatus = "DISABLED"
)

func (e *TaskAtomicDefStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskAtomicDefStatus(s)
	case string:
		*e = TaskAtomicDefStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskAtomicDefStatus: %T", src)
	}
	return nil
}

type NullTaskAtomicDefStatus struct {
	TaskAtomicDefStatus TaskAtomicDefStatus `json:"task_atomic_def_status"`
	Valid               bool                `json:"valid"` // Valid is true if TaskAtomicDefStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskAtomicDefStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskAtomicDefStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskAtomicDefStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskAtomicDefStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskAtomicDefStatus), nil
}

type TaskAtomicDefTaskCategory string

const (
	TaskAtomicDefTaskCategorySCRIPT  TaskAtomicDefTaskCategory = "SCRIPT"
	TaskAtomicDefTaskCategoryHTTPAPI TaskAtomicDefTaskCategory = "HTTP_API"
	TaskAtomicDefTaskCategoryBUILTIN TaskAtomicDefTaskCategory = "BUILTIN"
)

func (e *TaskAtomicDefTaskCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskAtomicDefTaskCategory(s)
	case string:
		*e = TaskAtomicDefTaskCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskAtomicDefTaskCategory: %T", src)
	}
	return nil
}

type NullTaskAtomicDefTaskCategory struct {
	TaskAtomicDefTaskCategory TaskAtomicDefTaskCategory `json:"task_atomic_def_task_category"`
	Valid                     bool                      `json:"valid"` // Valid is true if TaskAtomicDefTaskCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskAtomicDefTaskCategory) Scan(value interface{}) error {
	if value == nil {
		ns.TaskAtomicDefTaskCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskAtomicDefTaskCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskAtomicDefTaskCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskAtomicDefTaskCategory), nil
}

type TaskAtomicInstanceStatus string

const (
	TaskAtomicInstanceStatusPENDING    TaskAtomicInstanceStatus = "PENDING"
	TaskAtomicInstanceStatusRUNNING    TaskAtomicInstanceStatus = "RUNNING"
	TaskAtomicInstanceStatusSUCCESS    TaskAtomicInstanceStatus = "SUCCESS"
	TaskAtomicInstanceStatusFAILED     TaskAtomicInstanceStatus = "FAILED"
	TaskAtomicInstanceStatusROLLEDBACK TaskAtomicInstanceStatus = "ROLLED_BACK"
)

func (e *TaskAtomicInstanceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskAtomicInstanceStatus(s)
	case string:
		*e = TaskAtomicInstanceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskAtomicInstanceStatus: %T", src)
	}
	return nil
}

type NullTaskAtomicInstanceStatus struct {
	TaskAtomicInstanceStatus TaskAtomicInstanceStatus `json:"task_atomic_instance_status"`
	Valid                    bool                     `json:"valid"` // Valid is true if TaskAtomicInstanceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskAtomicInstanceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskAtomicInstanceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskAtomicInstanceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskAtomicInstanceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskAtomicInstanceStatus), nil
}

type TaskExecutionLogLogLevel string

const (
	TaskExecutionLogLogLevelDEBUG TaskExecutionLogLogLevel = "DEBUG"
	TaskExecutionLogLogLevelINFO  TaskExecutionLogLogLevel = "INFO"
	TaskExecutionLogLogLevelWARN  TaskExecutionLogLogLevel = "WARN"
	TaskExecutionLogLogLevelERROR TaskExecutionLogLogLevel = "ERROR"
)

func (e *TaskExecutionLogLogLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskExecutionLogLogLevel(s)
	case string:
		*e = TaskExecutionLogLogLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskExecutionLogLogLevel: %T", src)
	}
	return nil
}

type NullTaskExecutionLogLogLevel struct {
	TaskExecutionLogLogLevel TaskExecutionLogLogLevel `json:"task_execution_log_log_level"`
	Valid                    bool                     `json:"valid"` // Valid is true if TaskExecutionLogLogLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskExecutionLogLogLevel) Scan(value interface{}) error {
	if value == nil {
		ns.TaskExecutionLogLogLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskExecutionLogLogLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskExecutionLogLogLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskExecutionLogLogLevel), nil
}

type TaskExecutionLogLogType string

const (
	TaskExecutionLogLogTypeEXECUTION TaskExecutionLogLogType = "EXECUTION"
	TaskExecutionLogLogTypeROLLBACK  TaskExecutionLogLogType = "ROLLBACK"
	TaskExecutionLogLogTypeRETRY     TaskExecutionLogLogType = "RETRY"
	TaskExecutionLogLogTypeSYSTEM    TaskExecutionLogLogType = "SYSTEM"
)

func (e *TaskExecutionLogLogType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskExecutionLogLogType(s)
	case string:
		*e = TaskExecutionLogLogType(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskExecutionLogLogType: %T", src)
	}
	return nil
}

type NullTaskExecutionLogLogType struct {
	TaskExecutionLogLogType TaskExecutionLogLogType `json:"task_execution_log_log_type"`
	Valid                   bool                    `json:"valid"` // Valid is true if TaskExecutionLogLogType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskExecutionLogLogType) Scan(value interface{}) error {
	if value == nil {
		ns.TaskExecutionLogLogType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskExecutionLogLogType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskExecutionLogLogType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskExecutionLogLogType), nil
}

type TaskNodeInstanceStatus string

const (
	TaskNodeInstanceStatusPENDING     TaskNodeInstanceStatus = "PENDING"
	TaskNodeInstanceStatusRUNNING     TaskNodeInstanceStatus = "RUNNING"
	TaskNodeInstanceStatusSUCCESS     TaskNodeInstanceStatus = "SUCCESS"
	TaskNodeInstanceStatusFAILED      TaskNodeInstanceStatus = "FAILED"
	TaskNodeInstanceStatusSKIPPED     TaskNodeInstanceStatus = "SKIPPED"
	TaskNodeInstanceStatusCANCELLED   TaskNodeInstanceStatus = "CANCELLED"
	TaskNodeInstanceStatusROLLINGBACK TaskNodeInstanceStatus = "ROLLING_BACK"
	TaskNodeInstanceStatusROLLEDBACK  TaskNodeInstanceStatus = "ROLLED_BACK"
)

func (e *TaskNodeInstanceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskNodeInstanceStatus(s)
	case string:
		*e = TaskNodeInstanceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskNodeInstanceStatus: %T", src)
	}
	return nil
}

type NullTaskNodeInstanceStatus struct {
	TaskNodeInstanceStatus TaskNodeInstanceStatus `json:"task_node_instance_status"`
	Valid                  bool                   `json:"valid"` // Valid is true if TaskNodeInstanceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskNodeInstanceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskNodeInstanceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskNodeInstanceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskNodeInstanceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskNodeInstanceStatus), nil
}

type TaskScheduleScheduleType string

const (
	TaskScheduleScheduleTypeCRON     TaskScheduleScheduleType = "CRON"
	TaskScheduleScheduleTypeINTERVAL TaskScheduleScheduleType = "INTERVAL"
	TaskScheduleScheduleTypeONCE     TaskScheduleScheduleType = "ONCE"
)

func (e *TaskScheduleScheduleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskScheduleScheduleType(s)
	case string:
		*e = TaskScheduleScheduleType(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskScheduleScheduleType: %T", src)
	}
	return nil
}

type NullTaskScheduleScheduleType struct {
	TaskScheduleScheduleType TaskScheduleScheduleType `json:"task_schedule_schedule_type"`
	Valid                    bool                     `json:"valid"` // Valid is true if TaskScheduleScheduleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskScheduleScheduleType) Scan(value interface{}) error {
	if value == nil {
		ns.TaskScheduleScheduleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskScheduleScheduleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskScheduleScheduleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskScheduleScheduleType), nil
}

type TaskScheduleStatus string

const (
	TaskScheduleStatusENABLED  TaskScheduleStatus = "ENABLED"
	TaskScheduleStatusDISABLED TaskScheduleStatus = "DISABLED"
	TaskScheduleStatusPAUSED   TaskScheduleStatus = "PAUSED"
)

func (e *TaskScheduleStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskScheduleStatus(s)
	case string:
		*e = TaskScheduleStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskScheduleStatus: %T", src)
	}
	return nil
}

type NullTaskScheduleStatus struct {
	TaskScheduleStatus TaskScheduleStatus `json:"task_schedule_status"`
	Valid              bool               `json:"valid"` // Valid is true if TaskScheduleStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskScheduleStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskScheduleStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskScheduleStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskScheduleStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskScheduleStatus), nil
}

type TaskWorkflowDefOnErrorStrategy string

const (
	TaskWorkflowDefOnErrorStrategySTOP     TaskWorkflowDefOnErrorStrategy = "STOP"
	TaskWorkflowDefOnErrorStrategyCONTINUE TaskWorkflowDefOnErrorStrategy = "CONTINUE"
	TaskWorkflowDefOnErrorStrategyROLLBACK TaskWorkflowDefOnErrorStrategy = "ROLLBACK"
)

func (e *TaskWorkflowDefOnErrorStrategy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskWorkflowDefOnErrorStrategy(s)
	case string:
		*e = TaskWorkflowDefOnErrorStrategy(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskWorkflowDefOnErrorStrategy: %T", src)
	}
	return nil
}

type NullTaskWorkflowDefOnErrorStrategy struct {
	TaskWorkflowDefOnErrorStrategy TaskWorkflowDefOnErrorStrategy `json:"task_workflow_def_on_error_strategy"`
	Valid                          bool                           `json:"valid"` // Valid is true if TaskWorkflowDefOnErrorStrategy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskWorkflowDefOnErrorStrategy) Scan(value interface{}) error {
	if value == nil {
		ns.TaskWorkflowDefOnErrorStrategy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskWorkflowDefOnErrorStrategy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskWorkflowDefOnErrorStrategy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskWorkflowDefOnErrorStrategy), nil
}

type TaskWorkflowDefStatus string

const (
	TaskWorkflowDefStatusDRAFT      TaskWorkflowDefStatus = "DRAFT"
	TaskWorkflowDefStatusENABLED    TaskWorkflowDefStatus = "ENABLED"
	TaskWorkflowDefStatusDISABLED   TaskWorkflowDefStatus = "DISABLED"
	TaskWorkflowDefStatusDEPRECATED TaskWorkflowDefStatus = "DEPRECATED"
)

func (e *TaskWorkflowDefStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskWorkflowDefStatus(s)
	case string:
		*e = TaskWorkflowDefStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskWorkflowDefStatus: %T", src)
	}
	return nil
}

type NullTaskWorkflowDefStatus struct {
	TaskWorkflowDefStatus TaskWorkflowDefStatus `json:"task_workflow_def_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if TaskWorkflowDefStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskWorkflowDefStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskWorkflowDefStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskWorkflowDefStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskWorkflowDefStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskWorkflowDefStatus), nil
}

type TaskWorkflowDefWorkflowType string

const (
	TaskWorkflowDefWorkflowTypeSEQUENTIAL  TaskWorkflowDefWorkflowType = "SEQUENTIAL"
	TaskWorkflowDefWorkflowTypePARALLEL    TaskWorkflowDefWorkflowType = "PARALLEL"
	TaskWorkflowDefWorkflowTypeDAG         TaskWorkflowDefWorkflowType = "DAG"
	TaskWorkflowDefWorkflowTypeCONDITIONAL TaskWorkflowDefWorkflowType = "CONDITIONAL"
)

func (e *TaskWorkflowDefWorkflowType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskWorkflowDefWorkflowType(s)
	case string:
		*e = TaskWorkflowDefWorkflowType(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskWorkflowDefWorkflowType: %T", src)
	}
	return nil
}

type NullTaskWorkflowDefWorkflowType struct {
	TaskWorkflowDefWorkflowType TaskWorkflowDefWorkflowType `json:"task_workflow_def_workflow_type"`
	Valid                       bool                        `json:"valid"` // Valid is true if TaskWorkflowDefWorkflowType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskWorkflowDefWorkflowType) Scan(value interface{}) error {
	if value == nil {
		ns.TaskWorkflowDefWorkflowType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskWorkflowDefWorkflowType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskWorkflowDefWorkflowType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskWorkflowDefWorkflowType), nil
}

type TaskWorkflowEdgeEdgeType string

const (
	TaskWorkflowEdgeEdgeTypeSEQUENTIAL     TaskWorkflowEdgeEdgeType = "SEQUENTIAL"
	TaskWorkflowEdgeEdgeTypeCONDITIONTRUE  TaskWorkflowEdgeEdgeType = "CONDITION_TRUE"
	TaskWorkflowEdgeEdgeTypeCONDITIONFALSE TaskWorkflowEdgeEdgeType = "CONDITION_FALSE"
	TaskWorkflowEdgeEdgeTypePARALLEL       TaskWorkflowEdgeEdgeType = "PARALLEL"
)

func (e *TaskWorkflowEdgeEdgeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskWorkflowEdgeEdgeType(s)
	case string:
		*e = TaskWorkflowEdgeEdgeType(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskWorkflowEdgeEdgeType: %T", src)
	}
	return nil
}

type NullTaskWorkflowEdgeEdgeType struct {
	TaskWorkflowEdgeEdgeType TaskWorkflowEdgeEdgeType `json:"task_workflow_edge_edge_type"`
	Valid                    bool                     `json:"valid"` // Valid is true if TaskWorkflowEdgeEdgeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskWorkflowEdgeEdgeType) Scan(value interface{}) error {
	if value == nil {
		ns.TaskWorkflowEdgeEdgeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskWorkflowEdgeEdgeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskWorkflowEdgeEdgeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskWorkflowEdgeEdgeType), nil
}

type TaskWorkflowInstanceExecutionMode string

const (
	TaskWorkflowInstanceExecutionModeSYNCHRONOUS  TaskWorkflowInstanceExecutionMode = "SYNCHRONOUS"
	TaskWorkflowInstanceExecutionModeASYNCHRONOUS TaskWorkflowInstanceExecutionMode = "ASYNCHRONOUS"
)

func (e *TaskWorkflowInstanceExecutionMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskWorkflowInstanceExecutionMode(s)
	case string:
		*e = TaskWorkflowInstanceExecutionMode(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskWorkflowInstanceExecutionMode: %T", src)
	}
	return nil
}

type NullTaskWorkflowInstanceExecutionMode struct {
	TaskWorkflowInstanceExecutionMode TaskWorkflowInstanceExecutionMode `json:"task_workflow_instance_execution_mode"`
	Valid                             bool                              `json:"valid"` // Valid is true if TaskWorkflowInstanceExecutionMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskWorkflowInstanceExecutionMode) Scan(value interface{}) error {
	if value == nil {
		ns.TaskWorkflowInstanceExecutionMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskWorkflowInstanceExecutionMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskWorkflowInstanceExecutionMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskWorkflowInstanceExecutionMode), nil
}

type TaskWorkflowInstanceStatus string

const (
	TaskWorkflowInstanceStatusPENDING     TaskWorkflowInstanceStatus = "PENDING"
	TaskWorkflowInstanceStatusRUNNING     TaskWorkflowInstanceStatus = "RUNNING"
	TaskWorkflowInstanceStatusPAUSED      TaskWorkflowInstanceStatus = "PAUSED"
	TaskWorkflowInstanceStatusSUCCESS     TaskWorkflowInstanceStatus = "SUCCESS"
	TaskWorkflowInstanceStatusFAILED      TaskWorkflowInstanceStatus = "FAILED"
	TaskWorkflowInstanceStatusCANCELLED   TaskWorkflowInstanceStatus = "CANCELLED"
	TaskWorkflowInstanceStatusROLLINGBACK TaskWorkflowInstanceStatus = "ROLLING_BACK"
)

func (e *TaskWorkflowInstanceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskWorkflowInstanceStatus(s)
	case string:
		*e = TaskWorkflowInstanceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskWorkflowInstanceStatus: %T", src)
	}
	return nil
}

type NullTaskWorkflowInstanceStatus struct {
	TaskWorkflowInstanceStatus TaskWorkflowInstanceStatus `json:"task_workflow_instance_status"`
	Valid                      bool                       `json:"valid"` // Valid is true if TaskWorkflowInstanceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskWorkflowInstanceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskWorkflowInstanceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskWorkflowInstanceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskWorkflowInstanceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskWorkflowInstanceStatus), nil
}

type TaskWorkflowInstanceTriggerType string

const (
	TaskWorkflowInstanceTriggerTypeMANUAL     TaskWorkflowInstanceTriggerType = "MANUAL"
	TaskWorkflowInstanceTriggerTypeSCHEDULED  TaskWorkflowInstanceTriggerType = "SCHEDULED"
	TaskWorkflowInstanceTriggerTypeAPI        TaskWorkflowInstanceTriggerType = "API"
	TaskWorkflowInstanceTriggerTypeEVENT      TaskWorkflowInstanceTriggerType = "EVENT"
	TaskWorkflowInstanceTriggerTypeDEPENDENCY TaskWorkflowInstanceTriggerType = "DEPENDENCY"
)

func (e *TaskWorkflowInstanceTriggerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskWorkflowInstanceTriggerType(s)
	case string:
		*e = TaskWorkflowInstanceTriggerType(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskWorkflowInstanceTriggerType: %T", src)
	}
	return nil
}

type NullTaskWorkflowInstanceTriggerType struct {
	TaskWorkflowInstanceTriggerType TaskWorkflowInstanceTriggerType `json:"task_workflow_instance_trigger_type"`
	Valid                           bool                            `json:"valid"` // Valid is true if TaskWorkflowInstanceTriggerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskWorkflowInstanceTriggerType) Scan(value interface{}) error {
	if value == nil {
		ns.TaskWorkflowInstanceTriggerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskWorkflowInstanceTriggerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskWorkflowInstanceTriggerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskWorkflowInstanceTriggerType), nil
}

type TaskWorkflowNodeNodeType string

const (
	TaskWorkflowNodeNodeTypeATOMIC         TaskWorkflowNodeNodeType = "ATOMIC"
	TaskWorkflowNodeNodeTypeSUBWORKFLOW    TaskWorkflowNodeNodeType = "SUB_WORKFLOW"
	TaskWorkflowNodeNodeTypeCONDITION      TaskWorkflowNodeNodeType = "CONDITION"
	TaskWorkflowNodeNodeTypePARALLELSPLIT  TaskWorkflowNodeNodeType = "PARALLEL_SPLIT"
	TaskWorkflowNodeNodeTypePARALLELJOIN   TaskWorkflowNodeNodeType = "PARALLEL_JOIN"
	TaskWorkflowNodeNodeTypeDELAY          TaskWorkflowNodeNodeType = "DELAY"
	TaskWorkflowNodeNodeTypeMANUALAPPROVAL TaskWorkflowNodeNodeType = "MANUAL_APPROVAL"
)

func (e *TaskWorkflowNodeNodeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskWorkflowNodeNodeType(s)
	case string:
		*e = TaskWorkflowNodeNodeType(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskWorkflowNodeNodeType: %T", src)
	}
	return nil
}

type NullTaskWorkflowNodeNodeType struct {
	TaskWorkflowNodeNodeType TaskWorkflowNodeNodeType `json:"task_workflow_node_node_type"`
	Valid                    bool                     `json:"valid"` // Valid is true if TaskWorkflowNodeNodeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskWorkflowNodeNodeType) Scan(value interface{}) error {
	if value == nil {
		ns.TaskWorkflowNodeNodeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskWorkflowNodeNodeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskWorkflowNodeNodeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskWorkflowNodeNodeType), nil
}

type TodoListTaskStatus string

const (
	TodoListTaskStatusPENDING    TodoListTaskStatus = "PENDING"
	TodoListTaskStatusINPROGRESS TodoListTaskStatus = "IN_PROGRESS"
	TodoListTaskStatusCOMPLETED  TodoListTaskStatus = "COMPLETED"
)

func (e *TodoListTaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TodoListTaskStatus(s)
	case string:
		*e = TodoListTaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TodoListTaskStatus: %T", src)
	}
	return nil
}

type NullTodoListTaskStatus struct {
	TodoListTaskStatus TodoListTaskStatus `json:"todo_list_task_status"`
	Valid              bool               `json:"valid"` // Valid is true if TodoListTaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTodoListTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TodoListTaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TodoListTaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTodoListTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TodoListTaskStatus), nil
}

// 服务器表
type Server struct {
	ID          int64     `json:"id"`
	GmtCreate   time.Time `json:"gmt_create"`
	GmtModified time.Time `json:"gmt_modified"`
	IDC         string    `json:"idc"`
	SvrIP       string    `json:"svr_ip"`
	AK          string    `json:"ak"`
	SK          string    `json:"sk"`
	SvrStatus   string    `json:"svr_status"`
}

// 原子任务定义表
type TaskAtomicDef struct {
	ID          int64     `json:"id"`
	GmtCreate   time.Time `json:"gmt_create"`
	GmtModified time.Time `json:"gmt_modified"`
	// 原子任务名称
	Name string `json:"name"`
	// 任务描述
	Description sql.NullString `json:"description"`
	// 任务类别
	TaskCategory TaskAtomicDefTaskCategory `json:"task_category"`
	// 脚本类型
	ScriptType NullTaskAtomicDefScriptType `json:"script_type"`
	// 脚本内容
	ScriptContent string `json:"script_content"`
	// 回滚脚本类型
	RollbackScriptType NullTaskAtomicDefRollbackScriptType `json:"rollback_script_type"`
	// 回滚脚本内容
	RollbackScriptContent sql.NullString `json:"rollback_script_content"`
	// HTTP API 配置
	HttpConfig json.RawMessage `json:"http_config"`
	// 内置任务配置
	BuiltinConfig json.RawMessage `json:"builtin_config"`
	// 超时时间(秒)
	Timeout sql.NullInt32 `json:"timeout"`
	// 重试次数
	RetryCount sql.NullInt32 `json:"retry_count"`
	// 重试间隔(秒)
	RetryInterval sql.NullInt32 `json:"retry_interval"`
	// 是否支持回滚
	IsRollbackSupported sql.NullBool `json:"is_rollback_supported"`
	// 参数定义
	Parameters json.RawMessage `json:"parameters"`
	// 输出 schema
	OutputSchema json.RawMessage `json:"output_schema"`
	// 环境变量
	EnvVars json.RawMessage `json:"env_vars"`
	// 工作目录
	WorkingDir sql.NullString `json:"working_dir"`
	// 状态
	Status NullTaskAtomicDefStatus `json:"status"`
}

// 原子任务实例表
type TaskAtomicInstance struct {
	ID          int64     `json:"id"`
	GmtCreate   time.Time `json:"gmt_create"`
	GmtModified time.Time `json:"gmt_modified"`
	// 关联节点实例ID
	NodeInstanceID int64 `json:"node_instance_id"`
	// 关联原子任务定义ID
	TaskAtomicDefID int64 `json:"task_atomic_def_id"`
	// 执行状态
	Status TaskAtomicInstanceStatus `json:"status"`
	// 输入参数
	InputParams json.RawMessage `json:"input_params"`
	// 输出结果
	OutputResult json.RawMessage `json:"output_result"`
	// 执行日志
	ExecutionLog sql.NullString `json:"execution_log"`
	// 错误日志
	ErrorLog sql.NullString `json:"error_log"`
	// 回滚日志
	RollbackLog sql.NullString `json:"rollback_log"`
	// 回滚结果
	RollbackResult json.RawMessage `json:"rollback_result"`
	// 超时时间
	Timeout sql.NullInt32 `json:"timeout"`
	// 开始时间
	GmtStart sql.NullTime `json:"gmt_start"`
	// 结束时间
	GmtEnd sql.NullTime `json:"gmt_end"`
	// 执行耗时(毫秒)
	DurationMs sql.NullInt32 `json:"duration_ms"`
	// 执行 worker ID
	WorkerID sql.NullString `json:"worker_id"`
}

// 任务执行日志表
type TaskExecutionLog struct {
	ID        int64     `json:"id"`
	GmtCreate time.Time `json:"gmt_create"`
	// 关联工作流实例ID
	WorkflowInstanceID int64 `json:"workflow_instance_id"`
	// 关联节点实例ID
	NodeInstanceID sql.NullInt64 `json:"node_instance_id"`
	// 关联原子任务实例ID
	TaskAtomicInstanceID sql.NullInt64 `json:"task_atomic_instance_id"`
	// 日志级别
	LogLevel TaskExecutionLogLogLevel `json:"log_level"`
	// 日志类型
	LogType TaskExecutionLogLogType `json:"log_type"`
	// 日志内容
	Message string `json:"message"`
	// 上下文信息
	Context json.RawMessage `json:"context"`
}

// 任务节点实例表
type TaskNodeInstance struct {
	ID          int64     `json:"id"`
	GmtCreate   time.Time `json:"gmt_create"`
	GmtModified time.Time `json:"gmt_modified"`
	// 关联工作流实例ID
	WorkflowInstanceID int64 `json:"workflow_instance_id"`
	// 关联节点定义ID
	NodeDefID int64 `json:"node_def_id"`
	// 节点标识
	NodeID string `json:"node_id"`
	// 执行状态
	Status TaskNodeInstanceStatus `json:"status"`
	// 状态原因
	StatusReason sql.NullString `json:"status_reason"`
	// 输入参数
	InputParams json.RawMessage `json:"input_params"`
	// 输出结果
	OutputResult json.RawMessage `json:"output_result"`
	// 执行日志
	ExecutionLog sql.NullString `json:"execution_log"`
	// 错误日志
	ErrorLog sql.NullString `json:"error_log"`
	// 已重试次数
	RetryCount sql.NullInt32 `json:"retry_count"`
	// 开始时间
	GmtStart sql.NullTime `json:"gmt_start"`
	// 结束时间
	GmtEnd sql.NullTime `json:"gmt_end"`
	// 执行耗时(毫秒)
	DurationMs sql.NullInt32 `json:"duration_ms"`
	// 执行 worker ID
	WorkerID sql.NullString `json:"worker_id"`
}

// 任务调度表
type TaskSchedule struct {
	ID          int64     `json:"id"`
	GmtCreate   time.Time `json:"gmt_create"`
	GmtModified time.Time `json:"gmt_modified"`
	// 调度名称
	Name string `json:"name"`
	// 调度描述
	Description sql.NullString `json:"description"`
	// 关联工作流定义ID
	WorkflowDefID int64 `json:"workflow_def_id"`
	// 调度类型
	ScheduleType TaskScheduleScheduleType `json:"schedule_type"`
	// Cron 表达式
	CronExpr sql.NullString `json:"cron_expr"`
	// 间隔秒数
	IntervalSeconds sql.NullInt32 `json:"interval_seconds"`
	// 单次执行时间
	ExecuteAt sql.NullTime `json:"execute_at"`
	// 默认输入参数
	InputParams json.RawMessage `json:"input_params"`
	// 状态
	Status NullTaskScheduleStatus `json:"status"`
	// 最近执行的实例ID
	LastExecuteID sql.NullInt64 `json:"last_execute_id"`
	// 下次执行时间
	NextExecuteAt sql.NullTime `json:"next_execute_at"`
	// 创建人
	CreatedBy sql.NullString `json:"created_by"`
}

// 任务工作流定义表
type TaskWorkflowDef struct {
	ID          int64     `json:"id"`
	GmtCreate   time.Time `json:"gmt_create"`
	GmtModified time.Time `json:"gmt_modified"`
	// 工作流名称
	Name string `json:"name"`
	// 工作流描述
	Description sql.NullString `json:"description"`
	// 版本号
	Version sql.NullInt32 `json:"version"`
	// 工作流类型
	WorkflowType TaskWorkflowDefWorkflowType `json:"workflow_type"`
	// DAG 图配置
	GraphConfig json.RawMessage `json:"graph_config"`
	// 输入参数定义
	Parameters json.RawMessage `json:"parameters"`
	// 整体超时时间(秒)
	Timeout sql.NullInt32 `json:"timeout"`
	// 错误处理策略
	OnErrorStrategy NullTaskWorkflowDefOnErrorStrategy `json:"on_error_strategy"`
	// 通知配置
	NotificationConfig json.RawMessage `json:"notification_config"`
	// 状态
	Status NullTaskWorkflowDefStatus `json:"status"`
	// 创建人
	CreatedBy sql.NullString `json:"created_by"`
}

// 工作流边定义表
type TaskWorkflowEdge struct {
	ID          int64     `json:"id"`
	GmtCreate   time.Time `json:"gmt_create"`
	GmtModified time.Time `json:"gmt_modified"`
	// 关联工作流定义ID
	WorkflowID int64 `json:"workflow_id"`
	// 源节点ID
	FromNodeID string `json:"from_node_id"`
	// 目标节点ID
	ToNodeID string `json:"to_node_id"`
	// 边类型
	EdgeType NullTaskWorkflowEdgeEdgeType `json:"edge_type"`
	// 条件表达式
	ConditionExpr sql.NullString `json:"condition_expr"`
}

// 工作流实例表
type TaskWorkflowInstance struct {
	ID          int64     `json:"id"`
	GmtCreate   time.Time `json:"gmt_create"`
	GmtModified time.Time `json:"gmt_modified"`
	// 关联工作流定义ID
	WorkflowDefID int64 `json:"workflow_def_id"`
	// 工作流定义版本
	WorkflowDefVersion sql.NullInt32 `json:"workflow_def_version"`
	// 触发类型
	TriggerType TaskWorkflowInstanceTriggerType `json:"trigger_type"`
	// 触发源ID
	TriggerID sql.NullString `json:"trigger_id"`
	// 输入参数
	InputParams json.RawMessage `json:"input_params"`
	// 执行状态
	Status TaskWorkflowInstanceStatus `json:"status"`
	// 状态原因
	StatusReason sql.NullString `json:"status_reason"`
	// 当前执行节点
	CurrentNodeID sql.NullString `json:"current_node_id"`
	// 执行模式
	ExecutionMode NullTaskWorkflowInstanceExecutionMode `json:"execution_mode"`
	// 调度优先级
	Priority sql.NullInt32 `json:"priority"`
	// 开始时间
	GmtStart sql.NullTime `json:"gmt_start"`
	// 结束时间
	GmtEnd sql.NullTime `json:"gmt_end"`
	// 暂停时间
	GmtPaused sql.NullTime `json:"gmt_paused"`
	// 总节点数
	TotalNodes sql.NullInt32 `json:"total_nodes"`
	// 已完成节点数
	CompletedNodes sql.NullInt32 `json:"completed_nodes"`
	// 失败节点数
	FailedNodes sql.NullInt32 `json:"failed_nodes"`
	// 执行结果汇总
	ResultSummary json.RawMessage `json:"result_summary"`
	// 错误信息
	ErrorInfo json.RawMessage `json:"error_info"`
	// 创建人
	CreatedBy sql.NullString `json:"created_by"`
}

// 工作流节点定义表
type TaskWorkflowNode struct {
	ID          int64     `json:"id"`
	GmtCreate   time.Time `json:"gmt_create"`
	GmtModified time.Time `json:"gmt_modified"`
	// 关联工作流定义ID
	WorkflowID int64 `json:"workflow_id"`
	// 节点唯一标识
	NodeID string `json:"node_id"`
	// 节点类型
	NodeType TaskWorkflowNodeNodeType `json:"node_type"`
	// 节点显示名称
	DisplayName string `json:"display_name"`
	// 引用的原子任务ID
	TaskAtomicDefID sql.NullInt64 `json:"task_atomic_def_id"`
	// 引用的子工作流ID
	SubWorkflowID sql.NullInt64 `json:"sub_workflow_id"`
	// 条件表达式
	ConditionExpr sql.NullString `json:"condition_expr"`
	// 节点额外配置
	NodeConfig json.RawMessage `json:"node_config"`
	// 节点级重试策略
	RetryPolicy json.RawMessage `json:"retry_policy"`
	// 节点超时时间
	Timeout sql.NullInt32 `json:"timeout"`
	// 执行顺序
	Ord sql.NullInt32 `json:"ord"`
}

// 代办事项表
type TodoList struct {
	ID          int64     `json:"id"`
	GmtCreate   time.Time `json:"gmt_create"`
	GmtModified time.Time `json:"gmt_modified"`
	Title       string    `json:"title"`
	Content     string    `json:"content"`
	Deadline    string    `json:"deadline"`
	// 任务完成进度 0-100
	Progress int32 `json:"progress"`
	// 任务优先级 1-10, 越高越紧急
	Priority int32 `json:"priority"`
	// 任务状态
	TaskStatus TodoListTaskStatus `json:"task_status"`
}

// 用户表
type User struct {
	ID          int64     `json:"id"`
	GmtCreate   time.Time `json:"gmt_create"`
	GmtModified time.Time `json:"gmt_modified"`
	UserName    string    `json:"user_name"`
	Password    string    `json:"password"`
	Email       string    `json:"email"`
}
