// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
)

const countTaskSchedules = `-- name: CountTaskSchedules :one
SELECT COUNT(*) AS cnt FROM task_schedule WHERE status != 'DISABLED'
`

func (q *Queries) CountTaskSchedules(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTaskSchedules)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const createTaskSchedule = `-- name: CreateTaskSchedule :execresult
INSERT INTO task_schedule (
  name,
  description,
  workflow_def_id,
  schedule_type,
  cron_expr,
  interval_seconds,
  execute_at,
  input_params,
  status,
  created_by
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskScheduleParams struct {
	Name            string                   `json:"name"`
	Description     sql.NullString           `json:"description"`
	WorkflowDefID   int64                    `json:"workflow_def_id"`
	ScheduleType    TaskScheduleScheduleType `json:"schedule_type"`
	CronExpr        sql.NullString           `json:"cron_expr"`
	IntervalSeconds sql.NullInt32            `json:"interval_seconds"`
	ExecuteAt       sql.NullTime             `json:"execute_at"`
	InputParams     json.RawMessage          `json:"input_params"`
	Status          NullTaskScheduleStatus   `json:"status"`
	CreatedBy       sql.NullString           `json:"created_by"`
}

func (q *Queries) CreateTaskSchedule(ctx context.Context, arg CreateTaskScheduleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTaskSchedule,
		arg.Name,
		arg.Description,
		arg.WorkflowDefID,
		arg.ScheduleType,
		arg.CronExpr,
		arg.IntervalSeconds,
		arg.ExecuteAt,
		arg.InputParams,
		arg.Status,
		arg.CreatedBy,
	)
}

const deleteTaskScheduleByID = `-- name: DeleteTaskScheduleByID :execresult
DELETE FROM task_schedule WHERE id = ? LIMIT 1
`

func (q *Queries) DeleteTaskScheduleByID(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTaskScheduleByID, id)
}

const getTaskScheduleByID = `-- name: GetTaskScheduleByID :one
SELECT id, gmt_create, gmt_modified, name, description, workflow_def_id, schedule_type, cron_expr, interval_seconds, execute_at, input_params, status, last_execute_id, next_execute_at, created_by FROM task_schedule WHERE id = ?
`

func (q *Queries) GetTaskScheduleByID(ctx context.Context, id int64) (TaskSchedule, error) {
	row := q.db.QueryRowContext(ctx, getTaskScheduleByID, id)
	var i TaskSchedule
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Name,
		&i.Description,
		&i.WorkflowDefID,
		&i.ScheduleType,
		&i.CronExpr,
		&i.IntervalSeconds,
		&i.ExecuteAt,
		&i.InputParams,
		&i.Status,
		&i.LastExecuteID,
		&i.NextExecuteAt,
		&i.CreatedBy,
	)
	return i, err
}

const listDueTaskSchedules = `-- name: ListDueTaskSchedules :many
SELECT id, gmt_create, gmt_modified, name, description, workflow_def_id, schedule_type, cron_expr, interval_seconds, execute_at, input_params, status, last_execute_id, next_execute_at, created_by FROM task_schedule
WHERE status = 'ENABLED' AND next_execute_at <= NOW()
ORDER BY next_execute_at ASC
LIMIT ?
`

func (q *Queries) ListDueTaskSchedules(ctx context.Context, limit int32) ([]TaskSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listDueTaskSchedules, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskSchedule{}
	for rows.Next() {
		var i TaskSchedule
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Name,
			&i.Description,
			&i.WorkflowDefID,
			&i.ScheduleType,
			&i.CronExpr,
			&i.IntervalSeconds,
			&i.ExecuteAt,
			&i.InputParams,
			&i.Status,
			&i.LastExecuteID,
			&i.NextExecuteAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskSchedules = `-- name: ListTaskSchedules :many
SELECT id, gmt_create, gmt_modified, name, description, workflow_def_id, schedule_type, cron_expr, interval_seconds, execute_at, input_params, status, last_execute_id, next_execute_at, created_by FROM task_schedule
WHERE status != 'DISABLED'
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListTaskSchedulesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTaskSchedules(ctx context.Context, arg ListTaskSchedulesParams) ([]TaskSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listTaskSchedules, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskSchedule{}
	for rows.Next() {
		var i TaskSchedule
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Name,
			&i.Description,
			&i.WorkflowDefID,
			&i.ScheduleType,
			&i.CronExpr,
			&i.IntervalSeconds,
			&i.ExecuteAt,
			&i.InputParams,
			&i.Status,
			&i.LastExecuteID,
			&i.NextExecuteAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskScheduleByID = `-- name: UpdateTaskScheduleByID :execresult
UPDATE task_schedule SET
  name = ?,
  description = ?,
  schedule_type = ?,
  cron_expr = ?,
  interval_seconds = ?,
  execute_at = ?,
  input_params = ?,
  status = ?,
  next_execute_at = ?
WHERE id = ?
`

type UpdateTaskScheduleByIDParams struct {
	Name            string                   `json:"name"`
	Description     sql.NullString           `json:"description"`
	ScheduleType    TaskScheduleScheduleType `json:"schedule_type"`
	CronExpr        sql.NullString           `json:"cron_expr"`
	IntervalSeconds sql.NullInt32            `json:"interval_seconds"`
	ExecuteAt       sql.NullTime             `json:"execute_at"`
	InputParams     json.RawMessage          `json:"input_params"`
	Status          NullTaskScheduleStatus   `json:"status"`
	NextExecuteAt   sql.NullTime             `json:"next_execute_at"`
	ID              int64                    `json:"id"`
}

func (q *Queries) UpdateTaskScheduleByID(ctx context.Context, arg UpdateTaskScheduleByIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTaskScheduleByID,
		arg.Name,
		arg.Description,
		arg.ScheduleType,
		arg.CronExpr,
		arg.IntervalSeconds,
		arg.ExecuteAt,
		arg.InputParams,
		arg.Status,
		arg.NextExecuteAt,
		arg.ID,
	)
}

const updateTaskScheduleLastExecute = `-- name: UpdateTaskScheduleLastExecute :execresult
UPDATE task_schedule SET
  last_execute_id = ?,
  next_execute_at = ?
WHERE id = ?
`

type UpdateTaskScheduleLastExecuteParams struct {
	LastExecuteID sql.NullInt64 `json:"last_execute_id"`
	NextExecuteAt sql.NullTime  `json:"next_execute_at"`
	ID            int64         `json:"id"`
}

func (q *Queries) UpdateTaskScheduleLastExecute(ctx context.Context, arg UpdateTaskScheduleLastExecuteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTaskScheduleLastExecute, arg.LastExecuteID, arg.NextExecuteAt, arg.ID)
}
