// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: server.sql

package repo

import (
	"context"
	"database/sql"
)

const countServer = `-- name: CountServer :one
SELECT count(*) ct FROM server
`

func (q *Queries) CountServer(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countServer)
	var ct int64
	err := row.Scan(&ct)
	return ct, err
}

const createServer = `-- name: CreateServer :execresult
INSERT INTO server (idc, svr_ip, ak, sk)
VALUES (?, ?, ?, ?)
`

type CreateServerParams struct {
	IDC   string `json:"idc"`
	SvrIP string `json:"svr_ip"`
	AK    string `json:"ak"`
	SK    string `json:"sk"`
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createServer,
		arg.IDC,
		arg.SvrIP,
		arg.AK,
		arg.SK,
	)
}

const deleteServer = `-- name: DeleteServer :execresult
DELETE FROM server
WHERE id = ?
LIMIT 1
`

func (q *Queries) DeleteServer(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteServer, id)
}

const getServerByID = `-- name: GetServerByID :one
SELECT
  id,
  gmt_create,
  gmt_modified,
  idc,
  svr_ip,
  ak,
  sk,
  svr_status
FROM server
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetServerByID(ctx context.Context, id int64) (Server, error) {
	row := q.db.QueryRowContext(ctx, getServerByID, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.IDC,
		&i.SvrIP,
		&i.AK,
		&i.SK,
		&i.SvrStatus,
	)
	return i, err
}

const listServers = `-- name: ListServers :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  idc,
  svr_ip,
  ak,
  sk,
  svr_status
FROM server
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListServersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListServers(ctx context.Context, arg ListServersParams) ([]Server, error) {
	rows, err := q.db.QueryContext(ctx, listServers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.IDC,
			&i.SvrIP,
			&i.AK,
			&i.SK,
			&i.SvrStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchServersByIDC = `-- name: SearchServersByIDC :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  idc,
  svr_ip,
  ak,
  sk,
  svr_status
FROM server
WHERE idc = ?
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type SearchServersByIDCParams struct {
	IDC    string `json:"idc"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SearchServersByIDC(ctx context.Context, arg SearchServersByIDCParams) ([]Server, error) {
	rows, err := q.db.QueryContext(ctx, searchServersByIDC, arg.IDC, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.IDC,
			&i.SvrIP,
			&i.AK,
			&i.SK,
			&i.SvrStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchServersByIDCAndSvrIP = `-- name: SearchServersByIDCAndSvrIP :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  idc,
  svr_ip,
  ak,
  sk,
  svr_status
FROM server
WHERE idc like ?
  AND svr_ip like ?
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type SearchServersByIDCAndSvrIPParams struct {
	IDC    string `json:"idc"`
	SvrIP  string `json:"svr_ip"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SearchServersByIDCAndSvrIP(ctx context.Context, arg SearchServersByIDCAndSvrIPParams) ([]Server, error) {
	rows, err := q.db.QueryContext(ctx, searchServersByIDCAndSvrIP,
		arg.IDC,
		arg.SvrIP,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.IDC,
			&i.SvrIP,
			&i.AK,
			&i.SK,
			&i.SvrStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchServersBySvrIP = `-- name: SearchServersBySvrIP :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  idc,
  svr_ip,
  ak,
  sk,
  svr_status
FROM server
WHERE svr_ip like ?
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type SearchServersBySvrIPParams struct {
	SvrIP  string `json:"svr_ip"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SearchServersBySvrIP(ctx context.Context, arg SearchServersBySvrIPParams) ([]Server, error) {
	rows, err := q.db.QueryContext(ctx, searchServersBySvrIP, arg.SvrIP, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.IDC,
			&i.SvrIP,
			&i.AK,
			&i.SK,
			&i.SvrStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServer = `-- name: UpdateServer :execresult
UPDATE server
SET  idc = ?,
  svr_ip = ?,
      ak = ?,
      sk = ?
WHERE id = ?
LIMIT 1
`

type UpdateServerParams struct {
	IDC   string `json:"idc"`
	SvrIP string `json:"svr_ip"`
	AK    string `json:"ak"`
	SK    string `json:"sk"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateServer(ctx context.Context, arg UpdateServerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateServer,
		arg.IDC,
		arg.SvrIP,
		arg.AK,
		arg.SK,
		arg.ID,
	)
}

const updateServerSvrStatus = `-- name: UpdateServerSvrStatus :execresult
UPDATE server
SET svr_status = ?
WHERE id = ?
LIMIT 1
`

type UpdateServerSvrStatusParams struct {
	SvrStatus string `json:"svr_status"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateServerSvrStatus(ctx context.Context, arg UpdateServerSvrStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateServerSvrStatus, arg.SvrStatus, arg.ID)
}
