// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sys_user.sql

package repo

import (
	"context"
	"database/sql"
)

const countSysUsers = `-- name: CountSysUsers :one
SELECT count(*) ct FROM sys_user
`

func (q *Queries) CountSysUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSysUsers)
	var ct int64
	err := row.Scan(&ct)
	return ct, err
}

const createSysUser = `-- name: CreateSysUser :execresult
INSERT INTO sys_user (user_name, password, email)
VALUES (?, ?, ?)
`

type CreateSysUserParams struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

func (q *Queries) CreateSysUser(ctx context.Context, arg CreateSysUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSysUser, arg.UserName, arg.Password, arg.Email)
}

const deleteSysUserByID = `-- name: DeleteSysUserByID :execresult
DELETE FROM sys_user
WHERE id = ?
LIMIT 1
`

func (q *Queries) DeleteSysUserByID(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteSysUserByID, id)
}

const getSysUserByID = `-- name: GetSysUserByID :one
SELECT
  id,
  gmt_create,
  gmt_modified,
  user_name,
  password,
  email
FROM sys_user
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetSysUserByID(ctx context.Context, id int64) (SysUser, error) {
	row := q.db.QueryRowContext(ctx, getSysUserByID, id)
	var i SysUser
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.UserName,
		&i.Password,
		&i.Email,
	)
	return i, err
}

const listSysUsers = `-- name: ListSysUsers :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  user_name,
  password,
  email
FROM sys_user
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListSysUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSysUsers(ctx context.Context, arg ListSysUsersParams) ([]SysUser, error) {
	rows, err := q.db.QueryContext(ctx, listSysUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SysUser{}
	for rows.Next() {
		var i SysUser
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.UserName,
			&i.Password,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSysUsersByEmail = `-- name: SearchSysUsersByEmail :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  user_name,
  password,
  email
FROM sys_user
WHERE email like ?
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type SearchSysUsersByEmailParams struct {
	Email  string `json:"email"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SearchSysUsersByEmail(ctx context.Context, arg SearchSysUsersByEmailParams) ([]SysUser, error) {
	rows, err := q.db.QueryContext(ctx, searchSysUsersByEmail, arg.Email, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SysUser{}
	for rows.Next() {
		var i SysUser
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.UserName,
			&i.Password,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSysUsersByUserName = `-- name: SearchSysUsersByUserName :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  user_name,
  password,
  email
FROM sys_user
WHERE user_name like ?
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type SearchSysUsersByUserNameParams struct {
	UserName string `json:"user_name"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) SearchSysUsersByUserName(ctx context.Context, arg SearchSysUsersByUserNameParams) ([]SysUser, error) {
	rows, err := q.db.QueryContext(ctx, searchSysUsersByUserName, arg.UserName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SysUser{}
	for rows.Next() {
		var i SysUser
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.UserName,
			&i.Password,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSysUserByID = `-- name: UpdateSysUserByID :execresult
UPDATE sys_user
SET user_name = ?,
     password = ?,
        email = ?
WHERE id = ?
LIMIT 1
`

type UpdateSysUserByIDParams struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
	Email    string `json:"email"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateSysUserByID(ctx context.Context, arg UpdateSysUserByIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSysUserByID,
		arg.UserName,
		arg.Password,
		arg.Email,
		arg.ID,
	)
}
