// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sys_distributed_lock.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const cleanExpiredLocks = `-- name: CleanExpiredLocks :execresult
DELETE FROM sys_distributed_lock
WHERE is_active = 0 OR expire_time < DATE_SUB(NOW(), INTERVAL 5 MINUTE)
`

// 清理过期锁（保留5分钟缓冲期）
func (q *Queries) CleanExpiredLocks(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, cleanExpiredLocks)
}

const countActiveLocks = `-- name: CountActiveLocks :one
SELECT count(*) ct
FROM sys_distributed_lock
WHERE is_active = 1 AND expire_time > NOW()
`

// 统计活跃锁数量
func (q *Queries) CountActiveLocks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveLocks)
	var ct int64
	err := row.Scan(&ct)
	return ct, err
}

const forceReleaseLock = `-- name: ForceReleaseLock :execresult
UPDATE sys_distributed_lock
SET is_active = 0
WHERE lock_key = ?
`

// 强制释放锁（不需要 holder，用于管理员或异常清理）
func (q *Queries) ForceReleaseLock(ctx context.Context, lockKey string) (sql.Result, error) {
	return q.db.ExecContext(ctx, forceReleaseLock, lockKey)
}

const getLockInfo = `-- name: GetLockInfo :one
SELECT
    id,
    gmt_create,
    gmt_modified,
    lock_key,
    lock_holder,
    lock_ttl,
    expire_time,
    is_active
FROM sys_distributed_lock
WHERE lock_key = ? AND is_active = 1
LIMIT 1
`

// 获取锁信息（仅活跃锁）
func (q *Queries) GetLockInfo(ctx context.Context, lockKey string) (SysDistributedLock, error) {
	row := q.db.QueryRowContext(ctx, getLockInfo, lockKey)
	var i SysDistributedLock
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.LockKey,
		&i.LockHolder,
		&i.LockTtl,
		&i.ExpireTime,
		&i.IsActive,
	)
	return i, err
}

const getLockInfoAll = `-- name: GetLockInfoAll :one
SELECT
    id,
    gmt_create,
    gmt_modified,
    lock_key,
    lock_holder,
    lock_ttl,
    expire_time,
    is_active
FROM sys_distributed_lock
WHERE lock_key = ?
LIMIT 1
`

// 获取锁信息（包含所有状态）
func (q *Queries) GetLockInfoAll(ctx context.Context, lockKey string) (SysDistributedLock, error) {
	row := q.db.QueryRowContext(ctx, getLockInfoAll, lockKey)
	var i SysDistributedLock
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.LockKey,
		&i.LockHolder,
		&i.LockTtl,
		&i.ExpireTime,
		&i.IsActive,
	)
	return i, err
}

const isLockHeld = `-- name: IsLockHeld :one
SELECT 1
FROM sys_distributed_lock
WHERE lock_key = ? AND is_active = 1 AND expire_time > NOW()
LIMIT 1
`

// 检查锁是否被持有（未过期）
func (q *Queries) IsLockHeld(ctx context.Context, lockKey string) (int32, error) {
	row := q.db.QueryRowContext(ctx, isLockHeld, lockKey)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listActiveLocks = `-- name: ListActiveLocks :many
SELECT
    id,
    gmt_create,
    gmt_modified,
    lock_key,
    lock_holder,
    lock_ttl,
    expire_time,
    is_active
FROM sys_distributed_lock
WHERE is_active = 1 AND expire_time > NOW()
ORDER BY expire_time ASC
LIMIT ? OFFSET ?
`

type ListActiveLocksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// 分页查询活跃锁
func (q *Queries) ListActiveLocks(ctx context.Context, arg ListActiveLocksParams) ([]SysDistributedLock, error) {
	rows, err := q.db.QueryContext(ctx, listActiveLocks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SysDistributedLock{}
	for rows.Next() {
		var i SysDistributedLock
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.LockKey,
			&i.LockHolder,
			&i.LockTtl,
			&i.ExpireTime,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseLock = `-- name: ReleaseLock :execresult
UPDATE sys_distributed_lock
SET is_active = 0
WHERE lock_key = ? AND lock_holder = ? AND is_active = 1
`

type ReleaseLockParams struct {
	LockKey    string `json:"lock_key"`
	LockHolder string `json:"lock_holder"`
}

// 释放锁（必须验证 lock_holder）
func (q *Queries) ReleaseLock(ctx context.Context, arg ReleaseLockParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, releaseLock, arg.LockKey, arg.LockHolder)
}

const renewLock = `-- name: RenewLock :execresult
UPDATE sys_distributed_lock
SET expire_time = ?
WHERE lock_key = ? AND lock_holder = ? AND is_active = 1 AND expire_time > NOW()
`

type RenewLockParams struct {
	ExpireTime time.Time `json:"expire_time"`
	LockKey    string    `json:"lock_key"`
	LockHolder string    `json:"lock_holder"`
}

// 续期锁（必须验证 lock_holder）
func (q *Queries) RenewLock(ctx context.Context, arg RenewLockParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, renewLock, arg.ExpireTime, arg.LockKey, arg.LockHolder)
}

const tryAcquireLock = `-- name: TryAcquireLock :execresult
INSERT INTO sys_distributed_lock (lock_key, lock_holder, lock_ttl, expire_time)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    lock_holder = IF(is_active = 1 AND expire_time > NOW(), lock_holder, VALUES(lock_holder)),
    lock_ttl = IF(is_active = 1 AND expire_time > NOW(), lock_ttl, VALUES(lock_ttl)),
    expire_time = IF(is_active = 1 AND expire_time > NOW(), expire_time, VALUES(expire_time)),
    is_active = IF(is_active = 1 AND expire_time > NOW(), is_active, 1)
`

type TryAcquireLockParams struct {
	LockKey    string    `json:"lock_key"`
	LockHolder string    `json:"lock_holder"`
	LockTtl    int32     `json:"lock_ttl"`
	ExpireTime time.Time `json:"expire_time"`
}

// 尝试获取锁（原子操作，锁存在且未过期则获取失败）
// 使用事务 + SELECT FOR UPDATE 确保并发安全
// 流程: 先查询 -> 如锁存在且未过期则失败 -> 如锁不存在或已过期则插入/更新
func (q *Queries) TryAcquireLock(ctx context.Context, arg TryAcquireLockParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, tryAcquireLock,
		arg.LockKey,
		arg.LockHolder,
		arg.LockTtl,
		arg.ExpireTime,
	)
}
