// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_def.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
	"strings"
)

const batchDeleteTaskDefByID = `-- name: BatchDeleteTaskDefByID :execresult
DELETE FROM task_def WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) BatchDeleteTaskDefByID(ctx context.Context, ids []int64) (sql.Result, error) {
	query := batchDeleteTaskDefByID
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	return q.db.ExecContext(ctx, query, queryParams...)
}

const countTaskDefs = `-- name: CountTaskDefs :one
SELECT COUNT(*) AS cnt FROM task_def
`

func (q *Queries) CountTaskDefs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTaskDefs)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const createTaskDef = `-- name: CreateTaskDef :execresult
INSERT INTO task_def (
  name,
  description,
  task_type,
  config,
  retry_policy
) VALUES (?, ?, ?, ?, ?)
`

type CreateTaskDefParams struct {
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	TaskType    TaskDefTaskType `json:"task_type"`
	Config      json.RawMessage `json:"config"`
	RetryPolicy json.RawMessage `json:"retry_policy"`
}

func (q *Queries) CreateTaskDef(ctx context.Context, arg CreateTaskDefParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTaskDef,
		arg.Name,
		arg.Description,
		arg.TaskType,
		arg.Config,
		arg.RetryPolicy,
	)
}

const deleteTaskDefByID = `-- name: DeleteTaskDefByID :execresult
DELETE FROM task_def WHERE id = ? LIMIT 1
`

func (q *Queries) DeleteTaskDefByID(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTaskDefByID, id)
}

const getTaskDefByID = `-- name: GetTaskDefByID :one
SELECT
  id,
  gmt_create,
  gmt_modified,
  name,
  description,
  task_type,
  config,
  retry_policy
FROM task_def
WHERE id = ?
`

func (q *Queries) GetTaskDefByID(ctx context.Context, id int64) (TaskDef, error) {
	row := q.db.QueryRowContext(ctx, getTaskDefByID, id)
	var i TaskDef
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Name,
		&i.Description,
		&i.TaskType,
		&i.Config,
		&i.RetryPolicy,
	)
	return i, err
}

const getTaskDefByName = `-- name: GetTaskDefByName :one
SELECT
  id,
  gmt_create,
  gmt_modified,
  name,
  description,
  task_type,
  config,
  retry_policy
FROM task_def
WHERE name = ?
ORDER BY id DESC
`

func (q *Queries) GetTaskDefByName(ctx context.Context, name string) (TaskDef, error) {
	row := q.db.QueryRowContext(ctx, getTaskDefByName, name)
	var i TaskDef
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Name,
		&i.Description,
		&i.TaskType,
		&i.Config,
		&i.RetryPolicy,
	)
	return i, err
}

const listTaskDefs = `-- name: ListTaskDefs :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  name,
  description,
  task_type,
  config,
  retry_policy
FROM task_def
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListTaskDefsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTaskDefs(ctx context.Context, arg ListTaskDefsParams) ([]TaskDef, error) {
	rows, err := q.db.QueryContext(ctx, listTaskDefs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDef{}
	for rows.Next() {
		var i TaskDef
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Name,
			&i.Description,
			&i.TaskType,
			&i.Config,
			&i.RetryPolicy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDefsByType = `-- name: ListTaskDefsByType :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  name,
  description,
  task_type,
  config,
  retry_policy
FROM task_def
WHERE task_type = ?
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListTaskDefsByTypeParams struct {
	TaskType TaskDefTaskType `json:"task_type"`
	Limit    int32           `json:"limit"`
	Offset   int32           `json:"offset"`
}

func (q *Queries) ListTaskDefsByType(ctx context.Context, arg ListTaskDefsByTypeParams) ([]TaskDef, error) {
	rows, err := q.db.QueryContext(ctx, listTaskDefsByType, arg.TaskType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDef{}
	for rows.Next() {
		var i TaskDef
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Name,
			&i.Description,
			&i.TaskType,
			&i.Config,
			&i.RetryPolicy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTaskDefsByName = `-- name: SearchTaskDefsByName :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  name,
  description,
  task_type,
  config,
  retry_policy
FROM task_def
WHERE name LIKE ?
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type SearchTaskDefsByNameParams struct {
	Name   string `json:"name"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SearchTaskDefsByName(ctx context.Context, arg SearchTaskDefsByNameParams) ([]TaskDef, error) {
	rows, err := q.db.QueryContext(ctx, searchTaskDefsByName, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDef{}
	for rows.Next() {
		var i TaskDef
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Name,
			&i.Description,
			&i.TaskType,
			&i.Config,
			&i.RetryPolicy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskDefByID = `-- name: UpdateTaskDefByID :execresult
UPDATE task_def
SET
  name = ?,
  description = ?,
  task_type = ?,
  config = ?,
  retry_policy = ?
WHERE id = ?
LIMIT 1
`

type UpdateTaskDefByIDParams struct {
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	TaskType    TaskDefTaskType `json:"task_type"`
	Config      json.RawMessage `json:"config"`
	RetryPolicy json.RawMessage `json:"retry_policy"`
	ID          int64           `json:"id"`
}

func (q *Queries) UpdateTaskDefByID(ctx context.Context, arg UpdateTaskDefByIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTaskDefByID,
		arg.Name,
		arg.Description,
		arg.TaskType,
		arg.Config,
		arg.RetryPolicy,
		arg.ID,
	)
}

const updateTaskDefConfigByID = `-- name: UpdateTaskDefConfigByID :execresult
UPDATE task_def
SET config = ?, retry_policy = ?
WHERE id = ?
`

type UpdateTaskDefConfigByIDParams struct {
	Config      json.RawMessage `json:"config"`
	RetryPolicy json.RawMessage `json:"retry_policy"`
	ID          int64           `json:"id"`
}

func (q *Queries) UpdateTaskDefConfigByID(ctx context.Context, arg UpdateTaskDefConfigByIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTaskDefConfigByID, arg.Config, arg.RetryPolicy, arg.ID)
}
