// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_workflow_instance.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
)

const countTaskWorkflowInstances = `-- name: CountTaskWorkflowInstances :one
SELECT COUNT(*) AS cnt FROM task_workflow_instance
`

func (q *Queries) CountTaskWorkflowInstances(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTaskWorkflowInstances)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const createTaskWorkflowInstance = `-- name: CreateTaskWorkflowInstance :execresult
INSERT INTO task_workflow_instance (
  workflow_def_id,
  workflow_def_version,
  trigger_type,
  trigger_id,
  input_params,
  status,
  execution_mode,
  priority,
  created_by
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskWorkflowInstanceParams struct {
	WorkflowDefID      int64                                 `json:"workflow_def_id"`
	WorkflowDefVersion sql.NullInt32                         `json:"workflow_def_version"`
	TriggerType        TaskWorkflowInstanceTriggerType       `json:"trigger_type"`
	TriggerID          sql.NullString                        `json:"trigger_id"`
	InputParams        json.RawMessage                       `json:"input_params"`
	Status             TaskWorkflowInstanceStatus            `json:"status"`
	ExecutionMode      NullTaskWorkflowInstanceExecutionMode `json:"execution_mode"`
	Priority           sql.NullInt32                         `json:"priority"`
	CreatedBy          sql.NullString                        `json:"created_by"`
}

func (q *Queries) CreateTaskWorkflowInstance(ctx context.Context, arg CreateTaskWorkflowInstanceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTaskWorkflowInstance,
		arg.WorkflowDefID,
		arg.WorkflowDefVersion,
		arg.TriggerType,
		arg.TriggerID,
		arg.InputParams,
		arg.Status,
		arg.ExecutionMode,
		arg.Priority,
		arg.CreatedBy,
	)
}

const getTaskWorkflowInstanceByID = `-- name: GetTaskWorkflowInstanceByID :one
SELECT id, gmt_create, gmt_modified, workflow_def_id, workflow_def_version, trigger_type, trigger_id, input_params, status, status_reason, current_node_id, execution_mode, priority, gmt_start, gmt_end, gmt_paused, total_nodes, completed_nodes, failed_nodes, result_summary, error_info, created_by FROM task_workflow_instance WHERE id = ?
`

func (q *Queries) GetTaskWorkflowInstanceByID(ctx context.Context, id int64) (TaskWorkflowInstance, error) {
	row := q.db.QueryRowContext(ctx, getTaskWorkflowInstanceByID, id)
	var i TaskWorkflowInstance
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.WorkflowDefID,
		&i.WorkflowDefVersion,
		&i.TriggerType,
		&i.TriggerID,
		&i.InputParams,
		&i.Status,
		&i.StatusReason,
		&i.CurrentNodeID,
		&i.ExecutionMode,
		&i.Priority,
		&i.GmtStart,
		&i.GmtEnd,
		&i.GmtPaused,
		&i.TotalNodes,
		&i.CompletedNodes,
		&i.FailedNodes,
		&i.ResultSummary,
		&i.ErrorInfo,
		&i.CreatedBy,
	)
	return i, err
}

const listPendingTaskWorkflowInstances = `-- name: ListPendingTaskWorkflowInstances :many
SELECT id, gmt_create, gmt_modified, workflow_def_id, workflow_def_version, trigger_type, trigger_id, input_params, status, status_reason, current_node_id, execution_mode, priority, gmt_start, gmt_end, gmt_paused, total_nodes, completed_nodes, failed_nodes, result_summary, error_info, created_by FROM task_workflow_instance
WHERE status = 'PENDING'
ORDER BY priority DESC, gmt_create ASC
LIMIT ?
`

func (q *Queries) ListPendingTaskWorkflowInstances(ctx context.Context, limit int32) ([]TaskWorkflowInstance, error) {
	rows, err := q.db.QueryContext(ctx, listPendingTaskWorkflowInstances, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskWorkflowInstance{}
	for rows.Next() {
		var i TaskWorkflowInstance
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.WorkflowDefID,
			&i.WorkflowDefVersion,
			&i.TriggerType,
			&i.TriggerID,
			&i.InputParams,
			&i.Status,
			&i.StatusReason,
			&i.CurrentNodeID,
			&i.ExecutionMode,
			&i.Priority,
			&i.GmtStart,
			&i.GmtEnd,
			&i.GmtPaused,
			&i.TotalNodes,
			&i.CompletedNodes,
			&i.FailedNodes,
			&i.ResultSummary,
			&i.ErrorInfo,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskWorkflowInstances = `-- name: ListTaskWorkflowInstances :many
SELECT id, gmt_create, gmt_modified, workflow_def_id, workflow_def_version, trigger_type, trigger_id, input_params, status, status_reason, current_node_id, execution_mode, priority, gmt_start, gmt_end, gmt_paused, total_nodes, completed_nodes, failed_nodes, result_summary, error_info, created_by FROM task_workflow_instance
ORDER BY gmt_create DESC
LIMIT ? OFFSET ?
`

type ListTaskWorkflowInstancesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTaskWorkflowInstances(ctx context.Context, arg ListTaskWorkflowInstancesParams) ([]TaskWorkflowInstance, error) {
	rows, err := q.db.QueryContext(ctx, listTaskWorkflowInstances, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskWorkflowInstance{}
	for rows.Next() {
		var i TaskWorkflowInstance
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.WorkflowDefID,
			&i.WorkflowDefVersion,
			&i.TriggerType,
			&i.TriggerID,
			&i.InputParams,
			&i.Status,
			&i.StatusReason,
			&i.CurrentNodeID,
			&i.ExecutionMode,
			&i.Priority,
			&i.GmtStart,
			&i.GmtEnd,
			&i.GmtPaused,
			&i.TotalNodes,
			&i.CompletedNodes,
			&i.FailedNodes,
			&i.ResultSummary,
			&i.ErrorInfo,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskWorkflowInstanceProgress = `-- name: UpdateTaskWorkflowInstanceProgress :execresult
UPDATE task_workflow_instance SET
  completed_nodes = ?,
  failed_nodes = ?,
  total_nodes = ?
WHERE id = ?
`

type UpdateTaskWorkflowInstanceProgressParams struct {
	CompletedNodes sql.NullInt32 `json:"completed_nodes"`
	FailedNodes    sql.NullInt32 `json:"failed_nodes"`
	TotalNodes     sql.NullInt32 `json:"total_nodes"`
	ID             int64         `json:"id"`
}

func (q *Queries) UpdateTaskWorkflowInstanceProgress(ctx context.Context, arg UpdateTaskWorkflowInstanceProgressParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTaskWorkflowInstanceProgress,
		arg.CompletedNodes,
		arg.FailedNodes,
		arg.TotalNodes,
		arg.ID,
	)
}

const updateTaskWorkflowInstanceStatus = `-- name: UpdateTaskWorkflowInstanceStatus :execresult
UPDATE task_workflow_instance SET
  status = ?,
  status_reason = ?,
  current_node_id = ?,
  gmt_start = COALESCE(?, gmt_start),
  gmt_end = COALESCE(?, gmt_end),
  gmt_paused = COALESCE(?, gmt_paused),
  completed_nodes = ?,
  failed_nodes = ?,
  result_summary = ?,
  error_info = ?
WHERE id = ?
`

type UpdateTaskWorkflowInstanceStatusParams struct {
	Status         TaskWorkflowInstanceStatus `json:"status"`
	StatusReason   sql.NullString             `json:"status_reason"`
	CurrentNodeID  sql.NullString             `json:"current_node_id"`
	GmtStart       sql.NullTime               `json:"gmt_start"`
	GmtEnd         sql.NullTime               `json:"gmt_end"`
	GmtPaused      sql.NullTime               `json:"gmt_paused"`
	CompletedNodes sql.NullInt32              `json:"completed_nodes"`
	FailedNodes    sql.NullInt32              `json:"failed_nodes"`
	ResultSummary  json.RawMessage            `json:"result_summary"`
	ErrorInfo      json.RawMessage            `json:"error_info"`
	ID             int64                      `json:"id"`
}

func (q *Queries) UpdateTaskWorkflowInstanceStatus(ctx context.Context, arg UpdateTaskWorkflowInstanceStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTaskWorkflowInstanceStatus,
		arg.Status,
		arg.StatusReason,
		arg.CurrentNodeID,
		arg.GmtStart,
		arg.GmtEnd,
		arg.GmtPaused,
		arg.CompletedNodes,
		arg.FailedNodes,
		arg.ResultSummary,
		arg.ErrorInfo,
		arg.ID,
	)
}
