// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_atomic.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
)

const countTaskAtomicDefs = `-- name: CountTaskAtomicDefs :one
SELECT COUNT(*) AS cnt FROM task_atomic_def WHERE status = 'ENABLED'
`

func (q *Queries) CountTaskAtomicDefs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTaskAtomicDefs)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const createTaskAtomicDef = `-- name: CreateTaskAtomicDef :execresult
INSERT INTO task_atomic_def (
  name,
  description,
  task_category,
  script_type,
  script_content,
  rollback_script_type,
  rollback_script_content,
  http_config,
  builtin_config,
  timeout,
  retry_count,
  retry_interval,
  is_rollback_supported,
  parameters,
  output_schema,
  env_vars,
  working_dir,
  status
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskAtomicDefParams struct {
	Name                  string                              `json:"name"`
	Description           sql.NullString                      `json:"description"`
	TaskCategory          TaskAtomicDefTaskCategory           `json:"task_category"`
	ScriptType            NullTaskAtomicDefScriptType         `json:"script_type"`
	ScriptContent         string                              `json:"script_content"`
	RollbackScriptType    NullTaskAtomicDefRollbackScriptType `json:"rollback_script_type"`
	RollbackScriptContent sql.NullString                      `json:"rollback_script_content"`
	HttpConfig            json.RawMessage                     `json:"http_config"`
	BuiltinConfig         json.RawMessage                     `json:"builtin_config"`
	Timeout               sql.NullInt32                       `json:"timeout"`
	RetryCount            sql.NullInt32                       `json:"retry_count"`
	RetryInterval         sql.NullInt32                       `json:"retry_interval"`
	IsRollbackSupported   sql.NullBool                        `json:"is_rollback_supported"`
	Parameters            json.RawMessage                     `json:"parameters"`
	OutputSchema          json.RawMessage                     `json:"output_schema"`
	EnvVars               json.RawMessage                     `json:"env_vars"`
	WorkingDir            sql.NullString                      `json:"working_dir"`
	Status                NullTaskAtomicDefStatus             `json:"status"`
}

func (q *Queries) CreateTaskAtomicDef(ctx context.Context, arg CreateTaskAtomicDefParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTaskAtomicDef,
		arg.Name,
		arg.Description,
		arg.TaskCategory,
		arg.ScriptType,
		arg.ScriptContent,
		arg.RollbackScriptType,
		arg.RollbackScriptContent,
		arg.HttpConfig,
		arg.BuiltinConfig,
		arg.Timeout,
		arg.RetryCount,
		arg.RetryInterval,
		arg.IsRollbackSupported,
		arg.Parameters,
		arg.OutputSchema,
		arg.EnvVars,
		arg.WorkingDir,
		arg.Status,
	)
}

const deleteTaskAtomicDefByID = `-- name: DeleteTaskAtomicDefByID :execresult
DELETE FROM task_atomic_def WHERE id = ? LIMIT 1
`

func (q *Queries) DeleteTaskAtomicDefByID(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTaskAtomicDefByID, id)
}

const getTaskAtomicDefByID = `-- name: GetTaskAtomicDefByID :one
SELECT id, gmt_create, gmt_modified, name, description, task_category, script_type, script_content, rollback_script_type, rollback_script_content, http_config, builtin_config, timeout, retry_count, retry_interval, is_rollback_supported, parameters, output_schema, env_vars, working_dir, status FROM task_atomic_def WHERE id = ?
`

func (q *Queries) GetTaskAtomicDefByID(ctx context.Context, id int64) (TaskAtomicDef, error) {
	row := q.db.QueryRowContext(ctx, getTaskAtomicDefByID, id)
	var i TaskAtomicDef
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Name,
		&i.Description,
		&i.TaskCategory,
		&i.ScriptType,
		&i.ScriptContent,
		&i.RollbackScriptType,
		&i.RollbackScriptContent,
		&i.HttpConfig,
		&i.BuiltinConfig,
		&i.Timeout,
		&i.RetryCount,
		&i.RetryInterval,
		&i.IsRollbackSupported,
		&i.Parameters,
		&i.OutputSchema,
		&i.EnvVars,
		&i.WorkingDir,
		&i.Status,
	)
	return i, err
}

const getTaskAtomicDefByName = `-- name: GetTaskAtomicDefByName :one
SELECT id, gmt_create, gmt_modified, name, description, task_category, script_type, script_content, rollback_script_type, rollback_script_content, http_config, builtin_config, timeout, retry_count, retry_interval, is_rollback_supported, parameters, output_schema, env_vars, working_dir, status FROM task_atomic_def WHERE name = ? LIMIT 1
`

func (q *Queries) GetTaskAtomicDefByName(ctx context.Context, name string) (TaskAtomicDef, error) {
	row := q.db.QueryRowContext(ctx, getTaskAtomicDefByName, name)
	var i TaskAtomicDef
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Name,
		&i.Description,
		&i.TaskCategory,
		&i.ScriptType,
		&i.ScriptContent,
		&i.RollbackScriptType,
		&i.RollbackScriptContent,
		&i.HttpConfig,
		&i.BuiltinConfig,
		&i.Timeout,
		&i.RetryCount,
		&i.RetryInterval,
		&i.IsRollbackSupported,
		&i.Parameters,
		&i.OutputSchema,
		&i.EnvVars,
		&i.WorkingDir,
		&i.Status,
	)
	return i, err
}

const listTaskAtomicDefs = `-- name: ListTaskAtomicDefs :many
SELECT id, gmt_create, gmt_modified, name, description, task_category, script_type, script_content, rollback_script_type, rollback_script_content, http_config, builtin_config, timeout, retry_count, retry_interval, is_rollback_supported, parameters, output_schema, env_vars, working_dir, status FROM task_atomic_def
WHERE status = 'ENABLED'
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListTaskAtomicDefsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTaskAtomicDefs(ctx context.Context, arg ListTaskAtomicDefsParams) ([]TaskAtomicDef, error) {
	rows, err := q.db.QueryContext(ctx, listTaskAtomicDefs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskAtomicDef{}
	for rows.Next() {
		var i TaskAtomicDef
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Name,
			&i.Description,
			&i.TaskCategory,
			&i.ScriptType,
			&i.ScriptContent,
			&i.RollbackScriptType,
			&i.RollbackScriptContent,
			&i.HttpConfig,
			&i.BuiltinConfig,
			&i.Timeout,
			&i.RetryCount,
			&i.RetryInterval,
			&i.IsRollbackSupported,
			&i.Parameters,
			&i.OutputSchema,
			&i.EnvVars,
			&i.WorkingDir,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskAtomicDefByID = `-- name: UpdateTaskAtomicDefByID :execresult
UPDATE task_atomic_def SET
  name = ?,
  description = ?,
  task_category = ?,
  script_type = ?,
  script_content = ?,
  rollback_script_type = ?,
  rollback_script_content = ?,
  http_config = ?,
  builtin_config = ?,
  timeout = ?,
  retry_count = ?,
  retry_interval = ?,
  is_rollback_supported = ?,
  parameters = ?,
  output_schema = ?,
  env_vars = ?,
  working_dir = ?,
  status = ?
WHERE id = ?
`

type UpdateTaskAtomicDefByIDParams struct {
	Name                  string                              `json:"name"`
	Description           sql.NullString                      `json:"description"`
	TaskCategory          TaskAtomicDefTaskCategory           `json:"task_category"`
	ScriptType            NullTaskAtomicDefScriptType         `json:"script_type"`
	ScriptContent         string                              `json:"script_content"`
	RollbackScriptType    NullTaskAtomicDefRollbackScriptType `json:"rollback_script_type"`
	RollbackScriptContent sql.NullString                      `json:"rollback_script_content"`
	HttpConfig            json.RawMessage                     `json:"http_config"`
	BuiltinConfig         json.RawMessage                     `json:"builtin_config"`
	Timeout               sql.NullInt32                       `json:"timeout"`
	RetryCount            sql.NullInt32                       `json:"retry_count"`
	RetryInterval         sql.NullInt32                       `json:"retry_interval"`
	IsRollbackSupported   sql.NullBool                        `json:"is_rollback_supported"`
	Parameters            json.RawMessage                     `json:"parameters"`
	OutputSchema          json.RawMessage                     `json:"output_schema"`
	EnvVars               json.RawMessage                     `json:"env_vars"`
	WorkingDir            sql.NullString                      `json:"working_dir"`
	Status                NullTaskAtomicDefStatus             `json:"status"`
	ID                    int64                               `json:"id"`
}

func (q *Queries) UpdateTaskAtomicDefByID(ctx context.Context, arg UpdateTaskAtomicDefByIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTaskAtomicDefByID,
		arg.Name,
		arg.Description,
		arg.TaskCategory,
		arg.ScriptType,
		arg.ScriptContent,
		arg.RollbackScriptType,
		arg.RollbackScriptContent,
		arg.HttpConfig,
		arg.BuiltinConfig,
		arg.Timeout,
		arg.RetryCount,
		arg.RetryInterval,
		arg.IsRollbackSupported,
		arg.Parameters,
		arg.OutputSchema,
		arg.EnvVars,
		arg.WorkingDir,
		arg.Status,
		arg.ID,
	)
}
