// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_tmpl.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createCompositeTask = `-- name: CreateCompositeTask :execresult
INSERT INTO task_tmpl (name, description, config, is_enable)
VALUES (?, ?, ?, ?)
`

type CreateCompositeTaskParams struct {
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Config      json.RawMessage `json:"config"`
	IsEnable    bool            `json:"is_enable"`
}

func (q *Queries) CreateCompositeTask(ctx context.Context, arg CreateCompositeTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCompositeTask,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.IsEnable,
	)
}

const deleteCompositeTask = `-- name: DeleteCompositeTask :execrows
DELETE FROM task_tmpl
WHERE id = ?
`

func (q *Queries) DeleteCompositeTask(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCompositeTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCompositeTaskByID = `-- name: GetCompositeTaskByID :one
SELECT id, gmt_create, gmt_modified, name, description, config, is_enable
FROM task_tmpl
WHERE id = ?
`

func (q *Queries) GetCompositeTaskByID(ctx context.Context, id int64) (TaskTmpl, error) {
	row := q.db.QueryRowContext(ctx, getCompositeTaskByID, id)
	var i TaskTmpl
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.IsEnable,
	)
	return i, err
}

const getCompositeTaskByName = `-- name: GetCompositeTaskByName :one
SELECT id, gmt_create, gmt_modified, name, description, config, is_enable
FROM task_tmpl
WHERE name = ?
`

func (q *Queries) GetCompositeTaskByName(ctx context.Context, name string) (TaskTmpl, error) {
	row := q.db.QueryRowContext(ctx, getCompositeTaskByName, name)
	var i TaskTmpl
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.IsEnable,
	)
	return i, err
}

const listCompositeTasks = `-- name: ListCompositeTasks :many
SELECT id, gmt_create, gmt_modified, name, description, config, is_enable
FROM task_tmpl
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListCompositeTasksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCompositeTasks(ctx context.Context, arg ListCompositeTasksParams) ([]TaskTmpl, error) {
	rows, err := q.db.QueryContext(ctx, listCompositeTasks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskTmpl{}
	for rows.Next() {
		var i TaskTmpl
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.IsEnable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompositeTask = `-- name: UpdateCompositeTask :execrows
UPDATE task_tmpl
SET
  name = ?,
  description = ?,
  config = ?,
  is_enable = ?
WHERE id = ?
`

type UpdateCompositeTaskParams struct {
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Config      json.RawMessage `json:"config"`
	IsEnable    bool            `json:"is_enable"`
	ID          int64           `json:"id"`
}

func (q *Queries) UpdateCompositeTask(ctx context.Context, arg UpdateCompositeTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCompositeTask,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.IsEnable,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
