// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_execution_log.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createTaskExecutionLog = `-- name: CreateTaskExecutionLog :execresult
INSERT INTO task_execution_log (
  workflow_instance_id,
  node_instance_id,
  task_atomic_instance_id,
  log_level,
  log_type,
  message,
  context
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskExecutionLogParams struct {
	WorkflowInstanceID   int64                    `json:"workflow_instance_id"`
	NodeInstanceID       sql.NullInt64            `json:"node_instance_id"`
	TaskAtomicInstanceID sql.NullInt64            `json:"task_atomic_instance_id"`
	LogLevel             TaskExecutionLogLogLevel `json:"log_level"`
	LogType              TaskExecutionLogLogType  `json:"log_type"`
	Message              string                   `json:"message"`
	Context              json.RawMessage          `json:"context"`
}

func (q *Queries) CreateTaskExecutionLog(ctx context.Context, arg CreateTaskExecutionLogParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTaskExecutionLog,
		arg.WorkflowInstanceID,
		arg.NodeInstanceID,
		arg.TaskAtomicInstanceID,
		arg.LogLevel,
		arg.LogType,
		arg.Message,
		arg.Context,
	)
}

const listTaskExecutionLogs = `-- name: ListTaskExecutionLogs :many
SELECT id, gmt_create, workflow_instance_id, node_instance_id, task_atomic_instance_id, log_level, log_type, message, context FROM task_execution_log
WHERE workflow_instance_id = ?
ORDER BY gmt_create ASC
`

func (q *Queries) ListTaskExecutionLogs(ctx context.Context, workflowInstanceID int64) ([]TaskExecutionLog, error) {
	rows, err := q.db.QueryContext(ctx, listTaskExecutionLogs, workflowInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskExecutionLog{}
	for rows.Next() {
		var i TaskExecutionLog
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.WorkflowInstanceID,
			&i.NodeInstanceID,
			&i.TaskAtomicInstanceID,
			&i.LogLevel,
			&i.LogType,
			&i.Message,
			&i.Context,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
