// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_atomic_instance.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createTaskAtomicInstance = `-- name: CreateTaskAtomicInstance :execresult
INSERT INTO task_atomic_instance (
  node_instance_id,
  task_atomic_def_id,
  status,
  input_params,
  timeout
) VALUES (?, ?, ?, ?, ?)
`

type CreateTaskAtomicInstanceParams struct {
	NodeInstanceID  int64                    `json:"node_instance_id"`
	TaskAtomicDefID int64                    `json:"task_atomic_def_id"`
	Status          TaskAtomicInstanceStatus `json:"status"`
	InputParams     json.RawMessage          `json:"input_params"`
	Timeout         sql.NullInt32            `json:"timeout"`
}

func (q *Queries) CreateTaskAtomicInstance(ctx context.Context, arg CreateTaskAtomicInstanceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTaskAtomicInstance,
		arg.NodeInstanceID,
		arg.TaskAtomicDefID,
		arg.Status,
		arg.InputParams,
		arg.Timeout,
	)
}

const getTaskAtomicInstanceByID = `-- name: GetTaskAtomicInstanceByID :one
SELECT id, gmt_create, gmt_modified, node_instance_id, task_atomic_def_id, status, input_params, output_result, execution_log, error_log, rollback_log, rollback_result, timeout, gmt_start, gmt_end, duration_ms, worker_id FROM task_atomic_instance WHERE id = ?
`

func (q *Queries) GetTaskAtomicInstanceByID(ctx context.Context, id int64) (TaskAtomicInstance, error) {
	row := q.db.QueryRowContext(ctx, getTaskAtomicInstanceByID, id)
	var i TaskAtomicInstance
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.NodeInstanceID,
		&i.TaskAtomicDefID,
		&i.Status,
		&i.InputParams,
		&i.OutputResult,
		&i.ExecutionLog,
		&i.ErrorLog,
		&i.RollbackLog,
		&i.RollbackResult,
		&i.Timeout,
		&i.GmtStart,
		&i.GmtEnd,
		&i.DurationMs,
		&i.WorkerID,
	)
	return i, err
}

const listTaskAtomicInstances = `-- name: ListTaskAtomicInstances :many
SELECT id, gmt_create, gmt_modified, node_instance_id, task_atomic_def_id, status, input_params, output_result, execution_log, error_log, rollback_log, rollback_result, timeout, gmt_start, gmt_end, duration_ms, worker_id FROM task_atomic_instance
WHERE node_instance_id = ?
ORDER BY id ASC
`

func (q *Queries) ListTaskAtomicInstances(ctx context.Context, nodeInstanceID int64) ([]TaskAtomicInstance, error) {
	rows, err := q.db.QueryContext(ctx, listTaskAtomicInstances, nodeInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskAtomicInstance{}
	for rows.Next() {
		var i TaskAtomicInstance
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.NodeInstanceID,
			&i.TaskAtomicDefID,
			&i.Status,
			&i.InputParams,
			&i.OutputResult,
			&i.ExecutionLog,
			&i.ErrorLog,
			&i.RollbackLog,
			&i.RollbackResult,
			&i.Timeout,
			&i.GmtStart,
			&i.GmtEnd,
			&i.DurationMs,
			&i.WorkerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskAtomicInstanceRollback = `-- name: UpdateTaskAtomicInstanceRollback :execresult
UPDATE task_atomic_instance SET
  status = 'ROLLED_BACK',
  rollback_log = ?,
  rollback_result = ?
WHERE id = ?
`

type UpdateTaskAtomicInstanceRollbackParams struct {
	RollbackLog    sql.NullString  `json:"rollback_log"`
	RollbackResult json.RawMessage `json:"rollback_result"`
	ID             int64           `json:"id"`
}

func (q *Queries) UpdateTaskAtomicInstanceRollback(ctx context.Context, arg UpdateTaskAtomicInstanceRollbackParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTaskAtomicInstanceRollback, arg.RollbackLog, arg.RollbackResult, arg.ID)
}

const updateTaskAtomicInstanceStatus = `-- name: UpdateTaskAtomicInstanceStatus :execresult
UPDATE task_atomic_instance SET
  status = ?,
  output_result = ?,
  execution_log = ?,
  error_log = ?,
  gmt_start = COALESCE(?, gmt_start),
  gmt_end = COALESCE(?, gmt_end),
  duration_ms = ?,
  worker_id = ?
WHERE id = ?
`

type UpdateTaskAtomicInstanceStatusParams struct {
	Status       TaskAtomicInstanceStatus `json:"status"`
	OutputResult json.RawMessage          `json:"output_result"`
	ExecutionLog sql.NullString           `json:"execution_log"`
	ErrorLog     sql.NullString           `json:"error_log"`
	GmtStart     sql.NullTime             `json:"gmt_start"`
	GmtEnd       sql.NullTime             `json:"gmt_end"`
	DurationMs   sql.NullInt32            `json:"duration_ms"`
	WorkerID     sql.NullString           `json:"worker_id"`
	ID           int64                    `json:"id"`
}

func (q *Queries) UpdateTaskAtomicInstanceStatus(ctx context.Context, arg UpdateTaskAtomicInstanceStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTaskAtomicInstanceStatus,
		arg.Status,
		arg.OutputResult,
		arg.ExecutionLog,
		arg.ErrorLog,
		arg.GmtStart,
		arg.GmtEnd,
		arg.DurationMs,
		arg.WorkerID,
		arg.ID,
	)
}
