// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_node_instance.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createTaskNodeInstance = `-- name: CreateTaskNodeInstance :execresult
INSERT INTO task_node_instance (
  workflow_instance_id,
  node_def_id,
  node_id,
  status,
  input_params
) VALUES (?, ?, ?, ?, ?)
`

type CreateTaskNodeInstanceParams struct {
	WorkflowInstanceID int64                  `json:"workflow_instance_id"`
	NodeDefID          int64                  `json:"node_def_id"`
	NodeID             string                 `json:"node_id"`
	Status             TaskNodeInstanceStatus `json:"status"`
	InputParams        json.RawMessage        `json:"input_params"`
}

func (q *Queries) CreateTaskNodeInstance(ctx context.Context, arg CreateTaskNodeInstanceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTaskNodeInstance,
		arg.WorkflowInstanceID,
		arg.NodeDefID,
		arg.NodeID,
		arg.Status,
		arg.InputParams,
	)
}

const getTaskNodeInstanceByID = `-- name: GetTaskNodeInstanceByID :one
SELECT id, gmt_create, gmt_modified, workflow_instance_id, node_def_id, node_id, status, status_reason, input_params, output_result, execution_log, error_log, retry_count, gmt_start, gmt_end, duration_ms, worker_id FROM task_node_instance WHERE id = ?
`

func (q *Queries) GetTaskNodeInstanceByID(ctx context.Context, id int64) (TaskNodeInstance, error) {
	row := q.db.QueryRowContext(ctx, getTaskNodeInstanceByID, id)
	var i TaskNodeInstance
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.WorkflowInstanceID,
		&i.NodeDefID,
		&i.NodeID,
		&i.Status,
		&i.StatusReason,
		&i.InputParams,
		&i.OutputResult,
		&i.ExecutionLog,
		&i.ErrorLog,
		&i.RetryCount,
		&i.GmtStart,
		&i.GmtEnd,
		&i.DurationMs,
		&i.WorkerID,
	)
	return i, err
}

const listPendingTaskNodeInstances = `-- name: ListPendingTaskNodeInstances :many
SELECT id, gmt_create, gmt_modified, workflow_instance_id, node_def_id, node_id, status, status_reason, input_params, output_result, execution_log, error_log, retry_count, gmt_start, gmt_end, duration_ms, worker_id FROM task_node_instance
WHERE workflow_instance_id = ? AND status = 'PENDING'
ORDER BY id ASC
`

func (q *Queries) ListPendingTaskNodeInstances(ctx context.Context, workflowInstanceID int64) ([]TaskNodeInstance, error) {
	rows, err := q.db.QueryContext(ctx, listPendingTaskNodeInstances, workflowInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskNodeInstance{}
	for rows.Next() {
		var i TaskNodeInstance
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.WorkflowInstanceID,
			&i.NodeDefID,
			&i.NodeID,
			&i.Status,
			&i.StatusReason,
			&i.InputParams,
			&i.OutputResult,
			&i.ExecutionLog,
			&i.ErrorLog,
			&i.RetryCount,
			&i.GmtStart,
			&i.GmtEnd,
			&i.DurationMs,
			&i.WorkerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskNodeInstances = `-- name: ListTaskNodeInstances :many
SELECT id, gmt_create, gmt_modified, workflow_instance_id, node_def_id, node_id, status, status_reason, input_params, output_result, execution_log, error_log, retry_count, gmt_start, gmt_end, duration_ms, worker_id FROM task_node_instance
WHERE workflow_instance_id = ?
ORDER BY id ASC
`

func (q *Queries) ListTaskNodeInstances(ctx context.Context, workflowInstanceID int64) ([]TaskNodeInstance, error) {
	rows, err := q.db.QueryContext(ctx, listTaskNodeInstances, workflowInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskNodeInstance{}
	for rows.Next() {
		var i TaskNodeInstance
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.WorkflowInstanceID,
			&i.NodeDefID,
			&i.NodeID,
			&i.Status,
			&i.StatusReason,
			&i.InputParams,
			&i.OutputResult,
			&i.ExecutionLog,
			&i.ErrorLog,
			&i.RetryCount,
			&i.GmtStart,
			&i.GmtEnd,
			&i.DurationMs,
			&i.WorkerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskNodeInstanceRetry = `-- name: UpdateTaskNodeInstanceRetry :execresult
UPDATE task_node_instance SET
  retry_count = ?,
  status = 'PENDING'
WHERE id = ?
`

type UpdateTaskNodeInstanceRetryParams struct {
	RetryCount sql.NullInt32 `json:"retry_count"`
	ID         int64         `json:"id"`
}

func (q *Queries) UpdateTaskNodeInstanceRetry(ctx context.Context, arg UpdateTaskNodeInstanceRetryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTaskNodeInstanceRetry, arg.RetryCount, arg.ID)
}

const updateTaskNodeInstanceStatus = `-- name: UpdateTaskNodeInstanceStatus :execresult
UPDATE task_node_instance SET
  status = ?,
  status_reason = ?,
  output_result = ?,
  execution_log = ?,
  error_log = ?,
  gmt_start = COALESCE(?, gmt_start),
  gmt_end = COALESCE(?, gmt_end),
  duration_ms = ?,
  worker_id = ?
WHERE id = ?
`

type UpdateTaskNodeInstanceStatusParams struct {
	Status       TaskNodeInstanceStatus `json:"status"`
	StatusReason sql.NullString         `json:"status_reason"`
	OutputResult json.RawMessage        `json:"output_result"`
	ExecutionLog sql.NullString         `json:"execution_log"`
	ErrorLog     sql.NullString         `json:"error_log"`
	GmtStart     sql.NullTime           `json:"gmt_start"`
	GmtEnd       sql.NullTime           `json:"gmt_end"`
	DurationMs   sql.NullInt32          `json:"duration_ms"`
	WorkerID     sql.NullString         `json:"worker_id"`
	ID           int64                  `json:"id"`
}

func (q *Queries) UpdateTaskNodeInstanceStatus(ctx context.Context, arg UpdateTaskNodeInstanceStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTaskNodeInstanceStatus,
		arg.Status,
		arg.StatusReason,
		arg.OutputResult,
		arg.ExecutionLog,
		arg.ErrorLog,
		arg.GmtStart,
		arg.GmtEnd,
		arg.DurationMs,
		arg.WorkerID,
		arg.ID,
	)
}
