// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_atomic.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createTaskAtomic = `-- name: CreateTaskAtomic :execresult
INSERT INTO task_atomic (name, description, task_type, config, is_enable)
VALUES (?, ?, ?, ?, ?)
`

type CreateTaskAtomicParams struct {
	Name        string          `json:"name"`
	Description string          `json:"description"`
	TaskType    string          `json:"task_type"`
	Config      json.RawMessage `json:"config"`
	IsEnable    bool            `json:"is_enable"`
}

func (q *Queries) CreateTaskAtomic(ctx context.Context, arg CreateTaskAtomicParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTaskAtomic,
		arg.Name,
		arg.Description,
		arg.TaskType,
		arg.Config,
		arg.IsEnable,
	)
}

const deleteTaskAtomic = `-- name: DeleteTaskAtomic :execrows
DELETE FROM task_atomic
WHERE id = ?
`

func (q *Queries) DeleteTaskAtomic(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTaskAtomic, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTaskAtomicByID = `-- name: GetTaskAtomicByID :one
SELECT id, gmt_create, gmt_modified, name, description, task_type, config, is_enable
FROM task_atomic
WHERE id = ?
`

func (q *Queries) GetTaskAtomicByID(ctx context.Context, id int64) (TaskAtomic, error) {
	row := q.db.QueryRowContext(ctx, getTaskAtomicByID, id)
	var i TaskAtomic
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Name,
		&i.Description,
		&i.TaskType,
		&i.Config,
		&i.IsEnable,
	)
	return i, err
}

const getTaskAtomicByName = `-- name: GetTaskAtomicByName :one
SELECT id, gmt_create, gmt_modified, name, description, task_type, config, is_enable
FROM task_atomic
WHERE name = ?
`

func (q *Queries) GetTaskAtomicByName(ctx context.Context, name string) (TaskAtomic, error) {
	row := q.db.QueryRowContext(ctx, getTaskAtomicByName, name)
	var i TaskAtomic
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Name,
		&i.Description,
		&i.TaskType,
		&i.Config,
		&i.IsEnable,
	)
	return i, err
}

const listTaskAtomics = `-- name: ListTaskAtomics :many
SELECT id, gmt_create, gmt_modified, name, description, task_type, config, is_enable
FROM task_atomic
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListTaskAtomicsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTaskAtomics(ctx context.Context, arg ListTaskAtomicsParams) ([]TaskAtomic, error) {
	rows, err := q.db.QueryContext(ctx, listTaskAtomics, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskAtomic{}
	for rows.Next() {
		var i TaskAtomic
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Name,
			&i.Description,
			&i.TaskType,
			&i.Config,
			&i.IsEnable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTaskAtomics = `-- name: SearchTaskAtomics :many
SELECT id, gmt_create, gmt_modified, name, description, task_type, config, is_enable
FROM task_atomic
WHERE name like ?
  AND description like ?
  AND task_type = ?
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type SearchTaskAtomicsParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	TaskType    string `json:"task_type"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) SearchTaskAtomics(ctx context.Context, arg SearchTaskAtomicsParams) ([]TaskAtomic, error) {
	rows, err := q.db.QueryContext(ctx, searchTaskAtomics,
		arg.Name,
		arg.Description,
		arg.TaskType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskAtomic{}
	for rows.Next() {
		var i TaskAtomic
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Name,
			&i.Description,
			&i.TaskType,
			&i.Config,
			&i.IsEnable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskAtomic = `-- name: UpdateTaskAtomic :execrows
UPDATE task_atomic
SET
  name = ?,
  description = ?,
  task_type = ?,
  config = ?,
  is_enable = ?
WHERE id = ?
`

type UpdateTaskAtomicParams struct {
	Name        string          `json:"name"`
	Description string          `json:"description"`
	TaskType    string          `json:"task_type"`
	Config      json.RawMessage `json:"config"`
	IsEnable    bool            `json:"is_enable"`
	ID          int64           `json:"id"`
}

func (q *Queries) UpdateTaskAtomic(ctx context.Context, arg UpdateTaskAtomicParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTaskAtomic,
		arg.Name,
		arg.Description,
		arg.TaskType,
		arg.Config,
		arg.IsEnable,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
