// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_def_relation.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
)

const countTaskDefRelations = `-- name: CountTaskDefRelations :one
SELECT COUNT(*) AS cnt
FROM task_def_relation
`

func (q *Queries) CountTaskDefRelations(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTaskDefRelations)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const countTaskDefRelationsByParendID = `-- name: CountTaskDefRelationsByParendID :one
SELECT COUNT(*) AS cnt
FROM task_def_relation
WHERE parent_id = ?
`

func (q *Queries) CountTaskDefRelationsByParendID(ctx context.Context, parentID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTaskDefRelationsByParendID, parentID)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const createTaskDefRelation = `-- name: CreateTaskDefRelation :execresult
INSERT INTO task_def_relation (
  parent_id,
  child_id,
  ord
) VALUES (?, ?, ?)
`

type CreateTaskDefRelationParams struct {
	ParentID int64         `json:"parent_id"`
	ChildID  int64         `json:"child_id"`
	Ord      sql.NullInt32 `json:"ord"`
}

func (q *Queries) CreateTaskDefRelation(ctx context.Context, arg CreateTaskDefRelationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTaskDefRelation, arg.ParentID, arg.ChildID, arg.Ord)
}

const deleteTaskDefRelation = `-- name: DeleteTaskDefRelation :exec
DELETE FROM task_def_relation
WHERE parent_id = ? AND child_id = ?
`

type DeleteTaskDefRelationParams struct {
	ParentID int64 `json:"parent_id"`
	ChildID  int64 `json:"child_id"`
}

func (q *Queries) DeleteTaskDefRelation(ctx context.Context, arg DeleteTaskDefRelationParams) error {
	_, err := q.db.ExecContext(ctx, deleteTaskDefRelation, arg.ParentID, arg.ChildID)
	return err
}

const deleteTaskDefRelationsByChild = `-- name: DeleteTaskDefRelationsByChild :exec
DELETE FROM task_def_relation
WHERE child_id = ?
`

func (q *Queries) DeleteTaskDefRelationsByChild(ctx context.Context, childID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTaskDefRelationsByChild, childID)
	return err
}

const deleteTaskDefRelationsByParent = `-- name: DeleteTaskDefRelationsByParent :exec
DELETE FROM task_def_relation
WHERE parent_id = ?
`

func (q *Queries) DeleteTaskDefRelationsByParent(ctx context.Context, parentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTaskDefRelationsByParent, parentID)
	return err
}

const getChildTaskDefs = `-- name: GetChildTaskDefs :many
SELECT
  td.id,
  td.name,
  td.description,
  td.task_type,
  td.config,
  td.retry_policy,
  tdr.ord
FROM task_def_relation AS tdr
JOIN task_def AS td ON td.id = tdr.child_id
WHERE tdr.parent_id = ?
ORDER BY tdr.ord ASC
`

type GetChildTaskDefsRow struct {
	ID          int64           `json:"id"`
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	TaskType    TaskDefTaskType `json:"task_type"`
	Config      json.RawMessage `json:"config"`
	RetryPolicy json.RawMessage `json:"retry_policy"`
	Ord         sql.NullInt32   `json:"ord"`
}

func (q *Queries) GetChildTaskDefs(ctx context.Context, parentID int64) ([]GetChildTaskDefsRow, error) {
	rows, err := q.db.QueryContext(ctx, getChildTaskDefs, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChildTaskDefsRow{}
	for rows.Next() {
		var i GetChildTaskDefsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.TaskType,
			&i.Config,
			&i.RetryPolicy,
			&i.Ord,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParentTaskDef = `-- name: GetParentTaskDef :one
SELECT
  td.id,
  td.name,
  td.description,
  td.task_type,
  td.config,
  td.retry_policy
FROM task_def_relation AS tdr
JOIN task_def AS td ON td.id = tdr.parent_id
WHERE tdr.child_id = ?
LIMIT 1
`

type GetParentTaskDefRow struct {
	ID          int64           `json:"id"`
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	TaskType    TaskDefTaskType `json:"task_type"`
	Config      json.RawMessage `json:"config"`
	RetryPolicy json.RawMessage `json:"retry_policy"`
}

func (q *Queries) GetParentTaskDef(ctx context.Context, childID int64) (GetParentTaskDefRow, error) {
	row := q.db.QueryRowContext(ctx, getParentTaskDef, childID)
	var i GetParentTaskDefRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TaskType,
		&i.Config,
		&i.RetryPolicy,
	)
	return i, err
}

const getTaskDefRelationByID = `-- name: GetTaskDefRelationByID :one
SELECT
  id,
  gmt_create,
  gmt_modified,
  parent_id,
  child_id,
  ord
FROM task_def_relation
WHERE id = ?
`

func (q *Queries) GetTaskDefRelationByID(ctx context.Context, id int64) (TaskDefRelation, error) {
	row := q.db.QueryRowContext(ctx, getTaskDefRelationByID, id)
	var i TaskDefRelation
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.ParentID,
		&i.ChildID,
		&i.Ord,
	)
	return i, err
}

const getTaskDefTree = `-- name: GetTaskDefTree :many
WITH RECURSIVE def_tree AS (
  SELECT
    td.id,
    td.name,
    td.description,
    td.task_type,
    td.config,
    td.retry_policy,
    tdr.parent_id,
    tdr.ord,
    0 AS depth
  FROM task_def_relation AS tdr
  JOIN task_def AS td ON td.id = tdr.child_id
  WHERE tdr.parent_id = ?
  UNION ALL
  SELECT
    ctd.id,
    ctd.name,
    ctd.description,
    ctd.task_type,
    ctd.config,
    ctd.retry_policy,
    cr.parent_id,
    cr.ord,
    dt.depth + 1
  FROM def_tree AS dt
  JOIN task_def_relation AS cr ON cr.parent_id = dt.id
  JOIN task_def AS ctd ON ctd.id = cr.child_id
)
SELECT id, name, description, task_type, config, retry_policy, parent_id, ord, depth FROM def_tree ORDER BY depth, ord
`

type GetTaskDefTreeRow struct {
	ID          int64           `json:"id"`
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	TaskType    TaskDefTaskType `json:"task_type"`
	Config      json.RawMessage `json:"config"`
	RetryPolicy json.RawMessage `json:"retry_policy"`
	ParentID    int64           `json:"parent_id"`
	Ord         sql.NullInt32   `json:"ord"`
	Depth       int32           `json:"depth"`
}

func (q *Queries) GetTaskDefTree(ctx context.Context, parentID int64) ([]GetTaskDefTreeRow, error) {
	rows, err := q.db.QueryContext(ctx, getTaskDefTree, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTaskDefTreeRow{}
	for rows.Next() {
		var i GetTaskDefTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.TaskType,
			&i.Config,
			&i.RetryPolicy,
			&i.ParentID,
			&i.Ord,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDefRelationsByChild = `-- name: ListTaskDefRelationsByChild :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  parent_id,
  child_id,
  ord
FROM task_def_relation
WHERE child_id = ?
ORDER BY gmt_create DESC
`

func (q *Queries) ListTaskDefRelationsByChild(ctx context.Context, childID int64) ([]TaskDefRelation, error) {
	rows, err := q.db.QueryContext(ctx, listTaskDefRelationsByChild, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDefRelation{}
	for rows.Next() {
		var i TaskDefRelation
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.ParentID,
			&i.ChildID,
			&i.Ord,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDefRelationsByParent = `-- name: ListTaskDefRelationsByParent :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  parent_id,
  child_id,
  ord
FROM task_def_relation
WHERE parent_id = ?
ORDER BY ord ASC
`

func (q *Queries) ListTaskDefRelationsByParent(ctx context.Context, parentID int64) ([]TaskDefRelation, error) {
	rows, err := q.db.QueryContext(ctx, listTaskDefRelationsByParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDefRelation{}
	for rows.Next() {
		var i TaskDefRelation
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.ParentID,
			&i.ChildID,
			&i.Ord,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskDefRelationOrd = `-- name: UpdateTaskDefRelationOrd :exec
UPDATE task_def_relation
SET ord = ?
WHERE parent_id = ? AND child_id = ?
`

type UpdateTaskDefRelationOrdParams struct {
	Ord      sql.NullInt32 `json:"ord"`
	ParentID int64         `json:"parent_id"`
	ChildID  int64         `json:"child_id"`
}

func (q *Queries) UpdateTaskDefRelationOrd(ctx context.Context, arg UpdateTaskDefRelationOrdParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskDefRelationOrd, arg.Ord, arg.ParentID, arg.ChildID)
	return err
}

const updateTaskDefRelationParent = `-- name: UpdateTaskDefRelationParent :exec
UPDATE task_def_relation
SET parent_id = ?
WHERE id = ?
`

type UpdateTaskDefRelationParentParams struct {
	ParentID int64 `json:"parent_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) UpdateTaskDefRelationParent(ctx context.Context, arg UpdateTaskDefRelationParentParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskDefRelationParent, arg.ParentID, arg.ID)
	return err
}
