// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_exec.sql

package repo

import (
	"context"
	"database/sql"
)

const appendTaskExecLog = `-- name: AppendTaskExecLog :exec
UPDATE task_exec
SET log = CONCAT(COALESCE(log, ''), '\n', ?)
WHERE id = ?
`

type AppendTaskExecLogParams struct {
	CONCAT interface{} `json:"concat"`
	ID     int64       `json:"id"`
}

func (q *Queries) AppendTaskExecLog(ctx context.Context, arg AppendTaskExecLogParams) error {
	_, err := q.db.ExecContext(ctx, appendTaskExecLog, arg.CONCAT, arg.ID)
	return err
}

const countTaskExecsByInstanceID = `-- name: CountTaskExecsByInstanceID :one
SELECT COUNT(*) AS cnt
FROM task_exec
WHERE task_instance_id = ?
`

func (q *Queries) CountTaskExecsByInstanceID(ctx context.Context, taskInstanceID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTaskExecsByInstanceID, taskInstanceID)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const countTaskExecsStatus = `-- name: CountTaskExecsStatus :one
SELECT
  SUM(CASE WHEN status = 'RUNNING' THEN 1 ELSE 0 END) AS running_count,
  SUM(CASE WHEN status = 'SUCCESS' THEN 1 ELSE 0 END) AS success_count,
  SUM(CASE WHEN status = 'FAILED' THEN 1 ELSE 0 END) AS failed_count
FROM task_exec
`

type CountTaskExecsStatusRow struct {
	RunningCount interface{} `json:"running_count"`
	SuccessCount interface{} `json:"success_count"`
	FailedCount  interface{} `json:"failed_count"`
}

func (q *Queries) CountTaskExecsStatus(ctx context.Context) (CountTaskExecsStatusRow, error) {
	row := q.db.QueryRowContext(ctx, countTaskExecsStatus)
	var i CountTaskExecsStatusRow
	err := row.Scan(&i.RunningCount, &i.SuccessCount, &i.FailedCount)
	return i, err
}

const countTaskExecsStatusByTaskInstanceID = `-- name: CountTaskExecsStatusByTaskInstanceID :one
SELECT
  task_instance_id,
  SUM(CASE WHEN status = 'RUNNING' THEN 1 ELSE 0 END) AS running_count,
  SUM(CASE WHEN status = 'SUCCESS' THEN 1 ELSE 0 END) AS success_count,
  SUM(CASE WHEN status = 'FAILED' THEN 1 ELSE 0 END) AS failed_count
FROM task_exec
WHERE task_instance_id = ?
GROUP BY task_instance_id
`

type CountTaskExecsStatusByTaskInstanceIDRow struct {
	TaskInstanceID int64       `json:"task_instance_id"`
	RunningCount   interface{} `json:"running_count"`
	SuccessCount   interface{} `json:"success_count"`
	FailedCount    interface{} `json:"failed_count"`
}

func (q *Queries) CountTaskExecsStatusByTaskInstanceID(ctx context.Context, taskInstanceID int64) (CountTaskExecsStatusByTaskInstanceIDRow, error) {
	row := q.db.QueryRowContext(ctx, countTaskExecsStatusByTaskInstanceID, taskInstanceID)
	var i CountTaskExecsStatusByTaskInstanceIDRow
	err := row.Scan(
		&i.TaskInstanceID,
		&i.RunningCount,
		&i.SuccessCount,
		&i.FailedCount,
	)
	return i, err
}

const createTaskExec = `-- name: CreateTaskExec :execresult
INSERT INTO task_exec (
  task_instance_id,
  gmt_start,
  gmt_end,
  status,
  log
)
VALUES (?, ?, ?, ?, ?)
`

type CreateTaskExecParams struct {
	TaskInstanceID int64              `json:"task_instance_id"`
	GmtStart       sql.NullTime       `json:"gmt_start"`
	GmtEnd         sql.NullTime       `json:"gmt_end"`
	Status         NullTaskExecStatus `json:"status"`
	Log            sql.NullString     `json:"log"`
}

func (q *Queries) CreateTaskExec(ctx context.Context, arg CreateTaskExecParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTaskExec,
		arg.TaskInstanceID,
		arg.GmtStart,
		arg.GmtEnd,
		arg.Status,
		arg.Log,
	)
}

const deleteTaskExecByID = `-- name: DeleteTaskExecByID :exec
DELETE FROM task_exec WHERE id = ? LIMIT 1
`

func (q *Queries) DeleteTaskExecByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTaskExecByID, id)
	return err
}

const getAvgTaskExecDurationByTaskInstanceID = `-- name: GetAvgTaskExecDurationByTaskInstanceID :one
SELECT
  task_instance_id,
  AVG(TIMESTAMPDIFF(SECOND, gmt_start, gmt_end)) AS avg_duration_sec
FROM task_exec
WHERE task_instance_id = ?
  AND gmt_start IS NOT NULL AND gmt_end IS NOT NULL
GROUP BY task_instance_id
`

type GetAvgTaskExecDurationByTaskInstanceIDRow struct {
	TaskInstanceID int64       `json:"task_instance_id"`
	AvgDurationSec interface{} `json:"avg_duration_sec"`
}

func (q *Queries) GetAvgTaskExecDurationByTaskInstanceID(ctx context.Context, taskInstanceID int64) (GetAvgTaskExecDurationByTaskInstanceIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAvgTaskExecDurationByTaskInstanceID, taskInstanceID)
	var i GetAvgTaskExecDurationByTaskInstanceIDRow
	err := row.Scan(&i.TaskInstanceID, &i.AvgDurationSec)
	return i, err
}

const getLastTaskExecByInstanceID = `-- name: GetLastTaskExecByInstanceID :one
SELECT
  id,
  gmt_create,
  gmt_modified,
  task_instance_id,
  gmt_start,
  gmt_end,
  status,
  log
FROM task_exec
WHERE task_instance_id = ?
ORDER BY gmt_start DESC
LIMIT 1
`

func (q *Queries) GetLastTaskExecByInstanceID(ctx context.Context, taskInstanceID int64) (TaskExec, error) {
	row := q.db.QueryRowContext(ctx, getLastTaskExecByInstanceID, taskInstanceID)
	var i TaskExec
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.TaskInstanceID,
		&i.GmtStart,
		&i.GmtEnd,
		&i.Status,
		&i.Log,
	)
	return i, err
}

const getTaskExecByID = `-- name: GetTaskExecByID :one
SELECT
  id,
  gmt_create,
  gmt_modified,
  task_instance_id,
  gmt_start,
  gmt_end,
  status,
  log
FROM task_exec
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetTaskExecByID(ctx context.Context, id int64) (TaskExec, error) {
	row := q.db.QueryRowContext(ctx, getTaskExecByID, id)
	var i TaskExec
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.TaskInstanceID,
		&i.GmtStart,
		&i.GmtEnd,
		&i.Status,
		&i.Log,
	)
	return i, err
}

const getTaskExecDetailByTaskInstanceID = `-- name: GetTaskExecDetailByTaskInstanceID :one
SELECT
  te.id AS exec_id,
  te.gmt_start,
  te.gmt_end,
  te.status AS exec_status,
  te.log,
  ti.id AS instance_id,
  ti.status AS instance_status,
  td.id AS def_id,
  td.name AS def_name,
  td.task_type
FROM task_exec te
JOIN task_instance ti ON te.task_instance_id = ti.id
JOIN task_def td ON ti.task_def_id = td.id
WHERE te.id = ?
`

type GetTaskExecDetailByTaskInstanceIDRow struct {
	ExecID         int64                  `json:"exec_id"`
	GmtStart       sql.NullTime           `json:"gmt_start"`
	GmtEnd         sql.NullTime           `json:"gmt_end"`
	ExecStatus     NullTaskExecStatus     `json:"exec_status"`
	Log            sql.NullString         `json:"log"`
	InstanceID     int64                  `json:"instance_id"`
	InstanceStatus NullTaskInstanceStatus `json:"instance_status"`
	DefID          int64                  `json:"def_id"`
	DefName        string                 `json:"def_name"`
	TaskType       TaskDefTaskType        `json:"task_type"`
}

func (q *Queries) GetTaskExecDetailByTaskInstanceID(ctx context.Context, id int64) (GetTaskExecDetailByTaskInstanceIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTaskExecDetailByTaskInstanceID, id)
	var i GetTaskExecDetailByTaskInstanceIDRow
	err := row.Scan(
		&i.ExecID,
		&i.GmtStart,
		&i.GmtEnd,
		&i.ExecStatus,
		&i.Log,
		&i.InstanceID,
		&i.InstanceStatus,
		&i.DefID,
		&i.DefName,
		&i.TaskType,
	)
	return i, err
}

const getTaskExecLogByID = `-- name: GetTaskExecLogByID :one
SELECT log FROM task_exec WHERE id = ?
`

func (q *Queries) GetTaskExecLogByID(ctx context.Context, id int64) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getTaskExecLogByID, id)
	var log sql.NullString
	err := row.Scan(&log)
	return log, err
}

const listTaskExecDetailsByTaskDefID = `-- name: ListTaskExecDetailsByTaskDefID :many
SELECT
  te.id AS exec_id,
  te.gmt_start,
  te.gmt_end,
  te.status AS exec_status,
  ti.id AS instance_id,
  td.name AS def_name,
  td.task_type
FROM task_exec te
JOIN task_instance ti ON te.task_instance_id = ti.id
JOIN task_def td ON ti.task_def_id = td.id
WHERE td.id = ?
ORDER BY te.gmt_start DESC
LIMIT ? OFFSET ?
`

type ListTaskExecDetailsByTaskDefIDParams struct {
	ID     int64 `json:"id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListTaskExecDetailsByTaskDefIDRow struct {
	ExecID     int64              `json:"exec_id"`
	GmtStart   sql.NullTime       `json:"gmt_start"`
	GmtEnd     sql.NullTime       `json:"gmt_end"`
	ExecStatus NullTaskExecStatus `json:"exec_status"`
	InstanceID int64              `json:"instance_id"`
	DefName    string             `json:"def_name"`
	TaskType   TaskDefTaskType    `json:"task_type"`
}

func (q *Queries) ListTaskExecDetailsByTaskDefID(ctx context.Context, arg ListTaskExecDetailsByTaskDefIDParams) ([]ListTaskExecDetailsByTaskDefIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listTaskExecDetailsByTaskDefID, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskExecDetailsByTaskDefIDRow{}
	for rows.Next() {
		var i ListTaskExecDetailsByTaskDefIDRow
		if err := rows.Scan(
			&i.ExecID,
			&i.GmtStart,
			&i.GmtEnd,
			&i.ExecStatus,
			&i.InstanceID,
			&i.DefName,
			&i.TaskType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskExecs = `-- name: ListTaskExecs :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  task_instance_id,
  gmt_start,
  gmt_end,
  status,
  log
FROM task_exec
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListTaskExecsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTaskExecs(ctx context.Context, arg ListTaskExecsParams) ([]TaskExec, error) {
	rows, err := q.db.QueryContext(ctx, listTaskExecs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskExec{}
	for rows.Next() {
		var i TaskExec
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.TaskInstanceID,
			&i.GmtStart,
			&i.GmtEnd,
			&i.Status,
			&i.Log,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskExecsByTaskInstanceID = `-- name: ListTaskExecsByTaskInstanceID :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  task_instance_id,
  gmt_start,
  gmt_end,
  status,
  log
FROM task_exec
WHERE task_instance_id = ?
ORDER BY ID DESC
`

func (q *Queries) ListTaskExecsByTaskInstanceID(ctx context.Context, taskInstanceID int64) ([]TaskExec, error) {
	rows, err := q.db.QueryContext(ctx, listTaskExecsByTaskInstanceID, taskInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskExec{}
	for rows.Next() {
		var i TaskExec
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.TaskInstanceID,
			&i.GmtStart,
			&i.GmtEnd,
			&i.Status,
			&i.Log,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskExecFailed = `-- name: MarkTaskExecFailed :exec
UPDATE task_exec
SET status = 'FAILED', log = CONCAT(log, '\n', ?)
WHERE id = ?
`

type MarkTaskExecFailedParams struct {
	CONCAT interface{} `json:"concat"`
	ID     int64       `json:"id"`
}

func (q *Queries) MarkTaskExecFailed(ctx context.Context, arg MarkTaskExecFailedParams) error {
	_, err := q.db.ExecContext(ctx, markTaskExecFailed, arg.CONCAT, arg.ID)
	return err
}

const markTaskExecSuccess = `-- name: MarkTaskExecSuccess :exec
UPDATE task_exec
SET status = 'SUCCESS'
WHERE id = ?
`

func (q *Queries) MarkTaskExecSuccess(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markTaskExecSuccess, id)
	return err
}

const updateTaskExecStatus = `-- name: UpdateTaskExecStatus :exec
UPDATE task_exec
SET status = ?
WHERE id = ?
`

type UpdateTaskExecStatusParams struct {
	Status NullTaskExecStatus `json:"status"`
	ID     int64              `json:"id"`
}

func (q *Queries) UpdateTaskExecStatus(ctx context.Context, arg UpdateTaskExecStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskExecStatus, arg.Status, arg.ID)
	return err
}
