// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_workflow_node.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createTaskWorkflowNode = `-- name: CreateTaskWorkflowNode :execresult
INSERT INTO task_workflow_node (
  workflow_id,
  node_id,
  node_type,
  display_name,
  task_atomic_def_id,
  sub_workflow_id,
  condition_expr,
  node_config,
  retry_policy,
  timeout,
  ord
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskWorkflowNodeParams struct {
	WorkflowID      int64                    `json:"workflow_id"`
	NodeID          string                   `json:"node_id"`
	NodeType        TaskWorkflowNodeNodeType `json:"node_type"`
	DisplayName     string                   `json:"display_name"`
	TaskAtomicDefID sql.NullInt64            `json:"task_atomic_def_id"`
	SubWorkflowID   sql.NullInt64            `json:"sub_workflow_id"`
	ConditionExpr   sql.NullString           `json:"condition_expr"`
	NodeConfig      json.RawMessage          `json:"node_config"`
	RetryPolicy     json.RawMessage          `json:"retry_policy"`
	Timeout         sql.NullInt32            `json:"timeout"`
	Ord             sql.NullInt32            `json:"ord"`
}

func (q *Queries) CreateTaskWorkflowNode(ctx context.Context, arg CreateTaskWorkflowNodeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTaskWorkflowNode,
		arg.WorkflowID,
		arg.NodeID,
		arg.NodeType,
		arg.DisplayName,
		arg.TaskAtomicDefID,
		arg.SubWorkflowID,
		arg.ConditionExpr,
		arg.NodeConfig,
		arg.RetryPolicy,
		arg.Timeout,
		arg.Ord,
	)
}

const deleteTaskWorkflowNodeByWorkflowID = `-- name: DeleteTaskWorkflowNodeByWorkflowID :execresult
DELETE FROM task_workflow_node WHERE workflow_id = ?
`

func (q *Queries) DeleteTaskWorkflowNodeByWorkflowID(ctx context.Context, workflowID int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTaskWorkflowNodeByWorkflowID, workflowID)
}

const getTaskWorkflowNodeByID = `-- name: GetTaskWorkflowNodeByID :one
SELECT id, gmt_create, gmt_modified, workflow_id, node_id, node_type, display_name, task_atomic_def_id, sub_workflow_id, condition_expr, node_config, retry_policy, timeout, ord FROM task_workflow_node WHERE id = ?
`

func (q *Queries) GetTaskWorkflowNodeByID(ctx context.Context, id int64) (TaskWorkflowNode, error) {
	row := q.db.QueryRowContext(ctx, getTaskWorkflowNodeByID, id)
	var i TaskWorkflowNode
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.WorkflowID,
		&i.NodeID,
		&i.NodeType,
		&i.DisplayName,
		&i.TaskAtomicDefID,
		&i.SubWorkflowID,
		&i.ConditionExpr,
		&i.NodeConfig,
		&i.RetryPolicy,
		&i.Timeout,
		&i.Ord,
	)
	return i, err
}

const getTaskWorkflowNodeByWorkflowAndNodeID = `-- name: GetTaskWorkflowNodeByWorkflowAndNodeID :one
SELECT id, gmt_create, gmt_modified, workflow_id, node_id, node_type, display_name, task_atomic_def_id, sub_workflow_id, condition_expr, node_config, retry_policy, timeout, ord FROM task_workflow_node WHERE workflow_id = ? AND node_id = ?
`

type GetTaskWorkflowNodeByWorkflowAndNodeIDParams struct {
	WorkflowID int64  `json:"workflow_id"`
	NodeID     string `json:"node_id"`
}

func (q *Queries) GetTaskWorkflowNodeByWorkflowAndNodeID(ctx context.Context, arg GetTaskWorkflowNodeByWorkflowAndNodeIDParams) (TaskWorkflowNode, error) {
	row := q.db.QueryRowContext(ctx, getTaskWorkflowNodeByWorkflowAndNodeID, arg.WorkflowID, arg.NodeID)
	var i TaskWorkflowNode
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.WorkflowID,
		&i.NodeID,
		&i.NodeType,
		&i.DisplayName,
		&i.TaskAtomicDefID,
		&i.SubWorkflowID,
		&i.ConditionExpr,
		&i.NodeConfig,
		&i.RetryPolicy,
		&i.Timeout,
		&i.Ord,
	)
	return i, err
}

const listTaskWorkflowNodes = `-- name: ListTaskWorkflowNodes :many
SELECT id, gmt_create, gmt_modified, workflow_id, node_id, node_type, display_name, task_atomic_def_id, sub_workflow_id, condition_expr, node_config, retry_policy, timeout, ord FROM task_workflow_node
WHERE workflow_id = ?
ORDER BY ord ASC
`

func (q *Queries) ListTaskWorkflowNodes(ctx context.Context, workflowID int64) ([]TaskWorkflowNode, error) {
	rows, err := q.db.QueryContext(ctx, listTaskWorkflowNodes, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskWorkflowNode{}
	for rows.Next() {
		var i TaskWorkflowNode
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.WorkflowID,
			&i.NodeID,
			&i.NodeType,
			&i.DisplayName,
			&i.TaskAtomicDefID,
			&i.SubWorkflowID,
			&i.ConditionExpr,
			&i.NodeConfig,
			&i.RetryPolicy,
			&i.Timeout,
			&i.Ord,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
