// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_composite.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const addTaskComposite = `-- name: AddTaskComposite :execresult
INSERT INTO task_composite (task_tmpl_id, task_atomic_id, step_order, depends_on)
VALUES (?, ?, ?, ?)
`

type AddTaskCompositeParams struct {
	TaskTmplID   uint64          `json:"task_tmpl_id"`
	TaskAtomicID uint64          `json:"task_atomic_id"`
	StepOrder    int32           `json:"step_order"`
	DependsOn    json.RawMessage `json:"depends_on"`
}

func (q *Queries) AddTaskComposite(ctx context.Context, arg AddTaskCompositeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addTaskComposite,
		arg.TaskTmplID,
		arg.TaskAtomicID,
		arg.StepOrder,
		arg.DependsOn,
	)
}

const deleteTaskComposite = `-- name: DeleteTaskComposite :execrows
DELETE FROM task_composite
WHERE task_tmpl_id = ?
`

func (q *Queries) DeleteTaskComposite(ctx context.Context, taskTmplID uint64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTaskComposite, taskTmplID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTaskComposite = `-- name: GetTaskComposite :many
SELECT id, gmt_create, gmt_modified, task_tmpl_id, task_atomic_id, step_order, depends_on
FROM task_composite
WHERE task_tmpl_id = ?
ORDER BY step_order ASC
`

func (q *Queries) GetTaskComposite(ctx context.Context, taskTmplID uint64) ([]TaskComposite, error) {
	rows, err := q.db.QueryContext(ctx, getTaskComposite, taskTmplID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskComposite{}
	for rows.Next() {
		var i TaskComposite
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.TaskTmplID,
			&i.TaskAtomicID,
			&i.StepOrder,
			&i.DependsOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskAtomicByTaskTmplID = `-- name: ListTaskAtomicByTaskTmplID :many
SELECT t1.task_tmpl_id, t1.step_order, t2.id, t2.gmt_create, t2.gmt_modified, t2.name, t2.description, t2.task_type, t2.config, t2.is_enable
FROM task_composite t1
JOIN task_atomic t2 ON t1.atomic_id = t2.id
WHERE t1.task_tmpl_id = ?
ORDER BY t1.step_order ASC
`

type ListTaskAtomicByTaskTmplIDRow struct {
	TaskTmplID  uint64          `json:"task_tmpl_id"`
	StepOrder   int32           `json:"step_order"`
	ID          int64           `json:"id"`
	GmtCreate   time.Time       `json:"gmt_create"`
	GmtModified time.Time       `json:"gmt_modified"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	TaskType    string          `json:"task_type"`
	Config      json.RawMessage `json:"config"`
	IsEnable    bool            `json:"is_enable"`
}

func (q *Queries) ListTaskAtomicByTaskTmplID(ctx context.Context, taskTmplID uint64) ([]ListTaskAtomicByTaskTmplIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listTaskAtomicByTaskTmplID, taskTmplID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskAtomicByTaskTmplIDRow{}
	for rows.Next() {
		var i ListTaskAtomicByTaskTmplIDRow
		if err := rows.Scan(
			&i.TaskTmplID,
			&i.StepOrder,
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Name,
			&i.Description,
			&i.TaskType,
			&i.Config,
			&i.IsEnable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskComposite = `-- name: ListTaskComposite :many
SELECT id, gmt_create, gmt_modified, task_tmpl_id, task_atomic_id, step_order, depends_on
FROM task_composite
ORDER BY task_tmpl_id, step_order ASC
LIMIT ? OFFSET ?
`

type ListTaskCompositeParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTaskComposite(ctx context.Context, arg ListTaskCompositeParams) ([]TaskComposite, error) {
	rows, err := q.db.QueryContext(ctx, listTaskComposite, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskComposite{}
	for rows.Next() {
		var i TaskComposite
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.TaskTmplID,
			&i.TaskAtomicID,
			&i.StepOrder,
			&i.DependsOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
