// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_workflow_edge.sql

package repo

import (
	"context"
	"database/sql"
)

const createTaskWorkflowEdge = `-- name: CreateTaskWorkflowEdge :execresult
INSERT INTO task_workflow_edge (
  workflow_id,
  from_node_id,
  to_node_id,
  edge_type,
  condition_expr
) VALUES (?, ?, ?, ?, ?)
`

type CreateTaskWorkflowEdgeParams struct {
	WorkflowID    int64                        `json:"workflow_id"`
	FromNodeID    string                       `json:"from_node_id"`
	ToNodeID      string                       `json:"to_node_id"`
	EdgeType      NullTaskWorkflowEdgeEdgeType `json:"edge_type"`
	ConditionExpr sql.NullString               `json:"condition_expr"`
}

func (q *Queries) CreateTaskWorkflowEdge(ctx context.Context, arg CreateTaskWorkflowEdgeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTaskWorkflowEdge,
		arg.WorkflowID,
		arg.FromNodeID,
		arg.ToNodeID,
		arg.EdgeType,
		arg.ConditionExpr,
	)
}

const deleteTaskWorkflowEdgeByWorkflowID = `-- name: DeleteTaskWorkflowEdgeByWorkflowID :execresult
DELETE FROM task_workflow_edge WHERE workflow_id = ?
`

func (q *Queries) DeleteTaskWorkflowEdgeByWorkflowID(ctx context.Context, workflowID int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTaskWorkflowEdgeByWorkflowID, workflowID)
}

const listTaskWorkflowEdges = `-- name: ListTaskWorkflowEdges :many
SELECT id, gmt_create, gmt_modified, workflow_id, from_node_id, to_node_id, edge_type, condition_expr FROM task_workflow_edge
WHERE workflow_id = ?
ORDER BY id ASC
`

func (q *Queries) ListTaskWorkflowEdges(ctx context.Context, workflowID int64) ([]TaskWorkflowEdge, error) {
	rows, err := q.db.QueryContext(ctx, listTaskWorkflowEdges, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskWorkflowEdge{}
	for rows.Next() {
		var i TaskWorkflowEdge
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.WorkflowID,
			&i.FromNodeID,
			&i.ToNodeID,
			&i.EdgeType,
			&i.ConditionExpr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskWorkflowEdgesByFromNode = `-- name: ListTaskWorkflowEdgesByFromNode :many
SELECT id, gmt_create, gmt_modified, workflow_id, from_node_id, to_node_id, edge_type, condition_expr FROM task_workflow_edge
WHERE workflow_id = ? AND from_node_id = ?
ORDER BY id ASC
`

type ListTaskWorkflowEdgesByFromNodeParams struct {
	WorkflowID int64  `json:"workflow_id"`
	FromNodeID string `json:"from_node_id"`
}

func (q *Queries) ListTaskWorkflowEdgesByFromNode(ctx context.Context, arg ListTaskWorkflowEdgesByFromNodeParams) ([]TaskWorkflowEdge, error) {
	rows, err := q.db.QueryContext(ctx, listTaskWorkflowEdgesByFromNode, arg.WorkflowID, arg.FromNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskWorkflowEdge{}
	for rows.Next() {
		var i TaskWorkflowEdge
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.WorkflowID,
			&i.FromNodeID,
			&i.ToNodeID,
			&i.EdgeType,
			&i.ConditionExpr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
