// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_instance.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
)

const countTaskInstancesByDefID = `-- name: CountTaskInstancesByDefID :one
SELECT COUNT(*) AS cnt
FROM task_instance
WHERE task_def_id = ?
`

func (q *Queries) CountTaskInstancesByDefID(ctx context.Context, taskDefID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTaskInstancesByDefID, taskDefID)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const countTaskInstancesByStatus = `-- name: CountTaskInstancesByStatus :one
SELECT COUNT(*) AS cnt
FROM task_instance
WHERE status = ?
`

func (q *Queries) CountTaskInstancesByStatus(ctx context.Context, status NullTaskInstanceStatus) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTaskInstancesByStatus, status)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const createTaskInstance = `-- name: CreateTaskInstance :execresult
INSERT INTO task_instance (
  task_def_id,
  parent_instance_id,
  ord,
  status,
  result,
  err_msg
)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateTaskInstanceParams struct {
	TaskDefID        int64                  `json:"task_def_id"`
	ParentInstanceID sql.NullInt64          `json:"parent_instance_id"`
	Ord              sql.NullInt32          `json:"ord"`
	Status           NullTaskInstanceStatus `json:"status"`
	Result           json.RawMessage        `json:"result"`
	ErrMsg           sql.NullString         `json:"err_msg"`
}

func (q *Queries) CreateTaskInstance(ctx context.Context, arg CreateTaskInstanceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTaskInstance,
		arg.TaskDefID,
		arg.ParentInstanceID,
		arg.Ord,
		arg.Status,
		arg.Result,
		arg.ErrMsg,
	)
}

const deleteTaskInstanceByID = `-- name: DeleteTaskInstanceByID :exec
DELETE FROM task_instance WHERE id = ? LIMIT 1
`

func (q *Queries) DeleteTaskInstanceByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTaskInstanceByID, id)
	return err
}

const deleteTaskInstancesByParent = `-- name: DeleteTaskInstancesByParent :exec
DELETE FROM task_instance WHERE parent_instance_id = ?
`

func (q *Queries) DeleteTaskInstancesByParent(ctx context.Context, parentInstanceID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteTaskInstancesByParent, parentInstanceID)
	return err
}

const getChildTaskInstances = `-- name: GetChildTaskInstances :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  task_def_id,
  parent_instance_id,
  ord,
  status,
  result,
  err_msg
FROM task_instance
WHERE parent_instance_id = ?
ORDER BY ord ASC
`

func (q *Queries) GetChildTaskInstances(ctx context.Context, parentInstanceID sql.NullInt64) ([]TaskInstance, error) {
	rows, err := q.db.QueryContext(ctx, getChildTaskInstances, parentInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskInstance{}
	for rows.Next() {
		var i TaskInstance
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.TaskDefID,
			&i.ParentInstanceID,
			&i.Ord,
			&i.Status,
			&i.Result,
			&i.ErrMsg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRootTaskInstances = `-- name: GetRootTaskInstances :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  task_def_id,
  parent_instance_id,
  ord,
  status,
  result,
  err_msg
FROM task_instance
WHERE parent_instance_id IS NULL
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type GetRootTaskInstancesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetRootTaskInstances(ctx context.Context, arg GetRootTaskInstancesParams) ([]TaskInstance, error) {
	rows, err := q.db.QueryContext(ctx, getRootTaskInstances, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskInstance{}
	for rows.Next() {
		var i TaskInstance
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.TaskDefID,
			&i.ParentInstanceID,
			&i.Ord,
			&i.Status,
			&i.Result,
			&i.ErrMsg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskInstance = `-- name: GetTaskInstance :one
SELECT
  id,
  gmt_create,
  gmt_modified,
  task_def_id,
  parent_instance_id,
  ord,
  status,
  result,
  err_msg
FROM task_instance
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetTaskInstance(ctx context.Context, id int64) (TaskInstance, error) {
	row := q.db.QueryRowContext(ctx, getTaskInstance, id)
	var i TaskInstance
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.TaskDefID,
		&i.ParentInstanceID,
		&i.Ord,
		&i.Status,
		&i.Result,
		&i.ErrMsg,
	)
	return i, err
}

const getTaskInstanceSummary = `-- name: GetTaskInstanceSummary :one
SELECT
  SUM(CASE WHEN status = 'PENDING' THEN 1 ELSE 0 END) AS pending_count,
  SUM(CASE WHEN status = 'RUNNING' THEN 1 ELSE 0 END) AS running_count,
  SUM(CASE WHEN status = 'SUCCESS' THEN 1 ELSE 0 END) AS success_count,
  SUM(CASE WHEN status = 'FAILED' THEN 1 ELSE 0 END) AS failed_count,
  SUM(CASE WHEN status = 'CANCELLED' THEN 1 ELSE 0 END) AS cancelled_count
FROM task_instance
`

type GetTaskInstanceSummaryRow struct {
	PendingCount   interface{} `json:"pending_count"`
	RunningCount   interface{} `json:"running_count"`
	SuccessCount   interface{} `json:"success_count"`
	FailedCount    interface{} `json:"failed_count"`
	CancelledCount interface{} `json:"cancelled_count"`
}

func (q *Queries) GetTaskInstanceSummary(ctx context.Context) (GetTaskInstanceSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getTaskInstanceSummary)
	var i GetTaskInstanceSummaryRow
	err := row.Scan(
		&i.PendingCount,
		&i.RunningCount,
		&i.SuccessCount,
		&i.FailedCount,
		&i.CancelledCount,
	)
	return i, err
}

const getTaskInstanceTree = `-- name: GetTaskInstanceTree :many
WITH RECURSIVE instance_tree AS (
  SELECT
    ti.id,
    ti.task_def_id,
    ti.parent_instance_id,
    ti.ord,
    ti.status,
    ti.result,
    ti.err_msg,
    td.name AS task_name,
    td.task_type
  FROM task_instance ti
  JOIN task_def td ON ti.task_def_id = td.id
  WHERE ti.id = ?
  UNION ALL
  SELECT
    ti.id,
    ti.task_def_id,
    ti.parent_instance_id,
    ti.ord,
    ti.status,
    ti.result,
    ti.err_msg,
    td.name AS task_name,
    td.task_type
  FROM task_instance ti
  JOIN task_def td ON ti.task_def_id = td.id
  JOIN instance_tree it ON ti.parent_instance_id = it.id
)
SELECT id, task_def_id, parent_instance_id, ord, status, result, err_msg, task_name, task_type FROM instance_tree ORDER BY parent_instance_id, ord
`

type GetTaskInstanceTreeRow struct {
	ID               int64                  `json:"id"`
	TaskDefID        int64                  `json:"task_def_id"`
	ParentInstanceID sql.NullInt64          `json:"parent_instance_id"`
	Ord              sql.NullInt32          `json:"ord"`
	Status           NullTaskInstanceStatus `json:"status"`
	Result           json.RawMessage        `json:"result"`
	ErrMsg           sql.NullString         `json:"err_msg"`
	TaskName         string                 `json:"task_name"`
	TaskType         TaskDefTaskType        `json:"task_type"`
}

func (q *Queries) GetTaskInstanceTree(ctx context.Context, id int64) ([]GetTaskInstanceTreeRow, error) {
	rows, err := q.db.QueryContext(ctx, getTaskInstanceTree, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTaskInstanceTreeRow{}
	for rows.Next() {
		var i GetTaskInstanceTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskDefID,
			&i.ParentInstanceID,
			&i.Ord,
			&i.Status,
			&i.Result,
			&i.ErrMsg,
			&i.TaskName,
			&i.TaskType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskInstances = `-- name: ListTaskInstances :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  task_def_id,
  parent_instance_id,
  ord,
  status,
  result,
  err_msg
FROM task_instance
ORDER BY ID DESC
LIMIT ? OFFSET ?
`

type ListTaskInstancesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTaskInstances(ctx context.Context, arg ListTaskInstancesParams) ([]TaskInstance, error) {
	rows, err := q.db.QueryContext(ctx, listTaskInstances, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskInstance{}
	for rows.Next() {
		var i TaskInstance
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.TaskDefID,
			&i.ParentInstanceID,
			&i.Ord,
			&i.Status,
			&i.Result,
			&i.ErrMsg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskInstancesByStatus = `-- name: ListTaskInstancesByStatus :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  task_def_id,
  parent_instance_id,
  ord,
  status,
  result,
  err_msg
FROM task_instance
WHERE status = ?
ORDER BY gmt_create DESC
LIMIT ? OFFSET ?
`

type ListTaskInstancesByStatusParams struct {
	Status NullTaskInstanceStatus `json:"status"`
	Limit  int32                  `json:"limit"`
	Offset int32                  `json:"offset"`
}

func (q *Queries) ListTaskInstancesByStatus(ctx context.Context, arg ListTaskInstancesByStatusParams) ([]TaskInstance, error) {
	rows, err := q.db.QueryContext(ctx, listTaskInstancesByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskInstance{}
	for rows.Next() {
		var i TaskInstance
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.TaskDefID,
			&i.ParentInstanceID,
			&i.Ord,
			&i.Status,
			&i.Result,
			&i.ErrMsg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskInstancesByTaskDefID = `-- name: ListTaskInstancesByTaskDefID :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  task_def_id,
  parent_instance_id,
  ord,
  status,
  result,
  err_msg
FROM task_instance
WHERE task_def_id = ?
ORDER BY gmt_create DESC
`

func (q *Queries) ListTaskInstancesByTaskDefID(ctx context.Context, taskDefID int64) ([]TaskInstance, error) {
	rows, err := q.db.QueryContext(ctx, listTaskInstancesByTaskDefID, taskDefID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskInstance{}
	for rows.Next() {
		var i TaskInstance
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.TaskDefID,
			&i.ParentInstanceID,
			&i.Ord,
			&i.Status,
			&i.Result,
			&i.ErrMsg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPendingInstances = `-- name: LockPendingInstances :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  task_def_id,
  parent_instance_id,
  ord,
  status,
  result,
  err_msg
FROM task_instance
WHERE status = 'PENDING'
ORDER BY id DESC
LIMIT ?
FOR UPDATE SKIP LOCKED
`

func (q *Queries) LockPendingInstances(ctx context.Context, limit int32) ([]TaskInstance, error) {
	rows, err := q.db.QueryContext(ctx, lockPendingInstances, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskInstance{}
	for rows.Next() {
		var i TaskInstance
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.TaskDefID,
			&i.ParentInstanceID,
			&i.Ord,
			&i.Status,
			&i.Result,
			&i.ErrMsg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTaskInstanceForUpdate = `-- name: LockTaskInstanceForUpdate :one
SELECT
  id,
  gmt_create,
  gmt_modified,
  task_def_id,
  parent_instance_id,
  ord,
  status,
  result,
  err_msg
FROM task_instance
WHERE id = ?
FOR UPDATE
`

func (q *Queries) LockTaskInstanceForUpdate(ctx context.Context, id int64) (TaskInstance, error) {
	row := q.db.QueryRowContext(ctx, lockTaskInstanceForUpdate, id)
	var i TaskInstance
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.TaskDefID,
		&i.ParentInstanceID,
		&i.Ord,
		&i.Status,
		&i.Result,
		&i.ErrMsg,
	)
	return i, err
}

const resetTaskInstanceStatus = `-- name: ResetTaskInstanceStatus :exec
UPDATE task_instance
SET status = 'PENDING', result = NULL, err_msg = NULL
WHERE id = ?
LIMIT 1
`

func (q *Queries) ResetTaskInstanceStatus(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, resetTaskInstanceStatus, id)
	return err
}

const updateTaskInstanceResult = `-- name: UpdateTaskInstanceResult :exec
UPDATE task_instance
SET result = ?, err_msg = ?, status = ?
WHERE id = ?
LIMIT 1
`

type UpdateTaskInstanceResultParams struct {
	Result json.RawMessage        `json:"result"`
	ErrMsg sql.NullString         `json:"err_msg"`
	Status NullTaskInstanceStatus `json:"status"`
	ID     int64                  `json:"id"`
}

func (q *Queries) UpdateTaskInstanceResult(ctx context.Context, arg UpdateTaskInstanceResultParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskInstanceResult,
		arg.Result,
		arg.ErrMsg,
		arg.Status,
		arg.ID,
	)
	return err
}

const updateTaskInstanceStatus = `-- name: UpdateTaskInstanceStatus :exec
UPDATE task_instance
SET status = ?
WHERE id = ?
LIMIT 1
`

type UpdateTaskInstanceStatusParams struct {
	Status NullTaskInstanceStatus `json:"status"`
	ID     int64                  `json:"id"`
}

func (q *Queries) UpdateTaskInstanceStatus(ctx context.Context, arg UpdateTaskInstanceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskInstanceStatus, arg.Status, arg.ID)
	return err
}
