// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo_list.sql

package repo

import (
	"context"
	"database/sql"
)

const completeTodoListByID = `-- name: CompleteTodoListByID :execresult
UPDATE todo_list
SET progress = 100,
    task_status = 'COMPLETED'
WHERE id = ?
LIMIT 1
`

func (q *Queries) CompleteTodoListByID(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, completeTodoListByID, id)
}

const countTodoList = `-- name: CountTodoList :one
SELECT count(*) ct FROM todo_list
`

func (q *Queries) CountTodoList(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTodoList)
	var ct int64
	err := row.Scan(&ct)
	return ct, err
}

const createTodoList = `-- name: CreateTodoList :execresult
INSERT INTO todo_list (title, content, deadline, progress, priority, task_status)
VALUES (?, ?, ?, 0, 5, 'PENDING')
`

type CreateTodoListParams struct {
	Title    string `json:"title"`
	Content  string `json:"content"`
	Deadline string `json:"deadline"`
}

func (q *Queries) CreateTodoList(ctx context.Context, arg CreateTodoListParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTodoList, arg.Title, arg.Content, arg.Deadline)
}

const deleteTodoListByID = `-- name: DeleteTodoListByID :execresult
DELETE FROM todo_list
WHERE id = ?
LIMIT 1
`

func (q *Queries) DeleteTodoListByID(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTodoListByID, id)
}

const getTodoListByID = `-- name: GetTodoListByID :one
SELECT
  id,
  gmt_create,
  gmt_modified,
  title,
  content,
  deadline,
  progress,
  priority,
  task_status
FROM todo_list
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetTodoListByID(ctx context.Context, id int64) (TodoList, error) {
	row := q.db.QueryRowContext(ctx, getTodoListByID, id)
	var i TodoList
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Title,
		&i.Content,
		&i.Deadline,
		&i.Progress,
		&i.Priority,
		&i.TaskStatus,
	)
	return i, err
}

const listTodoLists = `-- name: ListTodoLists :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  title,
  content,
  deadline,
  progress,
  priority,
  task_status
FROM todo_list
ORDER BY priority DESC, id DESC
LIMIT ? OFFSET ?
`

type ListTodoListsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTodoLists(ctx context.Context, arg ListTodoListsParams) ([]TodoList, error) {
	rows, err := q.db.QueryContext(ctx, listTodoLists, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoList{}
	for rows.Next() {
		var i TodoList
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Title,
			&i.Content,
			&i.Deadline,
			&i.Progress,
			&i.Priority,
			&i.TaskStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTodoListsByContent = `-- name: SearchTodoListsByContent :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  title,
  content,
  deadline,
  progress,
  priority,
  task_status
FROM todo_list
WHERE content like ?
ORDER BY priority DESC, id DESC
LIMIT ? OFFSET ?
`

type SearchTodoListsByContentParams struct {
	Content string `json:"content"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) SearchTodoListsByContent(ctx context.Context, arg SearchTodoListsByContentParams) ([]TodoList, error) {
	rows, err := q.db.QueryContext(ctx, searchTodoListsByContent, arg.Content, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoList{}
	for rows.Next() {
		var i TodoList
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Title,
			&i.Content,
			&i.Deadline,
			&i.Progress,
			&i.Priority,
			&i.TaskStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTodoListsByDeadlineLT = `-- name: SearchTodoListsByDeadlineLT :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  title,
  content,
  deadline,
  progress,
  priority,
  task_status
FROM todo_list
WHERE deadline < ?
ORDER BY priority DESC, id DESC
LIMIT ? OFFSET ?
`

type SearchTodoListsByDeadlineLTParams struct {
	Deadline string `json:"deadline"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) SearchTodoListsByDeadlineLT(ctx context.Context, arg SearchTodoListsByDeadlineLTParams) ([]TodoList, error) {
	rows, err := q.db.QueryContext(ctx, searchTodoListsByDeadlineLT, arg.Deadline, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoList{}
	for rows.Next() {
		var i TodoList
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Title,
			&i.Content,
			&i.Deadline,
			&i.Progress,
			&i.Priority,
			&i.TaskStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTodoListsByTitle = `-- name: SearchTodoListsByTitle :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  title,
  content,
  deadline,
  progress,
  priority,
  task_status
FROM todo_list
WHERE title like ?
ORDER BY priority DESC, id DESC
LIMIT ? OFFSET ?
`

type SearchTodoListsByTitleParams struct {
	Title  string `json:"title"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SearchTodoListsByTitle(ctx context.Context, arg SearchTodoListsByTitleParams) ([]TodoList, error) {
	rows, err := q.db.QueryContext(ctx, searchTodoListsByTitle, arg.Title, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoList{}
	for rows.Next() {
		var i TodoList
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Title,
			&i.Content,
			&i.Deadline,
			&i.Progress,
			&i.Priority,
			&i.TaskStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTodoListsByTitleAndContent = `-- name: SearchTodoListsByTitleAndContent :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  title,
  content,
  deadline,
  progress,
  priority,
  task_status
FROM todo_list
WHERE title like ?
  AND content like ?
ORDER BY priority, id
LIMIT ? OFFSET ?
`

type SearchTodoListsByTitleAndContentParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) SearchTodoListsByTitleAndContent(ctx context.Context, arg SearchTodoListsByTitleAndContentParams) ([]TodoList, error) {
	rows, err := q.db.QueryContext(ctx, searchTodoListsByTitleAndContent,
		arg.Title,
		arg.Content,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoList{}
	for rows.Next() {
		var i TodoList
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Title,
			&i.Content,
			&i.Deadline,
			&i.Progress,
			&i.Priority,
			&i.TaskStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodoListByID = `-- name: UpdateTodoListByID :execresult
UPDATE todo_list
SET  title = ?,
   content = ?,
   deadline = ?,
   progress = ?,
   priority = ?,
   task_status = ?
WHERE id = ?
LIMIT 1
`

type UpdateTodoListByIDParams struct {
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	Deadline   string             `json:"deadline"`
	Progress   int32              `json:"progress"`
	Priority   int32              `json:"priority"`
	TaskStatus TodoListTaskStatus `json:"task_status"`
	ID         int64              `json:"id"`
}

func (q *Queries) UpdateTodoListByID(ctx context.Context, arg UpdateTodoListByIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTodoListByID,
		arg.Title,
		arg.Content,
		arg.Deadline,
		arg.Progress,
		arg.Priority,
		arg.TaskStatus,
		arg.ID,
	)
}

const updateTodoListPriorityByID = `-- name: UpdateTodoListPriorityByID :execresult
UPDATE todo_list
SET priority = ?
WHERE id = ?
LIMIT 1
`

type UpdateTodoListPriorityByIDParams struct {
	Priority int32 `json:"priority"`
	ID       int64 `json:"id"`
}

func (q *Queries) UpdateTodoListPriorityByID(ctx context.Context, arg UpdateTodoListPriorityByIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTodoListPriorityByID, arg.Priority, arg.ID)
}

const updateTodoListProgressByID = `-- name: UpdateTodoListProgressByID :execresult
UPDATE todo_list
SET progress = ?,
    task_status = CASE WHEN ? >= 100 THEN 'COMPLETED' ELSE 'IN_PROGRESS' END
WHERE id = ?
LIMIT 1
`

type UpdateTodoListProgressByIDParams struct {
	Progress int32       `json:"progress"`
	Column2  interface{} `json:"column_2"`
	ID       int64       `json:"id"`
}

func (q *Queries) UpdateTodoListProgressByID(ctx context.Context, arg UpdateTodoListProgressByIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTodoListProgressByID, arg.Progress, arg.Column2, arg.ID)
}
