// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo_list.sql

package repo

import (
	"context"
	"database/sql"
)

const countTodoList = `-- name: CountTodoList :one
SELECT count(*) ct FROM todo_list
`

func (q *Queries) CountTodoList(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTodoList)
	var ct int64
	err := row.Scan(&ct)
	return ct, err
}

const createTodoList = `-- name: CreateTodoList :execresult
INSERT INTO todo_list (title, content, deadline)
VALUES (?, ?, ?)
`

type CreateTodoListParams struct {
	Title    string `json:"title"`
	Content  string `json:"content"`
	Deadline string `json:"deadline"`
}

func (q *Queries) CreateTodoList(ctx context.Context, arg CreateTodoListParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTodoList, arg.Title, arg.Content, arg.Deadline)
}

const deleteTodoList = `-- name: DeleteTodoList :execresult
DELETE FROM todo_list
WHERE id = ?
LIMIT 1
`

func (q *Queries) DeleteTodoList(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTodoList, id)
}

const doneTodoList = `-- name: DoneTodoList :execresult
UPDATE todo_list
SET is_done = 1
WHERE id = ?
LIMIT 1
`

func (q *Queries) DoneTodoList(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, doneTodoList, id)
}

const getTodoList = `-- name: GetTodoList :one
SELECT id, gmt_create, gmt_modified, title, content, deadline, is_done
FROM todo_list
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetTodoList(ctx context.Context, id int64) (TodoList, error) {
	row := q.db.QueryRowContext(ctx, getTodoList, id)
	var i TodoList
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Title,
		&i.Content,
		&i.Deadline,
		&i.IsDone,
	)
	return i, err
}

const listTodoLists = `-- name: ListTodoLists :many
SELECT id, gmt_create, gmt_modified, title, content, deadline, is_done
FROM todo_list
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListTodoListsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTodoLists(ctx context.Context, arg ListTodoListsParams) ([]TodoList, error) {
	rows, err := q.db.QueryContext(ctx, listTodoLists, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoList{}
	for rows.Next() {
		var i TodoList
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Title,
			&i.Content,
			&i.Deadline,
			&i.IsDone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTodoListsByContent = `-- name: SearchTodoListsByContent :many
SELECT id, gmt_create, gmt_modified, title, content, deadline, is_done
FROM todo_list
WHERE content like ?
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type SearchTodoListsByContentParams struct {
	Content string `json:"content"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) SearchTodoListsByContent(ctx context.Context, arg SearchTodoListsByContentParams) ([]TodoList, error) {
	rows, err := q.db.QueryContext(ctx, searchTodoListsByContent, arg.Content, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoList{}
	for rows.Next() {
		var i TodoList
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Title,
			&i.Content,
			&i.Deadline,
			&i.IsDone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTodoListsByDeadlineLT = `-- name: SearchTodoListsByDeadlineLT :many
SELECT id, gmt_create, gmt_modified, title, content, deadline, is_done
FROM todo_list
WHERE deadline < ?
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type SearchTodoListsByDeadlineLTParams struct {
	Deadline string `json:"deadline"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) SearchTodoListsByDeadlineLT(ctx context.Context, arg SearchTodoListsByDeadlineLTParams) ([]TodoList, error) {
	rows, err := q.db.QueryContext(ctx, searchTodoListsByDeadlineLT, arg.Deadline, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoList{}
	for rows.Next() {
		var i TodoList
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Title,
			&i.Content,
			&i.Deadline,
			&i.IsDone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTodoListsByTitle = `-- name: SearchTodoListsByTitle :many
SELECT id, gmt_create, gmt_modified, title, content, deadline, is_done
FROM todo_list
WHERE title like ?
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type SearchTodoListsByTitleParams struct {
	Title  string `json:"title"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SearchTodoListsByTitle(ctx context.Context, arg SearchTodoListsByTitleParams) ([]TodoList, error) {
	rows, err := q.db.QueryContext(ctx, searchTodoListsByTitle, arg.Title, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoList{}
	for rows.Next() {
		var i TodoList
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Title,
			&i.Content,
			&i.Deadline,
			&i.IsDone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTodoListsByTitleContent = `-- name: SearchTodoListsByTitleContent :many
SELECT id, gmt_create, gmt_modified, title, content, deadline, is_done
FROM todo_list
WHERE title like ?
  AND content like ?
ORDER BY id
LIMIT ? OFFSET ?
`

type SearchTodoListsByTitleContentParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) SearchTodoListsByTitleContent(ctx context.Context, arg SearchTodoListsByTitleContentParams) ([]TodoList, error) {
	rows, err := q.db.QueryContext(ctx, searchTodoListsByTitleContent,
		arg.Title,
		arg.Content,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoList{}
	for rows.Next() {
		var i TodoList
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Title,
			&i.Content,
			&i.Deadline,
			&i.IsDone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodoList = `-- name: UpdateTodoList :execresult
UPDATE todo_list
SET  title = ?,
   content = ?,
  deadline = ?
WHERE id = ?
LIMIT 1
`

type UpdateTodoListParams struct {
	Title    string `json:"title"`
	Content  string `json:"content"`
	Deadline string `json:"deadline"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateTodoList(ctx context.Context, arg UpdateTodoListParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTodoList,
		arg.Title,
		arg.Content,
		arg.Deadline,
		arg.ID,
	)
}
