// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wiki.sql

package repo

import (
	"context"
	"database/sql"
)

const countWiki = `-- name: CountWiki :one
SELECT count(*) ct FROM wiki
`

func (q *Queries) CountWiki(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWiki)
	var ct int64
	err := row.Scan(&ct)
	return ct, err
}

const createWiki = `-- name: CreateWiki :execresult
INSERT INTO wiki (title, content, keywords, content_hash, created_by)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  content = VALUES(content),
  keywords = VALUES(keywords),
  gmt_modified = CURRENT_TIMESTAMP
`

type CreateWikiParams struct {
	Title       string `json:"title"`
	Content     string `json:"content"`
	Keywords    string `json:"keywords"`
	ContentHash string `json:"content_hash"`
	CreatedBy   string `json:"created_by"`
}

func (q *Queries) CreateWiki(ctx context.Context, arg CreateWikiParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createWiki,
		arg.Title,
		arg.Content,
		arg.Keywords,
		arg.ContentHash,
		arg.CreatedBy,
	)
}

const deleteWikiByID = `-- name: DeleteWikiByID :execresult
DELETE FROM wiki WHERE id = ? LIMIT 1
`

func (q *Queries) DeleteWikiByID(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteWikiByID, id)
}

const getWikiByHash = `-- name: GetWikiByHash :one
SELECT
  id,
  gmt_create,
  gmt_modified,
  title,
  content,
  keywords,
  content_hash,
  created_by
FROM wiki
WHERE content_hash = ?
LIMIT 1
`

func (q *Queries) GetWikiByHash(ctx context.Context, contentHash string) (Wiki, error) {
	row := q.db.QueryRowContext(ctx, getWikiByHash, contentHash)
	var i Wiki
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Title,
		&i.Content,
		&i.Keywords,
		&i.ContentHash,
		&i.CreatedBy,
	)
	return i, err
}

const getWikiByID = `-- name: GetWikiByID :one
SELECT
  id,
  gmt_create,
  gmt_modified,
  title,
  content,
  keywords,
  content_hash,
  created_by
FROM wiki
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetWikiByID(ctx context.Context, id int64) (Wiki, error) {
	row := q.db.QueryRowContext(ctx, getWikiByID, id)
	var i Wiki
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Title,
		&i.Content,
		&i.Keywords,
		&i.ContentHash,
		&i.CreatedBy,
	)
	return i, err
}

const listWiki = `-- name: ListWiki :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  title,
  content,
  keywords,
  content_hash,
  created_by
FROM wiki
ORDER BY gmt_modified DESC
LIMIT ? OFFSET ?
`

type ListWikiParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListWiki(ctx context.Context, arg ListWikiParams) ([]Wiki, error) {
	rows, err := q.db.QueryContext(ctx, listWiki, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wiki{}
	for rows.Next() {
		var i Wiki
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Title,
			&i.Content,
			&i.Keywords,
			&i.ContentHash,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchWiki = `-- name: SearchWiki :many
SELECT
  id,
  gmt_create,
  gmt_modified,
  title,
  content,
  keywords,
  content_hash,
  created_by
FROM wiki
WHERE MATCH(title, keywords, content) AGAINST(? IN NATURAL LANGUAGE MODE)
ORDER BY MATCH(title, keywords, content) AGAINST(? IN NATURAL LANGUAGE MODE) DESC
LIMIT ?
`

type SearchWikiParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) SearchWiki(ctx context.Context, arg SearchWikiParams) ([]Wiki, error) {
	rows, err := q.db.QueryContext(ctx, searchWiki, arg.Column1, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wiki{}
	for rows.Next() {
		var i Wiki
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Title,
			&i.Content,
			&i.Keywords,
			&i.ContentHash,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
