// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
)

const countTaskWorkflowDefs = `-- name: CountTaskWorkflowDefs :one
SELECT COUNT(*) AS cnt FROM task_workflow_def WHERE status != 'DEPRECATED'
`

func (q *Queries) CountTaskWorkflowDefs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTaskWorkflowDefs)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const createTaskWorkflowDef = `-- name: CreateTaskWorkflowDef :execresult
INSERT INTO task_workflow_def (
  name,
  description,
  version,
  workflow_type,
  graph_config,
  parameters,
  timeout,
  on_error_strategy,
  notification_config,
  status,
  created_by
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskWorkflowDefParams struct {
	Name               string                             `json:"name"`
	Description        sql.NullString                     `json:"description"`
	Version            sql.NullInt32                      `json:"version"`
	WorkflowType       TaskWorkflowDefWorkflowType        `json:"workflow_type"`
	GraphConfig        json.RawMessage                    `json:"graph_config"`
	Parameters         json.RawMessage                    `json:"parameters"`
	Timeout            sql.NullInt32                      `json:"timeout"`
	OnErrorStrategy    NullTaskWorkflowDefOnErrorStrategy `json:"on_error_strategy"`
	NotificationConfig json.RawMessage                    `json:"notification_config"`
	Status             NullTaskWorkflowDefStatus          `json:"status"`
	CreatedBy          sql.NullString                     `json:"created_by"`
}

func (q *Queries) CreateTaskWorkflowDef(ctx context.Context, arg CreateTaskWorkflowDefParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTaskWorkflowDef,
		arg.Name,
		arg.Description,
		arg.Version,
		arg.WorkflowType,
		arg.GraphConfig,
		arg.Parameters,
		arg.Timeout,
		arg.OnErrorStrategy,
		arg.NotificationConfig,
		arg.Status,
		arg.CreatedBy,
	)
}

const deleteTaskWorkflowDefByID = `-- name: DeleteTaskWorkflowDefByID :execresult
DELETE FROM task_workflow_def WHERE id = ? LIMIT 1
`

func (q *Queries) DeleteTaskWorkflowDefByID(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTaskWorkflowDefByID, id)
}

const getTaskWorkflowDefByID = `-- name: GetTaskWorkflowDefByID :one
SELECT id, gmt_create, gmt_modified, name, description, version, workflow_type, graph_config, parameters, timeout, on_error_strategy, notification_config, status, created_by FROM task_workflow_def WHERE id = ?
`

func (q *Queries) GetTaskWorkflowDefByID(ctx context.Context, id int64) (TaskWorkflowDef, error) {
	row := q.db.QueryRowContext(ctx, getTaskWorkflowDefByID, id)
	var i TaskWorkflowDef
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.WorkflowType,
		&i.GraphConfig,
		&i.Parameters,
		&i.Timeout,
		&i.OnErrorStrategy,
		&i.NotificationConfig,
		&i.Status,
		&i.CreatedBy,
	)
	return i, err
}

const getTaskWorkflowDefByName = `-- name: GetTaskWorkflowDefByName :one
SELECT id, gmt_create, gmt_modified, name, description, version, workflow_type, graph_config, parameters, timeout, on_error_strategy, notification_config, status, created_by FROM task_workflow_def WHERE name = ? ORDER BY version DESC LIMIT 1
`

func (q *Queries) GetTaskWorkflowDefByName(ctx context.Context, name string) (TaskWorkflowDef, error) {
	row := q.db.QueryRowContext(ctx, getTaskWorkflowDefByName, name)
	var i TaskWorkflowDef
	err := row.Scan(
		&i.ID,
		&i.GmtCreate,
		&i.GmtModified,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.WorkflowType,
		&i.GraphConfig,
		&i.Parameters,
		&i.Timeout,
		&i.OnErrorStrategy,
		&i.NotificationConfig,
		&i.Status,
		&i.CreatedBy,
	)
	return i, err
}

const listTaskWorkflowDefs = `-- name: ListTaskWorkflowDefs :many
SELECT id, gmt_create, gmt_modified, name, description, version, workflow_type, graph_config, parameters, timeout, on_error_strategy, notification_config, status, created_by FROM task_workflow_def
WHERE status != 'DEPRECATED'
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListTaskWorkflowDefsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTaskWorkflowDefs(ctx context.Context, arg ListTaskWorkflowDefsParams) ([]TaskWorkflowDef, error) {
	rows, err := q.db.QueryContext(ctx, listTaskWorkflowDefs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskWorkflowDef{}
	for rows.Next() {
		var i TaskWorkflowDef
		if err := rows.Scan(
			&i.ID,
			&i.GmtCreate,
			&i.GmtModified,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.WorkflowType,
			&i.GraphConfig,
			&i.Parameters,
			&i.Timeout,
			&i.OnErrorStrategy,
			&i.NotificationConfig,
			&i.Status,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskWorkflowDefByID = `-- name: UpdateTaskWorkflowDefByID :execresult
UPDATE task_workflow_def SET
  name = ?,
  description = ?,
  workflow_type = ?,
  graph_config = ?,
  parameters = ?,
  timeout = ?,
  on_error_strategy = ?,
  notification_config = ?,
  status = ?
WHERE id = ?
`

type UpdateTaskWorkflowDefByIDParams struct {
	Name               string                             `json:"name"`
	Description        sql.NullString                     `json:"description"`
	WorkflowType       TaskWorkflowDefWorkflowType        `json:"workflow_type"`
	GraphConfig        json.RawMessage                    `json:"graph_config"`
	Parameters         json.RawMessage                    `json:"parameters"`
	Timeout            sql.NullInt32                      `json:"timeout"`
	OnErrorStrategy    NullTaskWorkflowDefOnErrorStrategy `json:"on_error_strategy"`
	NotificationConfig json.RawMessage                    `json:"notification_config"`
	Status             NullTaskWorkflowDefStatus          `json:"status"`
	ID                 int64                              `json:"id"`
}

func (q *Queries) UpdateTaskWorkflowDefByID(ctx context.Context, arg UpdateTaskWorkflowDefByIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTaskWorkflowDefByID,
		arg.Name,
		arg.Description,
		arg.WorkflowType,
		arg.GraphConfig,
		arg.Parameters,
		arg.Timeout,
		arg.OnErrorStrategy,
		arg.NotificationConfig,
		arg.Status,
		arg.ID,
	)
}
